MsPASS C++ API: mspass::algorithms::deconvolution::CNRDeconEngine Class Reference
mspass::algorithms::deconvolution::CNRDeconEngine Class Reference
Colored-noise regularized three-component deconvolution engine.
#include <CNRDeconEngine.h>
Public Member Functions
CNRDeconEngine ()
CNRDeconEngine (const mspass::utility::AntelopePf &pf)
CNRDeconEngine (const CNRDeconEngine &parent)
void changeparameter (const mspass::utility::Metadata &md)
void initialize_inverse_operator (const mspass::seismic::TimeSeries &wavelet, const mspass::seismic::TimeSeries &noise_data)
void initialize_inverse_operator (const mspass::seismic::TimeSeries &wavelet, const mspass::seismic::PowerSpectrum &noise_spectrum)
virtual ~CNRDeconEngine ()
mspass::seismic::Seismogram process (const mspass::seismic::Seismogram &d, const mspass::seismic::PowerSpectrum &psnoise, const double fl, const double fh)
double get_operator_dt () const
mspass::seismic::PowerSpectrum compute_noise_spectrum (const mspass::seismic::TimeSeries &d2use)
mspass::seismic::PowerSpectrum compute_noise_spectrum (const mspass::seismic::Seismogram &d2use)
mspass::seismic::TimeSeries output_shaping_wavelet ()
Return the output shaping wavelet.
mspass::seismic::TimeSeries ideal_output ()
mspass::seismic::TimeSeries actual_output (const mspass::seismic::TimeSeries &wavelet)
mspass::seismic::TimeSeries resolution_kernel (const mspass::seismic::TimeSeries &wavelet)
Alias for actual_output using inverse-theory terminology.
mspass::seismic::TimeSeries inverse_wavelet (const mspass::seismic::TimeSeries &wavelet, const double t0shift)
mspass::utility::Metadata QCMetrics ()
CNRDeconEngine & operator= (const CNRDeconEngine &parent)
Public Member Functions inherited from mspass::algorithms::deconvolution::FFTDeconOperator
FFTDeconOperator ()
Construct an empty FFT operator shell.
FFTDeconOperator (const mspass::utility::Metadata &md)
Construct from deconvolution Metadata.
FFTDeconOperator (const FFTDeconOperator &parent)
Copy constructor.
~FFTDeconOperator ()
Release allocated GSL FFT work objects.
FFTDeconOperator & operator= (const FFTDeconOperator &parent)
Assign FFT size and lag shift from another operator.
void changeparameter (const mspass::utility::Metadata &md)
Reconfigure the FFT operator from Metadata.
void change_size (const int nfft_new)
Change the FFT work-buffer length.
void change_shift (const int shift)
Set the sample offset used to unwrap deconvolution lag windows.
int get_size ()
Return the current FFT work-buffer length.
int get_shift ()
Return the current deconvolution lag-window sample shift.
int operator_size ()
Return the current FFT work-buffer length.
int operator_shift ()
Return the current deconvolution lag-window sample shift.
double df (const double dt)
Return frequency spacing for the current FFT length.
mspass::seismic::CoreTimeSeries FourierInverse (const ComplexArray &winv, const ComplexArray &sw, const double dt, const double t0parent)
Return inverse wavelet for Fourier methods.
Additional Inherited Members
Protected Attributes inherited from mspass::algorithms::deconvolution::FFTDeconOperator
int nfft
Current FFT work-buffer length in samples.
int sample_shift
Sample offset used to place zero lag in deconvolution outputs.
gsl_fft_complex_wavetable * wavetable
GSL factorization table allocated for nfft.
gsl_fft_complex_workspace * workspace
GSL scratch workspace allocated for nfft.
ComplexArray winv
Frequency-domain inverse wavelet coefficients for derived operators.
Detailed Description
Colored-noise regularized three-component deconvolution engine.
This operator builds frequency-domain inverse filters using either generalized water-level or colored-noise damping regularization and applies them to three-component data.
Constructor & Destructor Documentation
CNRDeconEngine() [1/3]
mspass::algorithms::deconvolution::CNRDeconEngine::CNRDeconEngine ()
Default constructor.
                               : FFTDeconOperator() {
  /* This constructor does not initialize everything.  It initializes
  only the simple types and the values are not necessarily reasonable. */
  algorithm = CNR3C_algorithms::colored_noise_damping;
  damp = 1.0;
  noise_floor = 1.5;
  band_snr_floor = 1.5;
  shaping_wavelet_number_poles = 3;
  snr_regularization_floor = 2.0;
  /* These are computed private variables - we initialize them all to 0*/
  regularization_bandwidth_fraction = 0.0;
  for (auto i = 0; i < 3; ++i) {
    peak_snr[i] = 0.0;
    signal_bandwidth_fraction[i] = 0.0;
  }
}
CNRDeconEngine() [2/3]
mspass::algorithms::deconvolution::CNRDeconEngine::CNRDeconEngine (const mspass::utility::AntelopePf & pf)
Construct from AntelopePf container.
This is currently the only valid constructor for this object. The operator requires a fair number of parameters for construction that include secondary groups of parameters in a hierarchy. An AntelopePf is one way to handle that with a human readable form. An alternative is yaml but that is not currently supported as an external format. The AntelopePf object API is a generic way to handle parameter data hierarchies that is in MsPASS. Most user's will interact with the object only indirectly via python wrappers. All a user needs to do is define all the required key-value pairs and get the obscure pf format correct. To use this constructor one passes an instance of the object of type AntelopePf that is normally constructed by reading a text file with the "pf" format or retrieved from another AntelopePf with the get_branch method.
    : FFTDeconOperator(dynamic_cast<const Metadata &>(pf)) {
  try {
    string stmp;
    stmp = pf.get_string("algorithm");
    if (stmp == "generalized_water_level") {
      this->algorithm = CNR3C_algorithms::generalized_water_level;
    } else if (stmp == "colored_noise_damping") {
      this->algorithm = CNR3C_algorithms::colored_noise_damping;
    } else {
      throw MsPASSError("CNRDeconEngine(constructor):  invalid value for "
                        "parameter algorithm=" +
                            stmp,
                        ErrorSeverity::Fatal);
    }
    this->damp = GetDoubleRequired(pf, "damping_factor");
    if (this->damp <= 0.0) {
      throw MsPASSError("CNRDeconEngine(constructor): damping_factor must be "
                        "positive for stable regularized deconvolution",
                        ErrorSeverity::Fatal);
    }
    /* Note this paramter is used for both the damping method and the
    generalized_water_level */
    this->noise_floor = GetDoubleRequired(pf, "noise_floor");
    this->snr_regularization_floor =
        GetDoubleRequired(pf, "snr_regularization_floor");
    this->band_snr_floor = GetDoubleRequired(pf, "snr_data_bandwidth_floor");
    this->operator_dt = GetDoubleRequired(pf, "target_sample_interval");
    if (this->operator_dt <= 0.0)
      throw MsPASSError("CNRDeconEngine(constructor): "
                        "target_sample_interval must be positive",
                        ErrorSeverity::Fatal);
    /* These parameters are not cached to the object directly but
    are used to initialize the multitaper engines.   A window is used
    instead of number of samples as it is less error prone to a user than
    requiring them to compute the number from the sample interval. */
    double ts, te;
    ts = GetDoubleRequired(pf, "deconvolution_data_window_start");
    te = GetDoubleRequired(pf, "deconvolution_data_window_end");
    ValidateWindowDuration(TimeWindow(ts, te), "deconvolution_data_window",
                           "CNRDeconEngine(constructor)");
    this->winlength = round((te - ts) / this->operator_dt) + 1;
    /* In this algorithm we are very careful to avoid circular convolution
    artifacts that I (glp) suspect may be a problem in some frequency domain
    implementations of rf deconvolution.   Here we set the length of the fft
    (nfft) to a minimum of 3 times the window size.   That allows 1 window
    of padding around both ends of the waveform being deconvolved.  Circular
    shift is used to put the result back in a rational time base. */
    int minwinsize = 3 * (this->winlength);
    /* This complicated set of tests to set nfft is needed to mesh with
     * ShapingWavelet constructor and FFTDeconOperator api constraints created
     * by use in other classes in this directory that also use these */
    int nfftneeded = nextPowerOf2(minwinsize);
    /* This compication is needed because FFTDeconOperator(pf) is called
    prior to this function and it requires operator_nfft.   We need to
    be sure it size is consistent with window size that we just computed */
    if (nfftneeded != this->get_size()) {
      FFTDeconOperator::change_size(nfftneeded);
      Metadata pfcopy(pf);
      pfcopy.put("operator_nfft", nfftneeded);
      this->shapingwavelet = ShapingWavelet(pfcopy);
    } else {
      this->shapingwavelet = ShapingWavelet(pf);
    }
    /* ShapingWavelet has more options than can be accepted in this algorithm
    so this test is needed */
    string swname = this->shapingwavelet.type();
    if (!((swname == "ricker") || (swname == "butterworth"))) {
      throw MsPASSError(
          string("CNRDeconEngine(AntelopePf constructor):  ") +
              "Cannot use shaping wavelet type=" + swname +
              "\nMust be either ricker or butterworth for this algorithm",
          ErrorSeverity::Fatal);
    }
    if (swname == "butterworth") {
      /* These MUST be consistent with FFTDeconOperator pf constructor
      names.   */
      int npoles_lo, npoles_hi;
      npoles_lo = GetIntRequired(pf, "npoles_lo");
      npoles_hi = GetIntRequired(pf, "npoles_hi");
      if (npoles_hi != npoles_lo) {
        stringstream ss;
        ss << "CNRDeconEngine(Metadata constructor):  "
           << "Butterworth filter high and low number of poles must be equal "
              "for this operator"
           << endl
           << "Found npoles_lo=" << npoles_lo << " and npoles_hi=" << npoles_hi
           << endl
           << "Edit parameter file to make those two parameters equal and rerun"
           << endl;
        throw MsPASSError(ss.str(), ErrorSeverity::Fatal);
      }
      this->shaping_wavelet_number_poles = npoles_lo;
    }
    /* As with signal we use this for initializing the noise engine
    rather than the number of points, which is all the engine cares about. */
    ts = GetDoubleRequired(pf, "noise_window_start");
    te = GetDoubleRequired(pf, "noise_window_end");
    ValidateWindowDuration(TimeWindow(ts, te), "noise_window",
                           "CNRDeconEngine(constructor)");
    int noise_winlength = round((te - ts) / operator_dt) + 1;
    double tbp = GetDoubleRequired(pf, "time_bandwidth_product");
    long ntapers = GetLongRequired(pf, "number_tapers");
    this->noise_engine = MTPowerSpectrumEngine(
        noise_winlength, tbp, ntapers, noise_winlength, this->operator_dt);
    this->signal_engine = MTPowerSpectrumEngine(
        this->winlength, tbp, ntapers, this->winlength, this->operator_dt);
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::change_size(), mspass::algorithms::deconvolution::FFTDeconOperator::get_size(), mspass::utility::Metadata::get_string(), mspass::utility::Metadata::put(), and mspass::algorithms::deconvolution::ShapingWavelet::type().
CNRDeconEngine() [3/3]
mspass::algorithms::deconvolution::CNRDeconEngine::CNRDeconEngine (const CNRDeconEngine & parent)
Copy constructor.
    : FFTDeconOperator(parent), shapingwavelet(parent.shapingwavelet),
      signal_engine(parent.signal_engine), noise_engine(parent.noise_engine),
      winv(parent.winv) {
  this->algorithm = parent.algorithm;
  this->damp = parent.damp;
  this->noise_floor = parent.noise_floor;
  this->band_snr_floor = parent.band_snr_floor;
  this->operator_dt = parent.operator_dt;
  this->winlength = parent.winlength;
  this->shaping_wavelet_number_poles = parent.shaping_wavelet_number_poles;
  this->snr_regularization_floor = parent.snr_regularization_floor;
  this->regularization_bandwidth_fraction =
      parent.regularization_bandwidth_fraction;
  for (int i = 0; i < 3; ++i) {
    this->peak_snr[i] = parent.peak_snr[i];
    this->signal_bandwidth_fraction[i] = parent.signal_bandwidth_fraction[i];
  }
  winv_t0_lag = parent.winv_t0_lag;
}
~CNRDeconEngine()
virtual mspass::algorithms::deconvolution::CNRDeconEngine::~CNRDeconEngine () inline virtual
Virtual destructor.
{};
Member Function Documentation
actual_output()
TimeSeries mspass::algorithms::deconvolution::CNRDeconEngine::actual_output (const mspass::seismic::TimeSeries & wavelet)
Return the actual output generated by applying inverse and wavelet.
{
  if (wavelet.dead()) {
    TimeSeries badout(wavelet);
    badout.kill();
    badout.set_npts(0);
    badout.elog.log_error(
        "CRFDeconEngine::actual_output",
        "received wavelet data via arg0 marked dead - cannot procede",
        ErrorSeverity::Invalid);
    return badout;
  }
  TimeSeries result(
      wavelet); // Use this to clone metadata and elog from wavelet
  result.set_npts(FFTDeconOperator::nfft);
  /* Force these even though they are likely already defined as
  in the parent wavelet TimeSeries. */
  result.set_live();
  /* We always shift this wavelet to the center of the data vector.
  We handle the time through the CoreTimeSeries object. */
  int i0 = FFTDeconOperator::nfft / 2;
  result.set_t0(operator_dt * (-(double)i0));
  result.set_dt(this->operator_dt);
  result.set_tref(TimeReferenceType::Relative);
  /* We need to require that wavelet time range is consistent with
   * operator.   We assume relative time so we demand wavelet t0 be less
   * than or equal to nff2/2 to assure a wavelet signal is in the
   * the range -nfft/2 to nff2/2.  */
  int w_t0_lag;
  w_t0_lag = wavelet.sample_number(0.0);
  /* We correct the relative phase of the input wavelet to that
  saved when winv was created. */
  w_t0_lag -= this->winv_t0_lag;
  /* note we handle two extremes differently*/
  if (w_t0_lag >= FFTDeconOperator::nfft) {
    stringstream ss;
    ss << "actual_output method received wavelet with t0=" << wavelet.t0()
       << " that resolves to offset of " << w_t0_lag << " samples" << endl
       << "That exceeds buffer for frequency domain calculation of size="
       << FFTDeconOperator::nfft << endl
       << "Cannot compute actual_output because we assume signal is in range "
          "t>0"
       << endl;
    result.elog.log_error("CNRDeconEngine::actual_output", ss.str(),
                          ErrorSeverity::Invalid);
    result.kill();
    result.set_npts(0);
    return result;
  } else if (w_t0_lag > (FFTDeconOperator::nfft) / 2) {
    stringstream ss;
    ss << "Warning: actual output method received wavelet with t0="
       << wavelet.t0() << " that resolves to offset of " << w_t0_lag
       << " samples" << endl
       << "That exceeds the midpoint of the frequency domain buffer used by "
          "this method="
       << FFTDeconOperator::nfft / 2 << endl
       << "Result may be incorrect as the function assumes the signal is after "
          "time 0"
       << endl;
    result.elog.log_error("CNRDeconEngine::actual_output", ss.str(),
                          ErrorSeverity::Complaint);
  }
  try {
    std::vector<double> work;
    if (wavelet.npts() == FFTDeconOperator::nfft) {
      work = wavelet.s;
    } else {
      work.reserve(FFTDeconOperator::nfft);
      int i, nend;
      for (i = 0; i < FFTDeconOperator::nfft; ++i)
        work.push_back(0.0);
      if (wavelet.npts() > FFTDeconOperator::nfft)
        nend = FFTDeconOperator::nfft;
      else
        nend = wavelet.npts();
      for (i = 0; i < nend; ++i)
        work[i] = wavelet.s[i];
    }
    /* This converts wavelet to zero phase - needed to preserve timing.*/
    work = circular_shift(work, w_t0_lag);
    ComplexArray W(FFTDeconOperator::nfft, &(work[0]));
    gsl_fft_complex_forward(W.ptr(), 1, FFTDeconOperator::nfft, wavetable,
                            workspace);
    ComplexArray ao_fft;
    ao_fft = this->winv * W;
    ComplexArray *stmp = this->shapingwavelet.wavelet();
    /* We always apply the shaping wavelet - this perhaps should be optional
    but probably better done with a none option for the shaping wavelet */
    ao_fft = (*stmp) * ao_fft;
    gsl_fft_complex_inverse(ao_fft.ptr(), 1, FFTDeconOperator::nfft, wavetable,
                            workspace);
    vector<double> ao;
    ao.reserve(FFTDeconOperator::nfft);
    for (int k = 0; k < ao_fft.size(); ++k)
      ao.push_back(ao_fft[k].real());
    ao = circular_shift(ao, i0);
    ao = normalize<double>(ao);
    /* set_npts always initializes the s buffer so it is more efficient to
    copy ao elements rather than what was here before:
      result.s=ao;
    */
    for (int k = 0; k < FFTDeconOperator::nfft; ++k)
      result.s[k] = ao[k];
    return result;
  } catch (...) {
    throw;
  };
}
References mspass::seismic::BasicTimeSeries::dead(), mspass::utility::ProcessingHistory::elog, mspass::seismic::BasicTimeSeries::kill(), mspass::utility::ErrorLogger::log_error(), mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::seismic::BasicTimeSeries::npts(), mspass::algorithms::deconvolution::ComplexArray::ptr(), mspass::seismic::CoreTimeSeries::s, mspass::seismic::BasicTimeSeries::sample_number(), mspass::seismic::CoreTimeSeries::set_dt(), mspass::seismic::BasicTimeSeries::set_live(), mspass::seismic::CoreTimeSeries::set_npts(), mspass::seismic::CoreTimeSeries::set_t0(), mspass::seismic::BasicTimeSeries::set_tref(), mspass::algorithms::deconvolution::ComplexArray::size(), mspass::seismic::BasicTimeSeries::t0(), mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), mspass::algorithms::deconvolution::FFTDeconOperator::wavetable, and mspass::algorithms::deconvolution::FFTDeconOperator::workspace.
changeparameter()
void mspass::algorithms::deconvolution::CNRDeconEngine::changeparameter (const mspass::utility::Metadata & md)
Update operator parameters from Metadata.
{
  try {
    string stmp(md.get_string("algorithm"));
    if (stmp == "generalized_water_level") {
      this->algorithm = CNR3C_algorithms::generalized_water_level;
    } else if (stmp == "colored_noise_damping") {
      this->algorithm = CNR3C_algorithms::colored_noise_damping;
    } else {
      throw MsPASSError("CNRDeconEngine::changeparameter: invalid value for "
                        "parameter algorithm=" +
                            stmp,
                        ErrorSeverity::Fatal);
    }
    this->damp = GetDoubleRequired(md, "damping_factor");
    if (this->damp <= 0.0)
      throw MsPASSError("CNRDeconEngine::changeparameter: damping_factor must "
                        "be positive for stable regularized deconvolution",
                        ErrorSeverity::Fatal);
    this->noise_floor = GetDoubleRequired(md, "noise_floor");
    this->snr_regularization_floor =
        GetDoubleRequired(md, "snr_regularization_floor");
    this->band_snr_floor = GetDoubleRequired(md, "snr_data_bandwidth_floor");
    this->operator_dt = GetDoubleRequired(md, "target_sample_interval");
    if (this->operator_dt <= 0.0)
      throw MsPASSError("CNRDeconEngine::changeparameter: "
                        "target_sample_interval must be positive",
                        ErrorSeverity::Fatal);
    double ts(GetDoubleRequired(md, "deconvolution_data_window_start"));
    double te(GetDoubleRequired(md, "deconvolution_data_window_end"));
    ValidateWindowDuration(TimeWindow(ts, te), "deconvolution_data_window",
                           "CNRDeconEngine::changeparameter");
    this->winlength = round((te - ts) / this->operator_dt) + 1;
    int nfftneeded = nextPowerOf2(3 * this->winlength);
    if (nfftneeded != this->get_size())
      FFTDeconOperator::change_size(nfftneeded);
    this->change_shift(ComputeDeconSampleShift(md));
    if (this->get_shift() < 0 || this->get_shift() > this->get_size())
      throw MsPASSError("CNRDeconEngine::changeparameter: computed sample "
                        "shift is inconsistent with FFT length",
                        ErrorSeverity::Fatal);
    Metadata mdcopy(md);
    mdcopy.put("operator_nfft", nfftneeded);
    this->shapingwavelet = ShapingWavelet(mdcopy);
    string swname(this->shapingwavelet.type());
    if (!((swname == "ricker") || (swname == "butterworth"))) {
      throw MsPASSError(
          string("CNRDeconEngine::changeparameter: ") +
              "Cannot use shaping wavelet type=" + swname +
              "\nMust be either ricker or butterworth for this algorithm",
          ErrorSeverity::Fatal);
    }
    if (swname == "butterworth") {
      int npoles_lo(GetIntRequired(md, "npoles_lo"));
      int npoles_hi(GetIntRequired(md, "npoles_hi"));
      if (npoles_hi != npoles_lo) {
        stringstream ss;
        ss << "CNRDeconEngine::changeparameter: Butterworth filter high and "
              "low number of poles must be equal"
           << endl
           << "Found npoles_lo=" << npoles_lo << " and npoles_hi=" << npoles_hi
           << endl;
        throw MsPASSError(ss.str(), ErrorSeverity::Fatal);
      }
      this->shaping_wavelet_number_poles = npoles_lo;
    }
    ts = GetDoubleRequired(md, "noise_window_start");
    te = GetDoubleRequired(md, "noise_window_end");
    ValidateWindowDuration(TimeWindow(ts, te), "noise_window",
                           "CNRDeconEngine::changeparameter");
    int noise_winlength = round((te - ts) / operator_dt) + 1;
    double tbp = GetDoubleRequired(md, "time_bandwidth_product");
    long ntapers = GetLongRequired(md, "number_tapers");
    this->noise_engine = MTPowerSpectrumEngine(
        noise_winlength, tbp, ntapers, noise_winlength, this->operator_dt);
    this->signal_engine = MTPowerSpectrumEngine(
        this->winlength, tbp, ntapers, this->winlength, this->operator_dt);
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::change_shift(), mspass::algorithms::deconvolution::FFTDeconOperator::change_size(), mspass::algorithms::deconvolution::FFTDeconOperator::get_shift(), mspass::algorithms::deconvolution::FFTDeconOperator::get_size(), mspass::utility::Metadata::get_string(), mspass::utility::Metadata::put(), and mspass::algorithms::deconvolution::ShapingWavelet::type().
compute_noise_spectrum() [1/2]
PowerSpectrum mspass::algorithms::deconvolution::CNRDeconEngine::compute_noise_spectrum (const mspass::seismic::Seismogram & d2use)
Compute noise spectrum from three component data.
Overloaded version returns average power spectrum of all three components. Measure of overall 3c power comparable to scalar signal power. Could do sum of component spectra but that would cause a scaling problem for use in regularization. For most data this will tend to be dominated by the component with the highest noise level
{
  if (n.dead()) {
    PowerSpectrum badout;
    badout.elog.log_error("CNRDeconEngine:compute_noise",
                          "Received noise data segment marked dead",
                          ErrorSeverity::Invalid);
    return badout;
  }
  try {
    PowerSpectrum avg3c;
    TimeSeries tswork;
    if (n.npts() != noise_engine.taper_length()) {
      /* this may change fft size and will set dt wrong so we need the
       * call to set_df afterward to correct that. */
      noise_engine =
          MTPowerSpectrumEngine(n.npts(), noise_engine.time_bandwidth_product(),
                                noise_engine.number_tapers());
      noise_engine.set_df(this->operator_dt);
    }
    for (int k = 0; k < 3; ++k) {
      tswork = TimeSeries(ExtractComponent(n, k), "Invalid");
      PowerSpectrum psnoise = this->noise_engine.apply(tswork);
      if (psnoise.dead()) {
        return psnoise;
      }
      if (k == 0)
        avg3c = psnoise;
      else
        avg3c += psnoise;
    }
    /* We define total power as the average on all three
    components */
    double scl = 1.0 / 3.0;
    for (int i = 0; i < avg3c.nf(); ++i)
      avg3c.spectrum[i] *= scl;
    return avg3c;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::MTPowerSpectrumEngine::apply(), mspass::seismic::BasicSpectrum::dead(), mspass::seismic::BasicTimeSeries::dead(), mspass::seismic::PowerSpectrum::elog, mspass::utility::ErrorLogger::log_error(), mspass::seismic::PowerSpectrum::nf(), mspass::seismic::BasicTimeSeries::npts(), mspass::algorithms::deconvolution::MTPowerSpectrumEngine::number_tapers(), mspass::algorithms::deconvolution::MTPowerSpectrumEngine::set_df(), mspass::seismic::PowerSpectrum::spectrum, mspass::algorithms::deconvolution::MTPowerSpectrumEngine::taper_length(), and mspass::algorithms::deconvolution::MTPowerSpectrumEngine::time_bandwidth_product().
compute_noise_spectrum() [2/2]
PowerSpectrum mspass::algorithms::deconvolution::CNRDeconEngine::compute_noise_spectrum (const mspass::seismic::TimeSeries & d2use)
Compute noise spectrum using internal Multitaper operator. Normally used for noise spectrum but can be used for signal. Necessary to assure consistent scaling between signal and noise spectrum estimators.
{
  if (n.dead()) {
    PowerSpectrum badout;
    badout.elog.log_error("CNRDeconEngine:compute_noise",
                          "Received noise data segment marked dead",
                          ErrorSeverity::Invalid);
    return badout;
  }
  try {
    if (n.npts() != noise_engine.taper_length()) {
      /* use this varaint of the construtor too allow the fft size to
       * be automatically changed if necessary.  */
      this->noise_engine =
          MTPowerSpectrumEngine(n.npts(), noise_engine.time_bandwidth_product(),
                                noise_engine.number_tapers());
      /* with auto fft we also need this to set the df and dt correctly */
      this->noise_engine.set_df(this->operator_dt);
    }
    return this->noise_engine.apply(n);
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::MTPowerSpectrumEngine::apply(), mspass::seismic::BasicTimeSeries::dead(), mspass::seismic::PowerSpectrum::elog, mspass::utility::ErrorLogger::log_error(), mspass::seismic::BasicTimeSeries::npts(), mspass::algorithms::deconvolution::MTPowerSpectrumEngine::number_tapers(), mspass::algorithms::deconvolution::MTPowerSpectrumEngine::set_df(), mspass::algorithms::deconvolution::MTPowerSpectrumEngine::taper_length(), and mspass::algorithms::deconvolution::MTPowerSpectrumEngine::time_bandwidth_product().
get_operator_dt()
double mspass::algorithms::deconvolution::CNRDeconEngine::get_operator_dt () const inline
Return the sample interval required by the current operator.
{ return this->operator_dt; }
ideal_output()
TimeSeries mspass::algorithms::deconvolution::CNRDeconEngine::ideal_output ()
Return the ideal output shaping wavelet.
{
  try {
    CoreTimeSeries ideal_tmp = this->shapingwavelet.impulse_response();
    return TimeSeries(ideal_tmp, "Invalid");
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::ShapingWavelet::impulse_response().
initialize_inverse_operator() [1/2]
void mspass::algorithms::deconvolution::CNRDeconEngine::initialize_inverse_operator (const mspass::seismic::TimeSeries & wavelet, const mspass::seismic::PowerSpectrum & noise_spectrum)
Initialize the inverse operator from a signal and precomputed noise spectrum.
{
  string alg("CNRDeconEngine::initialize_inverse_operator");
  if (wavelet.dead()) {
    string message;
    message = alg + string("Received wavelet signal marked dead");
    throw MsPASSError(message, ErrorSeverity::Invalid);
  }
  if (noise_spectrum.dead()) {
    string message;
    message = alg + string("Received a PowerSpectrum object marked dead");
    throw MsPASSError(message, ErrorSeverity::Invalid);
  }
  try {
    this->compute_winv(wavelet, noise_spectrum);
  } catch (...) {
    throw;
  };
}
References mspass::seismic::BasicSpectrum::dead(), and mspass::seismic::BasicTimeSeries::dead().
initialize_inverse_operator() [2/2]
void mspass::algorithms::deconvolution::CNRDeconEngine::initialize_inverse_operator (const mspass::seismic::TimeSeries & wavelet, const mspass::seismic::TimeSeries & noise_data)
Initialize the inverse operator from signal and noise time series.
{
  const string alg("CNRDeconEngine::initialize_inverse_operator");
  if (wavelet.dead() || noise_data.dead()) {
    string message;
    message = alg + string(":  Received TimeSeries inputs marked dead\n");
    if (wavelet.dead())
      message += "wavelet signal input was marked dead\n";
    if (noise_data.dead())
      message += "noise data segment was marked dead\n";
    throw MsPASSError(message, ErrorSeverity::Invalid);
  }
  try {
    /* Assume wavelet and noise_data have the correct sample rate.
     * python wrapper should guarantee that */
    PowerSpectrum psnoise(this->compute_noise_spectrum(noise_data));
    if (psnoise.dead()) {
      string message;
      message = alg + string("compute_noise_spectrum method failed - cannot "
                             "compute inverse opeator");
      throw MsPASSError(message, ErrorSeverity::Invalid);
    }
    this->initialize_inverse_operator(wavelet, psnoise);
  } catch (...) {
    throw;
  };
}
References compute_noise_spectrum(), mspass::seismic::BasicSpectrum::dead(), mspass::seismic::BasicTimeSeries::dead(), and initialize_inverse_operator().
inverse_wavelet()
TimeSeries mspass::algorithms::deconvolution::CNRDeconEngine::inverse_wavelet (const mspass::seismic::TimeSeries & wavelet, const double t0shift)
Return the inverse wavelet for a supplied input wavelet.
{
  try {
    /* Using the time shift of wavelet.t0() may be a bad idea here.  Will
    need to sort that out in debugging behaviour*/
    double timeshift(tshift0);
    timeshift += wavelet.t0();
    timeshift -= operator_dt * ((double)this->winlength);
    CoreTimeSeries invcore(this->FFTDeconOperator::FourierInverse(
        this->winv, *this->shapingwavelet.wavelet(), operator_dt, timeshift));
    TimeSeries result(invcore, "Invalid");
    /* Copy the error log from wavelet and post some information parameters
    to metadata */
    result.elog = wavelet.elog;
    result.put("waveform_type", "deconvolution_inverse_wavelet");
    result.put("decon_type", "CNRDeconEngine");
    return result;
  } catch (...) {
    throw;
  };
}
References mspass::utility::ProcessingHistory::elog, mspass::algorithms::deconvolution::FFTDeconOperator::FourierInverse(), mspass::utility::Metadata::put(), mspass::seismic::BasicTimeSeries::t0(), and mspass::algorithms::deconvolution::ShapingWavelet::wavelet().
operator=()
CNRDeconEngine & mspass::algorithms::deconvolution::CNRDeconEngine::operator= (const CNRDeconEngine & parent)
Assignment operator.
{
  if (&parent != this) {
    this->shapingwavelet = parent.shapingwavelet;
    this->signal_engine = parent.signal_engine;
    this->noise_engine = parent.noise_engine;
    this->winv = parent.winv;
    this->winv_t0_lag = parent.winv_t0_lag;
    this->algorithm = parent.algorithm;
    this->damp = parent.damp;
    this->noise_floor = parent.noise_floor;
    this->band_snr_floor = parent.band_snr_floor;
    this->operator_dt = parent.operator_dt;
    this->shaping_wavelet_number_poles = parent.shaping_wavelet_number_poles;
    this->snr_regularization_floor = parent.snr_regularization_floor;
    this->regularization_bandwidth_fraction =
        parent.regularization_bandwidth_fraction;
    for (int i = 0; i < 3; ++i) {
      this->peak_snr[i] = parent.peak_snr[i];
      this->signal_bandwidth_fraction[i] = parent.signal_bandwidth_fraction[i];
    }
  }
  return *this;
}
output_shaping_wavelet()
mspass::seismic::TimeSeries mspass::algorithms::deconvolution::CNRDeconEngine::output_shaping_wavelet () inline
Return the output shaping wavelet.
This is the wavelet used as the target finite-bandwidth representation of the deconvolved result. The historical method name ideal_output is retained as a legacy alias.
{
    return this->ideal_output();
  }
References ideal_output().
process()
Seismogram mspass::algorithms::deconvolution::CNRDeconEngine::process (const mspass::seismic::Seismogram & d, const mspass::seismic::PowerSpectrum & psnoise, const double fl, const double fh)
Apply the deconvolution operator to a three-component datum.
{
  const string alg("CNRDeconEngine::process");
  if (d.dead() || psnoise.dead()) {
    Seismogram dout(d);
    dout.set_npts(0);
    if (d.dead()) {
      dout.elog.log_error(
          alg, "received Seismogram input segment marked dead - cannot process",
          ErrorSeverity::Invalid);
    }
    if (psnoise.dead()) {
      dout.elog.log_error(
          alg, "received PowerSpectrum object marked dead - cannot process",
          ErrorSeverity::Invalid);
    }
    dout.kill();
    return dout;
  }
  try {
    string base_error("CNRDeconEngine::process:  ");
    this->update_shaping_wavelet(fl, fh);
    Seismogram rfest(d);
    /* This is used to apply a shift to the fft outputs to put signals
    at relative time 0 */
    int t0_shift;
    t0_shift = round((-rfest.t0()) / rfest.dt());
    vector<double> wvec;
    wvec.reserve(FFTDeconOperator::nfft);
    /* The set_npts method is assumed to not only set that attribute
     * but initialize the u matrix to a 3xnfft matrix.*/
    if (rfest.npts() != FFTDeconOperator::nfft)
      rfest.set_npts(FFTDeconOperator::nfft);
    int nhighsnr;
    double df;
    df = 1.0 / (operator_dt * static_cast<double>(FFTDeconOperator::nfft));
    for (int k = 0; k < 3; ++k) {
      TimeSeries work;
      work = TimeSeries(ExtractComponent(d, k), "Invalid");
      wvec.clear();
      int ntocopy = FFTDeconOperator::nfft;
      if (ntocopy > work.npts())
        ntocopy = work.npts();
      for (int j = 0; j < ntocopy; ++j)
        wvec.push_back(work.s[j]);
      for (int j = ntocopy; j < FFTDeconOperator::nfft; ++j)
        wvec.push_back(0.0);
      ComplexArray numerator(FFTDeconOperator::nfft, &(wvec[0]));
      gsl_fft_complex_forward(numerator.ptr(), 1, FFTDeconOperator::nfft,
                              wavetable, workspace);
      /* This loop computes QCMetrics of bandwidth fraction that
      is above a defined snr floor - not necessarily the same as the
      regularization floor used in computing the inverse */
      double snrmax;
      snrmax = 1.0;
      nhighsnr = 0;
      for (int j = 0; j < FFTDeconOperator::nfft / 2; ++j) {
        double f;
        f = df * static_cast<double>(j);
        Complex64 z = numerator[j];
        double sigamp = abs(z);
        double namp = sqrt(psnoise.power(f));
        double snr = sigamp / namp;
        if (snr > snrmax)
          snrmax = snr;
        if (snr > this->band_snr_floor)
          ++nhighsnr;
      }
      signal_bandwidth_fraction[k] =
          static_cast<double>(nhighsnr) /
          static_cast<double>(FFTDeconOperator::nfft / 2);
      peak_snr[k] = snrmax;
      ComplexArray rftmp = numerator * winv;
      rftmp = (*this->shapingwavelet.wavelet()) * rftmp;
      gsl_fft_complex_inverse(rftmp.ptr(), 1, FFTDeconOperator::nfft, wavetable,
                              workspace);
      wvec.clear();
      for (int j = 0; j < FFTDeconOperator::nfft; ++j)
        wvec.push_back(rftmp[j].real());
      /* Note we used a time domain shift instead of using a linear phase
      shift in the frequency domain because the time domain operator has a lower
      operation count than the frequency domain algorithm and is thus more
      efficient.*/
      if (t0_shift != 0)
        wvec = circular_shift(wvec, -t0_shift);
      for (int j = 0; j < FFTDeconOperator::nfft; ++j)
        rfest.u(k, j) = wvec[j];
    }
    return rfest;
  } catch (...) {
    throw;
  };
}
References mspass::seismic::BasicSpectrum::dead(), mspass::seismic::BasicTimeSeries::dead(), mspass::algorithms::deconvolution::FFTDeconOperator::df(), mspass::seismic::BasicTimeSeries::dt(), mspass::utility::ProcessingHistory::elog, mspass::seismic::BasicTimeSeries::kill(), mspass::utility::ErrorLogger::log_error(), mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::seismic::BasicTimeSeries::npts(), mspass::seismic::PowerSpectrum::power(), mspass::algorithms::deconvolution::ComplexArray::ptr(), mspass::seismic::CoreTimeSeries::s, mspass::seismic::CoreSeismogram::set_npts(), mspass::seismic::BasicTimeSeries::t0(), mspass::seismic::CoreSeismogram::u, mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), mspass::algorithms::deconvolution::FFTDeconOperator::wavetable, and mspass::algorithms::deconvolution::FFTDeconOperator::workspace.
QCMetrics()
Metadata mspass::algorithms::deconvolution::CNRDeconEngine::QCMetrics ()
Return quality-control metrics from the most recent processing.
{
  Metadata result;
  result.put("decon_operator", string("CNRDeconEngine"));
  result.put("decon_processed", this->regularization_bandwidth_fraction > 0.0);
  result.put("decon_operator_nfft", nfft);
  result.put("decon_operator_sample_shift", sample_shift);
  result.put("decon_sample_interval", operator_dt);
  result.put("cnr_regularization_bandwidth_fraction",
             this->regularization_bandwidth_fraction);
  result.put("waveletbf", this->regularization_bandwidth_fraction);
  result.put("maxsnr0", peak_snr[0]);
  result.put("maxsnr1", peak_snr[1]);
  result.put("maxsnr2", peak_snr[2]);
  result.put("signalbf0", signal_bandwidth_fraction[0]);
  result.put("signalbf1", signal_bandwidth_fraction[1]);
  result.put("signalbf2", signal_bandwidth_fraction[2]);
  return result;
}
References mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::utility::Metadata::put(), and mspass::algorithms::deconvolution::FFTDeconOperator::sample_shift.
resolution_kernel()
mspass::seismic::TimeSeries mspass::algorithms::deconvolution::CNRDeconEngine::resolution_kernel (const mspass::seismic::TimeSeries & wavelet) inline
Alias for actual_output using inverse-theory terminology.
{
    return this->actual_output(wavelet);
  }
References actual_output().
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/cxx/include/mspass/algorithms/deconvolution/CNRDeconEngine.h
/home/runner/work/mspass/mspass/cxx/src/lib/algorithms/deconvolution/CNRDeconEngine.cc