MsPASS C++ API: mspass::algorithms::deconvolution::GeneralIterDecon Class Reference
mspass::algorithms::deconvolution::GeneralIterDecon Class Reference
Implements the Generalized Iterative Method of Wang and Pavlis.
#include <GeneralIterDecon.h>
Public Member Functions
GeneralIterDecon (mspass::utility::AntelopePf &md)
Create an initialize an operator for subseqquent processing.
GeneralIterDecon (const GeneralIterDecon &parent)
void changeparameter (const mspass::utility::Metadata &md)
int load (const mspass::seismic::CoreSeismogram &d, mspass::algorithms::TimeWindow dwin)
int loadnoise (const mspass::seismic::CoreSeismogram &d, mspass::algorithms::TimeWindow nwin)
int load (const mspass::seismic::CoreSeismogram &d, mspass::algorithms::TimeWindow dwin, mspass::algorithms::TimeWindow nwin)
Load all needed data and process.
void process ()
mspass::seismic::CoreSeismogram getresult ()
mspass::seismic::CoreTimeSeries ideal_output ()
mspass::seismic::CoreTimeSeries actual_output ()
Return the actual output of the deconvolution operator.
mspass::seismic::CoreTimeSeries inverse_wavelet ()
Return a FIR represention of the inverse filter.
mspass::seismic::CoreTimeSeries inverse_wavelet (double t0parent)
mspass::utility::Metadata QCMetrics ()
Return appropriate quality measures.
Public Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
ScalarDecon (const mspass::utility::Metadata &md)
ScalarDecon (const std::vector< double > &d, const std::vector< double > &w)
ScalarDecon (const ScalarDecon &parent)
int load (const std::vector< double > &wavelet, const std::vector< double > &data)
Load all data required for decon.
int loaddata (const std::vector< double > &data)
int loadwavelet (const std::vector< double > &wavelet)
ScalarDecon & operator= (const ScalarDecon &parent)
std::vector< double > getresult ()
void changeparameter (const mspass::utility::Metadata &md)
void change_shaping_wavelet (const ShapingWavelet &nsw)
ShapingWavelet get_shaping_wavelet () const
mspass::seismic::CoreTimeSeries ideal_output ()
Additional Inherited Members
Protected Attributes inherited from mspass::algorithms::deconvolution::ScalarDecon
std::vector< double > data
std::vector< double > wavelet
std::vector< double > result
ShapingWavelet shapingwavelet
Detailed Description
Implements the Generalized Iterative Method of Wang and Pavlis.
This class is an extension of the idea o the generalized iterative method described in the paper by Wang and Pavlis. Their original paper worked on scalar seismograms. This implemenation differs by iterating on the vector data effectively reducing a 3c seismogram to a sequence of 3D vectors at computed lags. The iterative reduction then iterates on the data matrix. In addition, Wang's original implementation did the iteration by repeated forward and inverse fourier transforms. This algorithm works completely in the time domain.
The class retains a concept Wang used in the original implementation. Many OOP books stress the idea of construction is initialization. That is not pruddent fo this case since construction involves some work that we do not want to repeat for each new seismogram. Hence, construction only initializes parameters required to run the algorithm. Calculation is triggered by calling one of the two overloaded load methods. The user should be warned, however, that we did not build ina test to assure the noise and signal windows are consistent. Anyone wanting to use this code outside of applications developed by the authors must recognize That the assure consistency they need to call loadnoise before load OR call only the load method that includes a signal and noise window.
Constructor & Destructor Documentation
GeneralIterDecon()
mspass::algorithms::deconvolution::GeneralIterDecon::GeneralIterDecon (mspass::utility::AntelopePf & md)
Create an initialize an operator for subseqquent processing.
This is the primary constructor for this object. The PfStyleMetadata object is expected to contain a suite of parameters used to define how this operator will behave along with what inverse filter is to be constructed ans applied before the iterative algorithm is applied. The pf is required to have multiple Arr sections the components.
                                                         : ScalarDecon() {
  const string base_error("GeneralIterDecon AntelopePf contructor:  ");
  stringstream ss; // used for constructing error messages
  /* The pf used for initializing this object has Antelope Arr section
  for each algorithm.   Since the generalized iterative method is a
  two-stage algorithm we have a section for the iterative algorithm
  and a (variable) sectin for the preprocessor algorithm.  We use
  the AntelopePf to parse this instead of raw antelope pfget
  C calls. */
  try {
    AntelopePf md = mdtoplevel.get_branch("deconvolution_operator_type");
    AntelopePf mdgiter = md.get_branch("generalized_iterative_deconvolution");
    IterDeconType dct = parse_for_itertype(mdgiter);
    this->decon_type = dct;
    double ts, te;
    ts = mdgiter.get<double>("full_data_window_start");
    te = mdgiter.get<double>("full_data_window_end");
    dwin = TimeWindow(ts, te);
    ts = mdgiter.get<double>("deconvolution_data_window_start");
    te = mdgiter.get<double>("deconvolution_data_window_end");
    fftwin = TimeWindow(ts, te);
    ts = mdgiter.get<double>("noise_window_start");
    te = mdgiter.get<double>("noise_window_end");
    nwin = TimeWindow(ts, te);
    /* We need to make sure the noise and decon windows are inside the
     * full_data_window*/
    if (fftwin.start < dwin.start || fftwin.end > dwin.end) {
      stringstream ss;
      ss << base_error << "decon window error" << endl
         << "Wavelet inversion window is not inside analysis window" << endl
         << "full_data_window (analysis) range=" << dwin.start << " to "
         << dwin.end << endl
         << "decon_window (wavelet inversion) range=" << fftwin.start << " to "
         << fftwin.end << endl;
      throw MsPASSError(ss.str(), ErrorSeverity::Invalid);
    }
    noise_component = mdgiter.get<int>("noise_component");
    double target_dt = mdgiter.get<double>("target_sample_interval");
    int maxns = static_cast<int>((fftwin.end - fftwin.start) / target_dt);
    ++maxns; // Add one - points not intervals
    nfft = nextPowerOf2(maxns);
    /* This should override this even if it was previously set */
    mdgiter.put("operator_nfft", nfft);
    this->ScalarDecon::changeparameter(mdgiter);
    shapingwavelet = ShapingWavelet(mdgiter, nfft);
    /* Note minus sign here */
    time_shift = -(dwin.start) / target_dt;
    AntelopePf mdleaf;
    /* We make sure the window parameters in each algorithm mactch what
    is set for this algorithm.  Abort if they are not consistent.  The
    test code is a bit repetitious but a necessary evil to allow the message
    to be clearer. */
    int n1, n2; // temporaries used below -  needed because declrations illegal
                // inside case
    switch (decon_type) {
    case WATER_LEVEL:
      mdleaf = md.get_branch("water_level");
      ts = mdleaf.get<double>("deconvolution_data_window_start");
      te = mdleaf.get<double>("deconvolution_data_window_end");
      if ((ts != fftwin.start) || (te != fftwin.end)) {
        ss << base_error
           << "water level method specification of processing window is not"
              " consistent with gid parameters"
           << endl
           << "water level parameters:  deconvolution_data_window_start=" << ts
           << ", decon_window_end=" << te << endl
           << "GID parameters: decon_window_start=" << fftwin.start
           << ", decon_window_end=" << fftwin.end << endl;
        throw MsPASSError(ss.str(), ErrorSeverity::Invalid);
      }
      preprocessor = new WaterLevelDecon(mdleaf);
      break;
    case LEAST_SQ:
      mdleaf = md.get_branch("least_square");
      ts = mdleaf.get<double>("deconvolution_data_window_start");
      te = mdleaf.get<double>("deconvolution_data_window_end");
      if ((ts != fftwin.start) || (te != fftwin.end)) {
        ss << base_error
           << "least square method specification of processing window is not"
              " consistent with gid parameters"
           << endl
           << "least square parameters:  deconvolution_data_window_start=" << ts
           << ", decon_window_end=" << te << endl
           << "GID parameters: decon_window_start=" << fftwin.start
           << ", decon_window_end=" << fftwin.end << endl;
        throw MsPASSError(ss.str(), ErrorSeverity::Invalid);
      }
      preprocessor = new LeastSquareDecon(mdleaf);
      break;
    case MULTI_TAPER:
    default:
      mdleaf = md.get_branch("multi_taper");
      ts = mdleaf.get<double>("deconvolution_data_window_start");
      te = mdleaf.get<double>("deconvolution_data_window_end");
      if ((ts != fftwin.start) || (te != fftwin.end)) {
        ss << base_error
           << "mulittaper method specification of processing window is not"
              " consistent with gid parameters"
           << endl
           << "multitaper parameters:  deconvolution_data_window_start=" << ts
           << ", decon_window_end=" << te << endl
           << "GID parameters: decon_window_start=" << fftwin.start
           << ", decon_window_end=" << fftwin.end << endl;
        throw MsPASSError(ss.str(), ErrorSeverity::Invalid);
      }
      /* Here we also have to test the noise parameters, but the gid
      window can be different fromt that passed to the mulittaper method.
      Hence we test only that the mulittaper noise window is within the bounds
      of the gid noise window */
      n1 = static_cast<int>((fftwin.end - fftwin.start) / target_dt) + 1;
      n2 = static_cast<int>((nwin.end - nwin.start) / target_dt) + 1;
      if (n1 > n2) {
        ss << base_error << "inconsistent noise window specification" << endl
           << "multitaper parameters specify taper length=" << n1 << " samples"
           << endl
           << "GID noise window parameters define noise_window_start="
           << nwin.start << " and noise_window_end=" << nwin.end << endl
           << "The GID window has a length of " << n2 << " samples" << endl
           << "GID implementation insists multitaper noise window be smaller "
              "or equal to GID noise window"
           << endl;
        throw MsPASSError(ss.str(), ErrorSeverity::Invalid);
      }
      preprocessor = new MultiTaperXcorDecon(mdleaf);
    };
    /* Because this may evolve we make this a private method to
    make changes easier to implement. */
    this->construct_weight_penalty_function(mdgiter);
    /* Set convergencd parameters from md keys */
    iter_max = mdgiter.get<int>("maximum_iterations");
    lw_linf_floor = mdgiter.get<double>("lag_weight_Linf_floor");
    lw_l2_floor = mdgiter.get<double>("lag_weight_rms_floor");
    resid_linf_prob =
        mdgiter.get<double>("residual_noise_rms_probability_floor");
    resid_l2_tol = mdgiter.get<double>("residual_fractional_improvement_floor");
  } catch (...) {
    throw;
  };
}
References mspass::utility::Metadata::get(), and mspass::utility::AntelopePf::get_branch().
~GeneralIterDecon()
mspass::algorithms::deconvolution::GeneralIterDecon::~GeneralIterDecon ()
{ delete preprocessor; }
Member Function Documentation
actual_output()
mspass::seismic::CoreTimeSeries mspass::algorithms::deconvolution::GeneralIterDecon::actual_output () inline virtual
Return the actual output of the deconvolution operator.
The actual output is defined as w^-1*w and is compable to resolution kernels in linear inverse theory. Although not required we would normally expect this function to be peaked at 0. Offsets from 0 would imply a bias.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
    return this->preprocessor->actual_output();
  };
References mspass::algorithms::deconvolution::ScalarDecon::actual_output().
changeparameter()
void mspass::algorithms::deconvolution::GeneralIterDecon::changeparameter (const mspass::utility::Metadata & md) inline virtual
Implements mspass::algorithms::deconvolution::BasicDeconOperator.
{
    this->preprocessor->changeparameter(md);
  };
getresult()
CoreSeismogram mspass::algorithms::deconvolution::GeneralIterDecon::getresult ()
{
  try {
    string base_error("GeneralIterDecon::getresult:  ");
    CoreSeismogram result(d_all);
    /* We will make the output the size of the processing window for the
    iteration.  May want to alter this to trim the large lag that would not
    be allowed due to wavelet duration anyway, BUT for GID method the
    wavelet should be compact enough that should be a small factor.  Hence
    for now I omit that complexity until proven to be an issue. */
    result = WindowData(result, dwin);
    result.u.zero();
    /* The spike sequences uses the time reference of the data in the
    private copy r.   This is the computed offset in samples to correct
    lags in the spikes list container to be at correct time in result */
    double dt0;
    int delta_col;
    dt0 = result.t0() - r.t0();
    delta_col = round(dt0 / r.dt());
    list<ThreeCSpike>::iterator sptr;
    int k, resultcol;
    for (sptr = spikes.begin(); sptr != spikes.end(); ++sptr) {
      if (((sptr->col) < 0) || ((sptr->col) >= result.npts()))
        throw MsPASSError(
            base_error +
                "Coding error - spike lag is outside output data range",
            ErrorSeverity::Fatal);
      resultcol = (sptr->col) - delta_col;
      for (k = 0; k < 3; ++k)
        result.u(k, resultcol) = sptr->u[k];
    }
    string wtype = this->shapingwavelet.type();
    if (wtype != "none") {
      CoreTimeSeries w(this->shapingwavelet.impulse_response());
      result = sparse_convolve(w, result);
    }
    return result;
  } catch (...) {
    throw;
  };
}
ideal_output()
mspass::seismic::CoreTimeSeries mspass::algorithms::deconvolution::GeneralIterDecon::ideal_output () inline
{
    return this->preprocessor->ideal_output();
  };
inverse_wavelet() [1/2]
mspass::seismic::CoreTimeSeries mspass::algorithms::deconvolution::GeneralIterDecon::inverse_wavelet () inline virtual
Return a FIR represention of the inverse filter.
After any deconvolution is computed one can sometimes produce a finite impulse response (FIR) respresentation of the inverse filter.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
    return this->preprocessor->inverse_wavelet();
  };
References mspass::algorithms::deconvolution::ScalarDecon::inverse_wavelet().
inverse_wavelet() [2/2]
mspass::seismic::CoreTimeSeries mspass::algorithms::deconvolution::GeneralIterDecon::inverse_wavelet (double t0parent) inline virtual
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
    return this->preprocessor->inverse_wavelet(t0parent);
  };
load() [1/2]
int mspass::algorithms::deconvolution::GeneralIterDecon::load (const mspass::seismic::CoreSeismogram & d, mspass::algorithms::TimeWindow dwin)
{
  try {
    dwin = dwin_in;
    /* First we load the requested window.  Note we MUST always make this window
    a bit larger than the range of desired lags as the iterative algorithm will
    not allow lags at the edges (defined by a construction parameter
    wavelet_pad)
    */
    d_all = WindowData(draw, dwin);
    ndwin = d_all.npts();
    return 0;
  } catch (...) {
    throw;
  };
}
load() [2/2]
int mspass::algorithms::deconvolution::GeneralIterDecon::load (const mspass::seismic::CoreSeismogram & d, mspass::algorithms::TimeWindow dwin, mspass::algorithms::TimeWindow nwin)
Load all needed data and process.
This method is little more than a call to loadnoise followed immediately by a call to load that is assumed to initiate the computation.
{
  try {
    int iretn, iret;
    iretn = this->loadnoise(draw, nwin);
    iret = this->load(draw, dwin);
    return (iretn + iret);
  } catch (...) {
    throw;
  };
}
loadnoise()
int mspass::algorithms::deconvolution::GeneralIterDecon::loadnoise (const mspass::seismic::CoreSeismogram & d, mspass::algorithms::TimeWindow nwin)
{
  try {
    nwin = nwin_in;
    n = WindowData(draw, nwin);
    nnwin = n.npts();
    double ret = this->compute_resid_linf_floor();
    if (ret > 0)
      return 0;
    else
      return 1;
  } catch (...) {
    throw;
  };
}
process()
void mspass::algorithms::deconvolution::GeneralIterDecon::process () virtual
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  const string base_error("GeneralIterDecon::process method:  ");
  try {
    /* We first have to run the signal processing style deconvolution.
    This is defined by the base pointer available through the symbol
    preprocessor.   All those altorithms require load methods to be called
    to initate the computation.  A complication is that the multitaper is
    different and requires a noise signal to also be loaded through loadnoise.
    That complicates this a bit below, but the flow of the algorithm should
    still be clear.   Outer loop is over the three components were we assemble
    a full 3c record.   Note this is the same algorithm use in trace_decon
    for anything but this iterative algorithm.
    */
    /* d_decon will hold the preprocessor output.  We normally expect to
    derive it by windowing of t_all.  We assume WindowData will be
    successful - constructor should guarantee that. */
    d_decon = WindowData(d_all, fftwin);
    dmatrix uwork(d_decon.u);
    uwork.zero();
    /* We assume loadnoise has been called previously to set put the
    right data here. We need a scalar function to pass to the multtitaper
    algorithm though. */
    if (decon_type == MULTI_TAPER) {
      CoreTimeSeries nts(ExtractComponent(n, noise_component));
      dynamic_cast<MultiTaperXcorDecon *>(preprocessor)->loadnoise(nts.s);
    }
    /* For this case of receiver function deconvolution we always get the
    wavelet from component 2 - assumed here to be Z or L. */
    CoreTimeSeries srcwavelet(ExtractComponent(d_decon, 2));
    for (int k = 0; k < 3; ++k) {
      CoreTimeSeries dcomp(ExtractComponent(d_decon, k));
      /* Need the qualifier or we get the wrong overloaded
       * load method */
      preprocessor->ScalarDecon::load(srcwavelet.s, dcomp.s);
      preprocessor->process();
      vector<double> deconout(preprocessor->getresult());
      int copysize = deconout.size();
      if (copysize > d_decon.npts())
        copysize = d_decon.npts();
      cblas_dcopy(copysize, &(deconout[0]), 1, uwork.get_address(k, 0), 3);
    }
    d_decon.u = uwork;
    /* The inverse wavelet and the actual output signals are determined in all
    current algorithms from srcwavelet.   Hence, what is now stored will work.
    If this is extended make sure that condition is satisfied.
    We extract the inverse filter and use a time domain convolution with
    data in the longer time window.   Note for efficiency may want to
    convert this to a frequency domain convolution if it proves to be
    a bottleneck */
    // double dt;
    // dt=this->shapingwavelet.sample_interval();
    // TimeSeries winv=this->preprocessor->inverse_wavelet(tshift,d_decon.t0());
    // DEBUG
    // cerr << "inverse wavelet tshift="<<tshift/5.0<<"
    // d_decon.to="<<d_decon.t0()<<endl; TimeSeries
    // winv=this->preprocessor->inverse_wavelet(tshift/5.0,d_decon.t0());
    // TimeSeries winv=this->preprocessor->inverse_wavelet(0.0,d_decon.t0());
    CoreTimeSeries winv = this->preprocessor->inverse_wavelet(d_decon.t0());
    // This is a test - need a more elegant solution if it works.  Remove me
    // when finished with this test
    // if(d_decon.t0!=0) winv.t0 -= d_decon.t0;
    // DEBUG
    /*
    cerr << "Inverse wavelet"<<endl
         << winv
         <<endl;
*/
    /* The actual output signal is used in the iterative
     * recursion of this algorithm.  For efficiency it is important
     * to trim the fir filter.  The call to trim does that.*/
    CoreTimeSeries actual_out(this->preprocessor->actual_output());
    // DEBUG
    /*
    cerr << "Actual output raw"<<endl;
    cerr << actual_out<<endl;
*/
    actual_out = trim(actual_out);
    actual_o_fir = actual_out.s;
    actual_o_0 = actual_out.sample_number(0.0);
    double peak_scale = actual_o_fir[actual_o_0];
    vector<double>::iterator aoptr;
    for (aoptr = actual_o_fir.begin(); aoptr != actual_o_fir.end(); ++aoptr)
      (*aoptr) /= peak_scale;
    /* This is the size of the inverse wavelet convolution transient
    we use it to prevent iterations in transient region of the deconvolved
    data */
    wavelet_pad = winv.s.size();
    if (2 * wavelet_pad > ndwin) {
      stringstream ss;
      ss << base_error << "Inadequate data window size" << endl
         << "trimmed FIR filter size for actual output signal=" << wavelet_pad
         << endl
         << "Data window length=" << ndwin << endl
         << "Window size must be larger than two times FIR filter size" << endl;
      throw MsPASSError(ss.str(), ErrorSeverity::Invalid);
    }
    /* These two signals should be trimmed by winv.npts() on both ends to remove
    sections that are pure edge transients.
    REMOVE me when that is done*/
    r = sparse_convolve(winv, d_all);
    /* Replace n by convolution with inverse wavelet to get the levels correct
     */
    n = sparse_convolve(winv, n);
    TimeWindow trimwin;
    trimwin.start = n.t0() + (n.dt()) * ((double)(winv.npts()));
    trimwin.end = n.endtime() - (n.dt()) * ((double)(winv.npts()));
    n = WindowData(n, trimwin);
    // double nfloor;
    // nfloor=compute_resid_linf_floor();
    // DEBUG - for debug always print this.  Should be a verbose option
    // cerr << "Computed noise floor="<<nfloor<<endl;
    /* d_all now contains the deconvolved data.  Now enter the
    generalized iterative method recursion */
    int i, k;
    lag_weights.clear();
    vector<double> amps, wamps; // raw and weighted amplitudes
    amps.reserve(r.npts());
    wamps.reserve(r.npts());
    /* We need these iterators repeatedly in the main loop below */
    vector<double>::iterator amax;
    for (i = 0; i < r.npts(); ++i)
      lag_weights.push_back(1.0);
    // DEBUG - temporarily disabled for testing
    // for(i=0; i<wavelet_pad; ++i) lag_weights[i]=0.0;
    // for(i=0; i<wavelet_pad; ++i) lag_weights[r.npts()-i-1]=0.0;
    /* These are initial values of convergence parameters */
    lw_linf_initial = 1.0;
    lw_l2_initial = 1.0;
    resid_linf_initial = Linf(r.u);
    resid_l2_initial = L2(r.u);
    iter_count = 0;
    // DEBUG - remove after testing
    lw_linf_history.push_back(lw_linf_initial);
    lw_l2_history.push_back(lw_l2_initial);
    resid_l2_history.push_back(resid_l2_initial);
    resid_linf_history.push_back(resid_linf_initial);
    do {
      /* Compute the vector of amplitudes and find the maximum */
      amps = amp3c(r.u);
      wamps.clear();
      for (k = 0; k < amps.size(); ++k)
        wamps.push_back(amps[k] * lag_weights[k]);
      amax = max_element(wamps.begin(), wamps.end());
      /* The generic distance algorithm used here returns an integer
      that would work to access amps[imax] so we can use the same index
      for the column of the data in d.u. */
      int imax = distance(wamps.begin(), amax);
      /* Save the 3c amplitude at this lag to the spike condensed
      respresentation of the output*/
      ThreeCSpike spk(r.u, imax);
      spikes.push_back(spk);
      // DEBUG
      cerr << iter_count << " col=" << spk.col << " " << "t=" << r.time(spk.col)
           << " amps=" << spk.u[0] << ", " << spk.u[1] << ", " << spk.u[2]
           << endl;
      /* This private method defines how the lag_weights vector is changed
      in the vicinity of this spike.  The tacit assumption is the weight is
      made smaller (maybe even zero) at the spike point and a chosen recipe
      for points in the vicinity of that spike */
      this->update_lag_weights(imax);
      /* Subtract the actual output from the data at lag imax.  Note
      We don't test validity of the lag in spk, but depend on dmatrix to throw
      an exception of the range is invalid */
      this->update_residual_matrix(spk);
      ++iter_count;
    } while (this->has_not_converged());
    if (iter_count >= iter_max)
      throw MsPASSError("GeneralIterDecon::process did not converge",
                        ErrorSeverity::Suspect);
  } catch (...) {
    throw;
  };
}
QCMetrics()
Metadata mspass::algorithms::deconvolution::GeneralIterDecon::QCMetrics () virtual
Return appropriate quality measures.
Each operator commonly has different was to measure the quality of the result. This method should return these in a generic Metadata object.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  cerr << "QCMetrics method not yet implemented" << endl;
  exit(-1);
}
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/cxx/include/mspass/algorithms/deconvolution/GeneralIterDecon.h
/home/runner/work/mspass/mspass/cxx/src/lib/algorithms/deconvolution/GeneralIterDecon.cc