MsPASS C++ API: mspass::seismic::TimeSeriesWGaps Class Reference
mspass::seismic::TimeSeriesWGaps Class Reference
Public Member Functions
TimeSeriesWGaps ()
Constructor.
TimeSeriesWGaps (const TimeSeries &parent)
TimeSeriesWGaps (const TimeSeriesWGaps &parent)
TimeSeriesWGaps (const TimeSeries &tsp, const DataGap &dgp)
TimeSeriesWGaps & operator= (const TimeSeriesWGaps &parent)
void ator (const double tshift)
void rtoa (const double tshift)
void rtoa ()
void shift (const double dt)
void zero_gaps ()
size_t memory_use () const
Public Member Functions inherited from mspass::seismic::TimeSeries
TimeSeries ()
TimeSeries (const size_t nsamples)
TimeSeries (const BasicTimeSeries &bts, const Metadata &md)
TimeSeries (const Metadata &md)
TimeSeries (const mspass::seismic::CoreTimeSeries &d)
Construct from lower level CoreTimeSeries.
TimeSeries (const mspass::seismic::CoreTimeSeries &d, const std::string alg)
TimeSeries (const mspass::seismic::BasicTimeSeries &b, const mspass::utility::Metadata &m, const mspass::utility::ProcessingHistory &mcts, const std::vector< double > &d)
TimeSeries (const TimeSeries &parent)
TimeSeries & operator= (const TimeSeries &parent)
TimeSeries & operator+= (const TimeSeries &d)
TimeSeries & operator*= (const double scale)
TimeSeries & operator-= (const TimeSeries &d)
void load_history (const mspass::utility::ProcessingHistory &h)
size_t memory_use () const
Public Member Functions inherited from mspass::seismic::CoreTimeSeries
CoreTimeSeries ()
CoreTimeSeries (const size_t nsin)
CoreTimeSeries (const BasicTimeSeries &bts, const Metadata &md)
CoreTimeSeries (const CoreTimeSeries &)
void set_dt (const double sample_interval)
Set the sample interval.
void set_npts (const size_t npts)
Set the number of samples attribute for data.
void sync_npts ()
Sync the number of samples attribute with actual data size.
void set_t0 (const double t0in)
Set the data start time.
CoreTimeSeries & operator= (const CoreTimeSeries &parent)
CoreTimeSeries & operator+= (const CoreTimeSeries &d)
Summation operator.
const CoreTimeSeries operator+ (const CoreTimeSeries &other) const
CoreTimeSeries & operator*= (const double)
CoreTimeSeries & operator-= (const CoreTimeSeries &d)
Subtraction operator.
const CoreTimeSeries operator- (const CoreTimeSeries &other) const
double operator[] (size_t const sample) const
Public Member Functions inherited from mspass::seismic::BasicTimeSeries
BasicTimeSeries ()
BasicTimeSeries (const BasicTimeSeries &)
virtual ~BasicTimeSeries ()
Virtual destructor.
double time (const int i) const
int sample_number (double t) const
double endtime () const noexcept
bool shifted () const
double get_t0shift () const
double time_reference () const
void force_t0_shift (const double t)
Force a t0 shift value on data.
bool live () const
bool dead () const
void kill ()
void set_live ()
double dt () const
bool time_is_UTC () const
bool time_is_relative () const
TimeReferenceType timetype () const
double samprate () const
size_t npts () const
double t0 () const
std::vector< double > time_axis () const
void set_tref (const TimeReferenceType newtref)
Force the time standard.
BasicTimeSeries & operator= (const BasicTimeSeries &parent)
Public Member Functions inherited from mspass::utility::Metadata
Metadata ()
Metadata (std::ifstream &ifs, const std::string form=std::string("pf"))
Metadata (const Metadata &mdold)
virtual ~Metadata ()
Metadata & operator= (const Metadata &mdold)
Metadata & operator+= (const Metadata &rhs) noexcept
const Metadata operator+ (const Metadata &other) const
double get_double (const std::string key) const override
int get_int (const std::string key) const override
long get_long (const std::string key) const
std::string get_string (const std::string key) const override
bool get_bool (const std::string key) const override
template<typename T >
T get (const std::string key) const
template<typename T >
T get (const char *key) const
Generic get interface for C char array.
boost::any get_any (const std::string key) const
std::string type (const std::string key) const
template<typename T >
void put (const std::string key, T val) noexcept
template<typename T >
void put (const char *key, T val) noexcept
void put (const std::string key, const double val) override
void put (const std::string key, const int val) override
void put (const std::string key, const bool val) override
void put (const std::string key, const std::string val) override
void put (const char *key, const char *val)
void put (std::string key, const char *val)
void put_object (const std::string key, const pybind11::object val)
void put_int (const std::string key, const int val)
void put_string (const std::string key, const std::string val)
void put_bool (const std::string key, const bool val)
void put_double (const std::string key, const double val)
void put_long (const std::string key, const long val)
void append_chain (const std::string key, const std::string val, const std::string separator=std::string(":"))
std::set< std::string > modified () const
void clear_modified ()
Mark all data as unmodified.
std::set< std::string > keys () const noexcept
bool is_defined (const std::string key) const noexcept
void erase (const std::string key)
std::size_t size () const noexcept
std::map< std::string, boost::any >::const_iterator begin () const noexcept
std::map< std::string, boost::any >::const_iterator end () const noexcept
void change_key (const std::string oldkey, const std::string newkey)
Change the keyword to access an attribute.
Public Member Functions inherited from mspass::utility::ProcessingHistory
ProcessingHistory ()
ProcessingHistory (const std::string jobnm, const std::string jid)
ProcessingHistory (const ProcessingHistory &parent)
bool is_empty () const
bool is_raw () const
bool is_origin () const
bool is_volatile () const
bool is_saved () const
size_t number_of_stages () override
Return number of processing stages that have been applied to this object.
void set_as_origin (const std::string alg, const std::string algid, const std::string uuid, const AtomicType typ, bool define_as_raw=false)
std::string new_ensemble_process (const std::string alg, const std::string algid, const AtomicType typ, const std::vector< ProcessingHistory * > parents, const bool create_newid=true)
void add_one_input (const ProcessingHistory &data_to_add)
Add one datum as an input for current data.
void add_many_inputs (const std::vector< ProcessingHistory * > &d)
Define several data objects as inputs.
void merge (const ProcessingHistory &data_to_add)
Merge the history nodes from another.
void accumulate (const std::string alg, const std::string algid, const AtomicType typ, const ProcessingHistory &newinput)
Method to use with a spark reduce algorithm.
std::string clean_accumulate_uuids ()
Clean up inconsistent uuids that can be produced by reduce.
std::string new_map (const std::string alg, const std::string algid, const AtomicType typ, const ProcessingStatus newstatus=ProcessingStatus::VOLATILE)
Define this algorithm as a one-to-one map of same type data.
std::string new_map (const std::string alg, const std::string algid, const AtomicType typ, const ProcessingHistory &data_to_clone, const ProcessingStatus newstatus=ProcessingStatus::VOLATILE)
Define this algorithm as a one-to-one map.
std::string map_as_saved (const std::string alg, const std::string algid, const AtomicType typ)
Prepare the current data for saving.
void clear ()
std::multimap< std::string, mspass::utility::NodeData > get_nodes () const
int stage () const
ProcessingStatus status () const
std::string id () const
std::pair< std::string, std::string > created_by () const
NodeData current_nodedata () const
std::string newid ()
int number_inputs () const
int number_inputs (const std::string uuidstr) const
void set_id (const std::string newid)
std::list< mspass::utility::NodeData > inputs (const std::string id_to_find) const
Return a list of data that define the inputs to a give uuids.
ProcessingHistory & operator= (const ProcessingHistory &parent)
Public Member Functions inherited from mspass::utility::BasicProcessingHistory
BasicProcessingHistory (const std::string jobname, const std::string jobid)
BasicProcessingHistory (const BasicProcessingHistory &parent)
std::string jobid () const
void set_jobid (const std::string &newjid)
std::string jobname () const
void set_jobname (const std::string jobname)
BasicProcessingHistory & operator= (const BasicProcessingHistory &parent)
Public Member Functions inherited from mspass::seismic::DataGap
DataGap ()
DataGap (const std::list< mspass::algorithms::TimeWindow > &twlist)
DataGap (const DataGap &parent)
bool is_gap (const double ttest)
bool has_gap (const mspass::algorithms::TimeWindow twin)
bool has_gap ()
void add_gap (const mspass::algorithms::TimeWindow tw)
std::list< mspass::algorithms::TimeWindow > get_gaps () const
void clear_gaps ()
Clear gaps.
int number_gaps () const
DataGap subset (const mspass::algorithms::TimeWindow tw) const
void translate_origin (double time_of_new_origin)
DataGap & operator= (const DataGap &parent)
DataGap & operator+= (const DataGap &other)
Additional Inherited Members
Public Attributes inherited from mspass::seismic::CoreTimeSeries
std::vector< double > s
Public Attributes inherited from mspass::utility::ProcessingHistory
ErrorLogger elog
Protected Attributes inherited from mspass::seismic::BasicTimeSeries
bool mlive
double mdt
double mt0
size_t nsamp
TimeReferenceType tref
bool t0shift_is_valid
double t0shift
Protected Attributes inherited from mspass::utility::Metadata
std::map< std::string, boost::any > md
std::set< std::string > changed_or_set
Protected Attributes inherited from mspass::utility::ProcessingHistory
std::multimap< std::string, mspass::utility::NodeData > nodes
Protected Attributes inherited from mspass::utility::BasicProcessingHistory
std::string jid
std::string jnm
Protected Attributes inherited from mspass::seismic::DataGap
std::set< mspass::algorithms::TimeWindow, mspass::algorithms::TimeWindowCmp > gaps
Holds data gap definitions. We use an STL set object to define data gaps for any time series object derived from this base class. The set is keyed by a TimeWindow which allows a simple, fast way to define a time range with invalid data.
Constructor & Destructor Documentation
TimeSeriesWGaps() [1/4]
mspass::seismic::TimeSeriesWGaps::TimeSeriesWGaps () inline
Constructor.
Will need a set of conastructors. Requires some thought as how to set gap is an issue.
:TimeSeries(),DataGap(){};
TimeSeriesWGaps() [2/4]
mspass::seismic::TimeSeriesWGaps::TimeSeriesWGaps (const TimeSeries & parent) inline
Partial copy constructor from a plain TimeSeries.
Sometimes we need to build the skeleton of a gappy TimeSeries from a regular TimeSeries. This does that and builds makes a copy of the TimeSeries and creates an empty container that defines the gaps.
: TimeSeries(parent),DataGap(){};
TimeSeriesWGaps() [3/4]
mspass::seismic::TimeSeriesWGaps::TimeSeriesWGaps (const TimeSeriesWGaps & parent) inline
Copy constructor.
      : TimeSeries(dynamic_cast<const TimeSeries&>(parent)),
              DataGap(dynamic_cast<const DataGap&>(parent)){};;
TimeSeriesWGaps() [4/4]
mspass::seismic::TimeSeriesWGaps::TimeSeriesWGaps (const TimeSeries & tsp, const DataGap & dgp) inline
      : TimeSeries(tsp), DataGap(dgp) {};
~TimeSeriesWGaps()
virtual mspass::seismic::TimeSeriesWGaps::~TimeSeriesWGaps () inline virtual
{};
Member Function Documentation
ator()
void mspass::seismic::TimeSeriesWGaps::ator (const double tshift) virtual
Absolute to relative time conversion. Sometimes we want to convert data from absolute time (epoch times) to a relative time standard. Examples are conversions to travel time using an event origin time or shifting to an arrival time reference frame. This operation simply switches the tref variable and alters t0 by tshift.
This method overrides the one in BasicTimeSeries to correctly reference gaps.
Parameters
tshift - time shift applied to data before switching data to relative time mode.
Reimplemented from mspass::seismic::BasicTimeSeries.
{
  /* dead traces should to totally ignored */
  if(this->dead()) return;
  if(tref==TimeReferenceType::Relative) return;
  this->t0shift=tshift;
  this->mt0 -= tshift;
  // We have to shift all the gap windows definitions
  TimeWindow tw;
  std::set <TimeWindow,TimeWindowCmp> shifted_gaps;
  std::set <TimeWindow,TimeWindowCmp>::iterator this_gap;
  for(this_gap=gaps.begin();this_gap!=gaps.end();++this_gap)
  {
    tw.start = this_gap->start - tshift;
    tw.end = this_gap->end - tshift;
    shifted_gaps.insert(tw);
  }
  /* the section below is a replacement for the following simple
  construct that worked in the old seispp library that used a
  similar construct for gaps:
  this->gaps = shifted_gaps;
  Had to use the clear and loop below because g++ complained about operator=
  not being defined for the set container.   This loop is likely actually
  faster than having to call operator= anyway but why this fails is unknown. */
  this->gaps.clear();
  for(this_gap=shifted_gaps.begin();this_gap!=shifted_gaps.end();++this_gap)
  {
    this->gaps.insert(*this_gap);
  }
  this->tref=TimeReferenceType::Relative;
  this->t0shift_is_valid=true;
}
References mspass::seismic::BasicTimeSeries::dead(), mspass::seismic::DataGap::gaps, mspass::utility::Metadata::get(), mspass::seismic::BasicTimeSeries::mt0, mspass::seismic::Relative, mspass::algorithms::TimeWindow::start, and mspass::seismic::BasicTimeSeries::tref.
memory_use()
size_t mspass::seismic::TimeSeriesWGaps::memory_use () const
Return an estimate of the memmory use by the data in this object.
Memory consumed by a TimeSeriesWGaps object is needed to implement the sizeof method in python that dask/spark use to manage memory. Without that feature we had memory fault issues. Note the estimate this method returns should not be expected to be exact. The MsPASS implementation or any alternative implementation avoids an exact calculation because it requries an (expensive) traversal of multiple map containers.
{
  size_t memory_estimate;
  memory_estimate = TimeSeries::memory_use();
  memory_estimate += DATA_GAP_AVERAGE_SIZE*gaps.size();
  return memory_estimate;
}
References mspass::seismic::DataGap::gaps, mspass::utility::Metadata::get(), and mspass::seismic::TimeSeries::memory_use().
operator=()
TimeSeriesWGaps & mspass::seismic::TimeSeriesWGaps::operator= (const TimeSeriesWGaps & parent)
{
  if(this!=(&parent))
  {
      this->TimeSeries::operator=(parent);
      this->gaps = parent.gaps;
  }
  return *this;
}
rtoa() [1/2]
void mspass::seismic::TimeSeriesWGaps::rtoa () virtual
Relative to absolute time conversion. Sometimes we want to convert data from relative time to to an absolute time standard. An example would be converting segy shot data to something that could be processed like earthquake data in a css3.0 database.
This method returns data previously converted to relative back to absolute using the internally stored time shift attribute.
This method overrides the one in BasicTimeSeries to correctly reference gaps.
Reimplemented from mspass::seismic::BasicTimeSeries.
{
  /* dead traces should to totally ignored */
  if(this->dead()) return;
  const std::string errormess("TimeSeriesWGaps::rtoa() t0shift for conversion is not defined.");
  /* This perhaps should create a complaint  message */
  if(tref==TimeReferenceType::UTC) return;
  /* A rather odd test for a nonzero.   We use 100 s assuming no active
  * source data would use a shift longer than that unless it really did
  * have an absolute time standard. Also assumes we'll never use data from
  * the first 2 minutes of 1960.*/
  if(t0shift_is_valid || (t0shift>100.0) )
  {
    this->mt0 += this->t0shift;
    TimeWindow tw;
    std::set <TimeWindow,TimeWindowCmp> shifted_gaps;
    std::set <TimeWindow,TimeWindowCmp>::iterator this_gap;
    for(this_gap=gaps.begin();this_gap!=gaps.end();++this_gap)
    {
      tw.start = this_gap->start + t0shift;
      tw.end = this_gap->end + t0shift;
      shifted_gaps.insert(tw);
    }
    /* See related comment on why the line below will not compile */
    //this->gaps = shifted_gaps;
    this->gaps.clear();
    for(this_gap=shifted_gaps.begin();this_gap!=shifted_gaps.end();++this_gap)
    {
      this->gaps.insert(*this_gap);
    }
    this->tref=TimeReferenceType::UTC;
    t0shift_is_valid=false;
  }
  else
  {
    this->kill();
    throw MsPASSError(errormess,ErrorSeverity::Invalid);
  }
}
References mspass::seismic::BasicTimeSeries::dead(), mspass::seismic::DataGap::gaps, mspass::utility::Metadata::get(), mspass::seismic::BasicTimeSeries::kill(), mspass::seismic::BasicTimeSeries::mt0, mspass::algorithms::TimeWindow::start, mspass::seismic::BasicTimeSeries::tref, and mspass::seismic::UTC.
rtoa() [2/2]
void mspass::seismic::TimeSeriesWGaps::rtoa (const double tshift)
Relative to absolute time conversion. Sometimes we want to convert data from relative time to to an absolute time standard. An example would be converting segy shot data to something that could be processed like earthquake data in a css3.0 database. This operation simply switches the tref variable and alters t0 by tshift.
This method overrides the one in BasicTimeSeries to correctly reference gaps.
Parameters
tshift - time shift applied to data before switching data to absolute time mode.
NOTE: This method is maintained only for backward compatibility. May be depricated in favor of method that uses internally stored private shift variable.
{
  /* dead traces should to totally ignored */
  if(this->dead()) return;
  if(tref==TimeReferenceType::UTC) return;
  this->mt0 += tshift;
  TimeWindow tw;
  std::set <TimeWindow,TimeWindowCmp> shifted_gaps;
  std::set <TimeWindow,TimeWindowCmp>::iterator this_gap;
  for(this_gap=gaps.begin();this_gap!=gaps.end();++this_gap)
  {
    tw.start = this_gap->start + tshift;
    tw.end = this_gap->end + tshift;
    shifted_gaps.insert(tw);
  }
  /* See related comment on why the line below will not compile */
  //this->gaps = shifted_gaps;
  this->gaps.clear();
  for(this_gap=shifted_gaps.begin();this_gap!=shifted_gaps.end();++this_gap)
  {
    this->gaps.insert(*this_gap);
  }
  this->tref=TimeReferenceType::UTC;
  this->t0shift_is_valid=true;
}
References mspass::seismic::BasicTimeSeries::dead(), mspass::seismic::DataGap::gaps, mspass::utility::Metadata::get(), mspass::seismic::BasicTimeSeries::mt0, mspass::algorithms::TimeWindow::start, mspass::seismic::BasicTimeSeries::tref, and mspass::seismic::UTC.
shift()
void mspass::seismic::TimeSeriesWGaps::shift (const double dt) virtual
Shift the reference time.
Sometimes we need to shift the reference time t0. An example is a moveout correction. This method shifts the reference time by dt. Note a positive dt means data aligned to zero will be shifted left because relative time is t-t0.
Reimplemented from mspass::seismic::BasicTimeSeries.
{
  /* This is the same test for valid t0shift used in BasicTimeSeries*/
  if(this->t0shift_is_valid || (this->t0shift>100.0) )
  {
    double oldt0shift=this->t0shift;
    this->rtoa();
    this->ator(oldt0shift+dt);
  }
  else
  {
    this->kill();
    std::stringstream ss;
    ss<<"TimeSeriesWGaps::shift:  internal shift attributes is marked invalid"
       <<std::endl
       <<"shift method should only be used on data originating with a UTC time standard"
       <<std::endl;
    throw MsPASSError(ss.str(),ErrorSeverity::Invalid);
  }
}
References ator(), mspass::seismic::BasicTimeSeries::dt(), mspass::utility::Metadata::get(), mspass::seismic::BasicTimeSeries::kill(), and rtoa().
zero_gaps()
void mspass::seismic::TimeSeriesWGaps::zero_gaps ()
Force all data inside data gaps to zero.
{
  int i,istart,iend;
  std::set<TimeWindow,TimeWindowCmp>::iterator this_gap;
  for(this_gap=gaps.begin();this_gap!=gaps.end();++this_gap)
  {
    if(this_gap->end < this->mt0) continue;
    if(this_gap->start > this->endtime()) continue;
    if(this_gap->start<this->mt0)
      istart = 0;
    else
      istart = round((this_gap->start-this->mt0)/this->mdt);
    if((this_gap->end) > this->endtime())
      iend = this->nsamp - 1;
    else
      iend = round((this_gap->end-mt0)/this->mdt);
    for(i=istart;i<=iend;++i) this->s[i]=0.0;
  }
}
References mspass::seismic::DataGap::gaps, mspass::utility::Metadata::get(), mspass::seismic::BasicTimeSeries::mt0, mspass::seismic::BasicTimeSeries::nsamp, and mspass::seismic::CoreTimeSeries::s.
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/cxx/include/mspass/seismic/TimeSeriesWGaps.h
/home/runner/work/mspass/mspass/cxx/src/lib/seismic/TimeSeriesWGaps.cc