MsPASS C++ API: mspass::algorithms::deconvolution::CNR3CDecon Class Reference
mspass::algorithms::deconvolution::CNR3CDecon Class Reference
Colored Noise Regularized 3C Deconvolution opertor.
#include <CNR3CDecon.h>
Public Member Functions
CNR3CDecon ()
CNR3CDecon (const mspass::utility::AntelopePf &pf)
Construct from a tree of parameters loaded into an AntelopePf object.
CNR3CDecon (const CNR3CDecon &parent)
~CNR3CDecon ()
CNR3CDecon & operator= (const CNR3CDecon &parent)
void change_parameters (const mspass::utility::BasicMetadata &md)
Change the setup of the operator on the fly.
void loaddata (mspass::seismic::Seismogram &d, const int wcomp, const bool loadnoise=false)
Load data with one component used as wavelet estimate.
void loaddata (mspass::seismic::Seismogram &d, const bool loadnoise=false)
Load data and optionally load noise.
void loadnoise_data (const mspass::seismic::Seismogram &n)
Load noise data directly.
void loadnoise_data (const mspass::seismic::PowerSpectrum &n)
Load noise estimate directly as a PowerSpectrum object.
void loadwavelet (const mspass::seismic::TimeSeries &w)
Load data defining the wavelet to use for deconvolution.
void loadnoise_wavelet (const mspass::seismic::TimeSeries &n)
Load noise data for wavelet directly.
void loadnoise_wavelet (const mspass::seismic::PowerSpectrum &n)
Load noise estimate for wavelet signal directly as a PowerSpectrum object.
mspass::seismic::Seismogram process ()
Apply the loaded 3C deconvolution operator.
mspass::seismic::TimeSeries output_shaping_wavelet ()
Return the output shaping wavelet.
mspass::seismic::TimeSeries ideal_output ()
mspass::seismic::TimeSeries actual_output ()
Return the actual output of the deconvolution operator.
mspass::seismic::TimeSeries resolution_kernel ()
Alias for actual_output using inverse-theory terminology.
mspass::seismic::TimeSeries inverse_wavelet (double tshift)
Return a FIR represention of the inverse filter.
mspass::utility::Metadata QCMetrics ()
Return appropriate quality measures.
mspass::seismic::PowerSpectrum wavelet_noise_spectrum ()
mspass::seismic::PowerSpectrum data_noise_spectrum ()
mspass::seismic::PowerSpectrum wavelet_spectrum ()
mspass::seismic::PowerSpectrum data_spectrum ()
Public Member Functions inherited from mspass::algorithms::deconvolution::FFTDeconOperator
FFTDeconOperator ()
Construct an empty FFT operator shell.
FFTDeconOperator (const mspass::utility::Metadata &md)
Construct from deconvolution Metadata.
FFTDeconOperator (const FFTDeconOperator &parent)
Copy constructor.
~FFTDeconOperator ()
Release allocated GSL FFT work objects.
FFTDeconOperator & operator= (const FFTDeconOperator &parent)
Assign FFT size and lag shift from another operator.
void changeparameter (const mspass::utility::Metadata &md)
Reconfigure the FFT operator from Metadata.
void change_size (const int nfft_new)
Change the FFT work-buffer length.
void change_shift (const int shift)
Set the sample offset used to unwrap deconvolution lag windows.
int get_size ()
Return the current FFT work-buffer length.
int get_shift ()
Return the current deconvolution lag-window sample shift.
int operator_size ()
Return the current FFT work-buffer length.
int operator_shift ()
Return the current deconvolution lag-window sample shift.
double df (const double dt)
Return frequency spacing for the current FFT length.
mspass::seismic::CoreTimeSeries FourierInverse (const ComplexArray &winv, const ComplexArray &sw, const double dt, const double t0parent)
Return inverse wavelet for Fourier methods.
Additional Inherited Members
Protected Attributes inherited from mspass::algorithms::deconvolution::FFTDeconOperator
int nfft
Current FFT work-buffer length in samples.
int sample_shift
Sample offset used to place zero lag in deconvolution outputs.
gsl_fft_complex_wavetable * wavetable
GSL factorization table allocated for nfft.
gsl_fft_complex_workspace * workspace
GSL scratch workspace allocated for nfft.
ComplexArray winv
Frequency-domain inverse wavelet coefficients for derived operators.
Detailed Description
Colored Noise Regularized 3C Deconvolution opertor.
This algorithm is somewhat of a synthesis of the best features from the various frequency comain methods currently in use for receiver function estimation. Key features are:
Data are tapered by a generic function with a range of options.
The output is always a Seismogram, which in MsPASS means 3C data
The inverse is regularized by a scaled 3C noise estimate.
Perhaps most importantly the shaping wavelet is computed dynamically based on bandwidth estimated from the combination power spectrum estimates of the signal and noise for both the data being deconvolved and the wavelet used to compute the inverse. For array methods the two noise estimates can be drastically different.
This object is what might be called a processing object. That is, it does not use the model of construction creating the thing it defines (Seismogram, for example, uses that paradigm). Instead the constructor defines the operator. Data are processed by first calling one of the loaddata and loadnoise methods. Once valid data is loaded call the process method to deconvolve the loaded data. Note this approach assumes the data, wavelet, and noise used for the processing are internally consistent. The user is warned there a limited safeties to validate any consistency because it would be hard to do so without causing more problems that it would solve. In MsPASS we expect to hide this a bit behind some python wrappers to create more safety mechanisms.
Constructor & Destructor Documentation
CNR3CDecon() [1/3]
mspass::algorithms::deconvolution::CNR3CDecon::CNR3CDecon ()
Default constructor. Puts operator in an invalid state.
    : FFTDeconOperator(), signalengine(), waveletengine(), dnoise_engine(),
      wnoise_engine(), shapingwavelet(), psnoise(), psnoise_data(), decondata(),
      wavelet() {
  algorithm = CNR3C_algorithms::undefined;
  operator_dt = 1.0;
  winlength = 0;
  processing_window = TimeWindow(0.0, 1.0);
  noise_window = TimeWindow(0.0, 1.0);
  damp = 0.0;
  noise_floor = 0.0001;
  snr_regularization_floor = 1.5;
  taper_data = false;
  fhs = 2.0; // appropriate for teleseismic P wave data
  for (int k = 0; k < 3; ++k) {
    signal_bandwidth_fraction[k] = 0.0;
    peak_snr[k] = 0.0;
  }
}
CNR3CDecon() [2/3]
mspass::algorithms::deconvolution::CNR3CDecon::CNR3CDecon (const mspass::utility::AntelopePf & pf)
Construct from a tree of parameters loaded into an AntelopePf object.
There number of inputs to construct this operator are quite large. An AntelelopePf is one way to store this information and the format assumed by this constructor. Note this object could be constructed from a yaml or xml file, in principle, but for the present we use Antelope's pf file \ format. i.e. a typical program would read a pf file and to construct the object passed as pf.
    : FFTDeconOperator(pf), signalengine(), waveletengine(), dnoise_engine(),
      wnoise_engine(), shapingwavelet(pf), psnoise(), psnoise_data(),
      decondata(), wavelet() {
  // DEBUG
  // cout << "Entering pf constructor"<<endl;
  this->read_parameters(pf);
}
CNR3CDecon() [3/3]
mspass::algorithms::deconvolution::CNR3CDecon::CNR3CDecon (const CNR3CDecon & parent)
Standard copy constructor.
    : processing_window(parent.processing_window),
      noise_window(parent.noise_window), signalengine(parent.signalengine),
      waveletengine(parent.waveletengine), dnoise_engine(parent.dnoise_engine),
      wnoise_engine(parent.wnoise_engine),
      shapingwavelet(parent.shapingwavelet), psnoise(parent.psnoise),
      psnoise_data(parent.psnoise_data), pssignal(parent.pssignal),
      pswavelet(parent.pswavelet), decondata(parent.decondata),
      wavelet(parent.wavelet), wavelet_taper(parent.wavelet_taper),
      data_taper(parent.data_taper), ao_fft(parent.ao_fft),
      wavelet_bwd(parent.wavelet_bwd), signal_bwd(parent.signal_bwd),
      wavelet_snr(parent.wavelet_snr)
{
  algorithm = parent.algorithm;
  taper_data = parent.taper_data;
  operator_dt = parent.operator_dt;
  winlength = parent.winlength;
  damp = parent.damp;
  noise_floor = parent.noise_floor;
  snr_regularization_floor = parent.snr_regularization_floor;
  snr_bandwidth = parent.snr_bandwidth;
  band_snr_floor = parent.band_snr_floor;
  regularization_bandwidth_fraction = parent.regularization_bandwidth_fraction;
  decon_bandwidth_cutoff = parent.decon_bandwidth_cutoff;
  fhs = parent.fhs;
  for (int k = 0; k < 3; ++k) {
    signal_bandwidth_fraction[k] = parent.signal_bandwidth_fraction[k];
    peak_snr[k] = parent.peak_snr[k];
  }
}
~CNR3CDecon()
mspass::algorithms::deconvolution::CNR3CDecon::~CNR3CDecon ()
Standard destructor.
{
  // if(wavelet_taper!=NULL) delete wavelet_taper;
  // if(data_taper!=NULL) delete data_taper;
}
Member Function Documentation
actual_output()
TimeSeries mspass::algorithms::deconvolution::CNR3CDecon::actual_output () virtual
Return the actual output of the deconvolution operator.
The actual output is defined as w^-1*w and is compable to resolution kernels in linear inverse theory. Although not required we would normally expect this function to be peaked at 0. Offsets from 0 would imply a bias.
Implements mspass::algorithms::deconvolution::Base3CDecon.
{
  try {
    ComplexArray W(FFTDeconOperator::nfft, &(wavelet.s[0]));
    gsl_fft_complex_forward(W.ptr(), 1, FFTDeconOperator::nfft, wavetable,
                            workspace);
    ComplexArray ao_fft;
    ao_fft = winv * W;
    /* We always apply the shaping wavelet - this perhaps should be optional
    but probably better done with a none option for the shaping wavelet */
    ao_fft = (*shapingwavelet.wavelet()) * ao_fft;
    gsl_fft_complex_inverse(ao_fft.ptr(), 1, FFTDeconOperator::nfft, wavetable,
                            workspace);
    vector<double> ao;
    ao.reserve(FFTDeconOperator::nfft);
    for (int k = 0; k < ao_fft.size(); ++k)
      ao.push_back(ao_fft[k].real());
    /* We always shift this wavelet to the center of the data vector.
    We handle the time through the CoreTimeSeries object. */
    int i0 = FFTDeconOperator::nfft / 2;
    ao = circular_shift(ao, i0);
    TimeSeries result(
        wavelet); // Use this to clone metadata and elog from wavelet
    result.set_npts(FFTDeconOperator::nfft);
    /* Force these even though they are likely already defined as
    in the parent wavelet TimeSeries. */
    result.set_live();
    // result.s=ao;
    result.set_t0(operator_dt * (-(double)i0));
    result.set_dt(this->operator_dt);
    result.set_tref(TimeReferenceType::Relative);
    /* set_npts always initializes the s buffer so it is more efficient to
    copy ao elements rather than what was here before:
      result.s=ao;
      */
    for (int k = 0; k < FFTDeconOperator::nfft; ++k)
      result.s[k] = ao[k];
    return result;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::algorithms::deconvolution::ComplexArray::ptr(), mspass::seismic::CoreTimeSeries::s, mspass::seismic::CoreTimeSeries::set_dt(), mspass::seismic::BasicTimeSeries::set_live(), mspass::seismic::CoreTimeSeries::set_npts(), mspass::seismic::CoreTimeSeries::set_t0(), mspass::seismic::BasicTimeSeries::set_tref(), mspass::algorithms::deconvolution::ComplexArray::size(), mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), mspass::algorithms::deconvolution::FFTDeconOperator::wavetable, mspass::algorithms::deconvolution::FFTDeconOperator::winv, and mspass::algorithms::deconvolution::FFTDeconOperator::workspace.
change_parameters()
void mspass::algorithms::deconvolution::CNR3CDecon::change_parameters (const mspass::utility::BasicMetadata & md)
Change the setup of the operator on the fly.
Sometimes an operator needs to have it's properties adjusted on the fly. this method can be used to redefine its operational properties instead of creating a new instance with the constructor. Use this method with care as it requires the same set of parameters as the AntelopePf constructor. The data are actually passed through the base class for an AntelopePF but currently it is implicitly expected to be data compatible with the pf constructor.
{
  try {
    AntelopePf pf = dynamic_cast<const AntelopePf &>(basemd);
    this->read_parameters(pf);
  } catch (...) {
    throw;
  };
}
data_noise_spectrum()
mspass::seismic::PowerSpectrum mspass::algorithms::deconvolution::CNR3CDecon::data_noise_spectrum () inline
Return the average 3C power spectrum for the latest loaded noise data.
{ return psnoise_data; };
data_spectrum()
mspass::seismic::PowerSpectrum mspass::algorithms::deconvolution::CNR3CDecon::data_spectrum () inline
Return the power spectrum of the signal loaded for deconvolution.
{ return pssignal; };
ideal_output()
TimeSeries mspass::algorithms::deconvolution::CNR3CDecon::ideal_output ()
Return the ideal output shaping wavelet.
{
  try {
    CoreTimeSeries ideal_tmp = this->shapingwavelet.impulse_response();
    return TimeSeries(ideal_tmp, "Invalid");
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::ShapingWavelet::impulse_response().
inverse_wavelet()
TimeSeries mspass::algorithms::deconvolution::CNR3CDecon::inverse_wavelet (double tshift) virtual
Return a FIR represention of the inverse filter.
After any deconvolution is computed one can sometimes produce a finite impulse response (FIR) respresentation of the inverse filter.
Implements mspass::algorithms::deconvolution::Base3CDecon.
{
  try {
    /* Using the time shift of wavelet.t0() may be a bad idea here.  Will
    need to sort that out in debugging behaviour*/
    double timeshift(tshift0);
    timeshift += wavelet.t0();
    // cout << "wavelet t0="<<wavelet.t0()<<endl;
    timeshift -= operator_dt * ((double)winlength);
    // Debug
    // cout << "inverse_wavelet - applying time shift="<<timeshift<<endl;
    CoreTimeSeries invcore(this->FFTDeconOperator::FourierInverse(
        this->winv, *shapingwavelet.wavelet(), operator_dt, timeshift));
    TimeSeries result(invcore, "Invalid");
    /* Copy the error log from wavelet and post some information parameters
    to metadata */
    result.elog = wavelet.elog;
    result.put("waveform_type", "deconvolution_inverse_wavelet");
    result.put("decon_type", "CNR3CDecon");
    return result;
  } catch (...) {
    throw;
  };
}
References mspass::utility::ProcessingHistory::elog, mspass::algorithms::deconvolution::FFTDeconOperator::FourierInverse(), mspass::utility::Metadata::put(), mspass::seismic::BasicTimeSeries::t0(), mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), and mspass::algorithms::deconvolution::FFTDeconOperator::winv.
loaddata() [1/2]
void mspass::algorithms::deconvolution::CNR3CDecon::loaddata (mspass::seismic::Seismogram & d, const bool loadnoise = false)
Load data and optionally load noise.
This method must be called before running process to get a unique result. Input data are windowed by the processing window parameters and inserted into an internal buffer with sufficient padding to avoid fft circular convolution artifacts. Noise can optionally be loaded but use that approach ONLY if the time span of d contains both the processing and noise time windows. Use loadnoise if the input data do not match that model.
Parameters
d is the input data (see note about time span above)
loadnoise when true the function will attempt to load data for the noise based regularization from the noise window defined for the operator.
Exceptions
MsPASSError may be thrown for a number of potential error conditions.
{
  if (d.dead())
    throw MsPASSError("CNR3CDecon::loaddata method received data marked dead",
                      ErrorSeverity::Invalid);
  try {
    int errcount;
    /* The -9999 is a magic number used to signal the test is
    coming from this variant*/
    errcount = TestSeismogramInput(d, -9999, nload);
    if (errcount > 0) {
      stringstream ss;
      ss << "CNR3CDecon::loaddata:  " << errcount
         << " errors were detected in this call" << endl
         << "Check error log of input Seismogram for detailed error messages"
         << endl
         << "Operator does not contain valid data for processing" << endl;
      throw MsPASSError(ss.str(), ErrorSeverity::Invalid);
    }
    CoreSeismogram dtmp(WindowData(d, this->processing_window));
    this->decondata = Seismogram(dtmp, string("invalid"));
    if (FFTDeconOperator::nfft < (2 * this->winlength)) {
      cerr << "CNR3CDecon:  coding error in loaddata method" << endl
           << "fft buffer size=" << FFTDeconOperator::nfft << endl
           << "winlength is only " << this->winlength << endl
           << "fft length is required to be at least twice winlength" << endl
           << "Debug exit to avoid seg fault" << endl;
      exit(-1);
    }
    /* In the old api this was necessary - no longer so because set_npts does
    this operation
    decondata.u=dmatrix(3,FFTDeconOperator::nfft);
    decondata.u.zero();
    */
    decondata.set_npts(FFTDeconOperator::nfft);
    double newt0 = (-operator_dt * static_cast<double>(winlength));
    decondata.set_t0(newt0);
    int k, i, ii;
    for (i = 0; i < dtmp.npts(); ++i) {
      ii = decondata.sample_number(dtmp.time(i));
      if ((ii >= 0) && (ii < decondata.npts())) {
        for (k = 0; k < 3; ++k)
          decondata.u(k, ii) = dtmp.u(k, i);
      }
    }
    /* This was the old code
    int k,i,ii;
    for(k=0;k<3;++k)
        for(i=0,ii=(this->winlength);i<(this->winlength);++i,++ii)
        {
            decondata.u(k,ii)=dtmp.u(k,i);
        }
    double newt0=decondata.t0() - operator_dt*static_cast<double>(winlength);
    //Debug
    cout << "in loaddata; initial t0="<<decondata.t0()<<endl
      << "Changed to "<<newt0<<endl;
    decondata.set_t0(newt0);
    */
    /* We need to compute the power spectrum of the signal here.  It is used
    to compute the bandwidth of the shaping wavelet in process.   This is the
    ONLY place right now this is computed.  Caution in order if there are
    changes in implementation later. */
    this->pssignal = this->ThreeCPower(dtmp);
    if (nload) {
      Seismogram ntmp(WindowData(d, this->noise_window), string("Invalid"));
      this->loadnoise_data(ntmp);
    }
    signal_bwd = EstimateBandwidth(
        FFTDeconOperator::df(this->operator_dt), pssignal, psnoise_data,
        snr_bandwidth, signalengine.time_bandwidth_product(), this->fhs);
  } catch (...) {
    throw;
  };
}
References mspass::seismic::BasicTimeSeries::dead(), mspass::algorithms::deconvolution::FFTDeconOperator::df(), loadnoise_data(), mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::seismic::BasicTimeSeries::npts(), mspass::seismic::BasicTimeSeries::sample_number(), mspass::seismic::CoreSeismogram::set_npts(), mspass::seismic::CoreSeismogram::set_t0(), mspass::seismic::BasicTimeSeries::time(), mspass::algorithms::deconvolution::MTPowerSpectrumEngine::time_bandwidth_product(), and mspass::seismic::CoreSeismogram::u.
loaddata() [2/2]
void mspass::algorithms::deconvolution::CNR3CDecon::loaddata (mspass::seismic::Seismogram & d, const int wcomp, const bool loadnoise = false)
Load data with one component used as wavelet estimate.
Use this method for conventional receiver function data if one of components is to be used as the wavelet estimate (conventionally Z or L). Optionally they can also load preevent noise defined by the noise window parameters defined by Pf constructor.
Parameters
d is the data to be loaded. If loadnoise is true it is assumed to be long enough to span the range of both the signal and noise windows defined in constuction.
wcomp is the component that is used as an estimate of the wavelet. In standard P receiver functions this would be the Z component but for S it would be the radial component
loadnoise when true method also loads noise data from predefined window.
Exceptions
Will throw an MsPASSError for a number of potential problems that can arise. All such errors will have an invalid condition set.
{
  // DEBUG
  // cout << "entering loaddata"<<endl;
  try {
    if (d.dead())
      throw MsPASSError("CNR3CDecon::loaddata method received data marked dead",
                        ErrorSeverity::Invalid);
    /* This does everything except load the wavelet from wcomp so we just
     * invoke it here. */
    this->loaddata(d, loadnoise);
    /* We need to pull wcomp now because we alter the decondata matrix with
     * padding next.  We don't want that for the wavelet at this stage as
     * the loadwavelet method handles the padding stuff and we call it after
     * windowing*/
    CoreTimeSeries wtmp(ExtractComponent(decondata, wcomp));
    wtmp = WindowData(wtmp, this->processing_window);
    TimeSeries wtmp2(wtmp, "Invalid");
    this->loadwavelet(wtmp2);
  } catch (...) {
    throw;
  };
}
References mspass::seismic::BasicTimeSeries::dead(), loaddata(), and loadwavelet().
loadnoise_data() [1/2]
void mspass::algorithms::deconvolution::CNR3CDecon::loadnoise_data (const mspass::seismic::PowerSpectrum & n)
Load noise estimate directly as a PowerSpectrum object.
The actual noise regularization is computed by this algorithm from an internally stored PowerSpectrum object. This method allows the power spectrum to be computed by some other method or using previously computed estimates rather than computing it through loadnoise. For instance, one might want to use a robust form of Welch's method to estimate preevent noise that would be immune to spikes and sporatic noise bursts.
{
  try {
    psnoise_data = d;
  } catch (...) {
    throw;
  };
}
loadnoise_data() [2/2]
void mspass::algorithms::deconvolution::CNR3CDecon::loadnoise_data (const mspass::seismic::Seismogram & n)
Load noise data directly.
This method can be used to load noise to be used to compute signal to noise related metrics. The spectrum of the noise is computed from a mutlitaper spectral estimator for the data passed as n. Best results will be obtain if the length of n is larger than the operator size defined by it's internal noise window (defined in constructor by noise_window_start and and parameters). Note for this constructor the actual time of the noise window passed is ignored, but the length it defines is used to define the length of the computed spectrum. It is better to have the input noise slightly larger than the operator length to be consistent with the expectations of the multitaper method. If the noise window is short the spectrum is computed but will be biased to lower amplitudes because of zero padding. That happens because the operator will not recompute Slepian tapers if the data are short.
{
  if (n.dead())
    throw MsPASSError(
        "CNR3CDecon::loadnoise_data method received data marked dead",
        ErrorSeverity::Invalid);
  try {
    this->psnoise_data = this->ThreeCPower(n);
  } catch (...) {
    throw;
  };
}
References mspass::seismic::BasicTimeSeries::dead().
loadnoise_wavelet() [1/2]
void mspass::algorithms::deconvolution::CNR3CDecon::loadnoise_wavelet (const mspass::seismic::PowerSpectrum & n)
Load noise estimate for wavelet signal directly as a PowerSpectrum object.
The actual noise regularization is computed by this algorithm from an internally stored PowerSpectrum object. This method allows the power spectrum to be computed by some other method or using previously computed estimates rather than computing it through loadnoise.
{
  try {
    psnoise = d;
  } catch (...) {
    throw;
  };
}
loadnoise_wavelet() [2/2]
void mspass::algorithms::deconvolution::CNR3CDecon::loadnoise_wavelet (const mspass::seismic::TimeSeries & n)
Load noise data for wavelet directly.
This method can be used to load noise to be used for regularization from an arbitrary time window. The spectrum of the noise is computed from a mutlitaper spectral estimator for the data passed as n. Best results will be obtain if the length of n is larger than the operator size defined by it's internal noise window (defined in constructor by noise_window_start and and parameters). Note for this constructor the actual time of the noise window passed is ignored, but the length it defines is used to define the length of the computed spectrum. It is better to have the input noise slightly larger than the operator length to be consistent with the expectations of the multitaper method. If the noise window is short the spectrum is computed but will be biased to lower amplitudes because of zero padding. That happens because the operator will not recompute Slepian tapers if the data are short.
{
  // DEBUG
  // cout << "Entering loadnoise_wavelet"<<endl;
  if (n.dead())
    throw MsPASSError(
        "CNR3CDecon::loadnoise_wavelet method received data marked dead",
        ErrorSeverity::Invalid);
  if (n.npts() <= 0)
    throw MsPASSError(
        "CNR3CDecon::loadnoise_wavelet method received an empty data vector.",
        ErrorSeverity::Invalid);
  try {
    if (n.npts() != wnoise_engine.taper_length()) {
      wnoise_engine = MTPowerSpectrumEngine(
          n.npts(), wnoise_engine.time_bandwidth_product(),
          wnoise_engine.number_tapers());
    }
    psnoise = this->wnoise_engine.apply(n);
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::MTPowerSpectrumEngine::apply(), mspass::seismic::BasicTimeSeries::dead(), mspass::seismic::BasicTimeSeries::npts(), mspass::algorithms::deconvolution::MTPowerSpectrumEngine::number_tapers(), mspass::algorithms::deconvolution::MTPowerSpectrumEngine::taper_length(), and mspass::algorithms::deconvolution::MTPowerSpectrumEngine::time_bandwidth_product().
loadwavelet()
void mspass::algorithms::deconvolution::CNR3CDecon::loadwavelet (const mspass::seismic::TimeSeries & w)
Load data defining the wavelet to use for deconvolution.
This algorithm assumes a deterministic model for deconvolution. That is, we have an estimate of the source wavelet. In conventional receiver functions this is the vertical or longitudinal component. In current array methods it is always some stack (not necessarily a simple average) of vertical or longitudinal data from an ensemble.
It is VERY IMPORTANT to realize that loadwavelet initiates the calculation of the inverse for the deconvolution. That allows this same processing object to be efficiently used in array deconvolution and single station deconvolution. For single station estimates loadwavelet should be called on each seismogram. For array methods loadwavelet should be called once for the ensemble (common source gather) to which a wavelet is linked. The inverse is then applied to very signal in the ensemble with process.
Parameters
w is the wavelet. Must be in relative time with 0 set to the estimated first break time.
{
  if (w.dead())
    throw MsPASSError(
        "CNR3CDecon::loadwavelet method received data marked dead",
        ErrorSeverity::Invalid);
  if (w.npts() <= 0)
    throw MsPASSError("CNR3CDecon::loadwavelet method received an empty "
                      "TimeSeries (number samples <=0)",
                      ErrorSeverity::Invalid);
  try {
    /* Automatically and silently adjust the window size if input wavelet
    length changes.   We always compute the wavelet spectrum from the full
    signal loaded.   */
    if (this->waveletengine.taper_length() != (w.npts())) {
      this->waveletengine = MTPowerSpectrumEngine(
          w.npts(), this->waveletengine.time_bandwidth_product(),
          this->waveletengine.number_tapers());
    }
    this->pswavelet = this->waveletengine.apply(w);
    /* for now use the same snr floor as regularization - may need to be an
    independent parameter */
    this->wavelet_bwd = EstimateBandwidth(
        FFTDeconOperator::df(this->operator_dt), pswavelet, psnoise,
        snr_bandwidth, waveletengine.time_bandwidth_product(), this->fhs);
    /* Now load the wavelet into the fft buffer area - there are some tricky
    things to do here to align the data correctly using the relative time
    reference t0 stored with the TimeSeries data */
    int k, kk;
    int ns_to_copy, ntest;
    this->wavelet = w;
    ntest = w.npts() - w.sample_number(0.0);
    if (ntest > (this->winlength)) {
      ns_to_copy = this->winlength;
      stringstream ss;
      ss << "loadwavelet method:  size mismatch.  Wavelet received has "
         << ntest << " samples with time>0.0" << endl
         << "This is larger than the processing window length of "
         << this->winlength << endl
         << "Wavelet must be contained in the processing window size" << endl
         << "Truncated on the right to processing window length - results may "
            "be invalid"
         << endl;
      wavelet.elog.log_error("CNR3CDecon", ss.str(), ErrorSeverity::Complaint);
    } else
      ns_to_copy = w.npts();
    /* These were in the old api but are no longer needed because set_npts
    does this operation
    this->wavelet.s.clear();
    this->wavelet.s.reserve(FFTDeconOperator::nfft);
    for(k=0;k<FFTDeconOperator::nfft;++k)this->wavelet.s.push_back(0.0);
    */
    this->wavelet.set_npts(FFTDeconOperator::nfft);
    this->wavelet.set_t0(-(this->winlength) * (this->operator_dt));
    // DEBUG
    // cout << "t0 of wavelet stored now wavelet data
    // objec="<<wavelet.t0()<<endl;
    /* We recycle the variable ntest defined above here for convenience only */
    for (k = 0, ntest = 0; k < w.npts(); ++k) {
      double t = w.time(k);
      if (t >= 0.0)
        ++ntest;
      if (ntest > ns_to_copy)
        break;
      kk = this->wavelet.sample_number(t);
      if ((kk >= 0) && (kk < this->wavelet.npts()))
        this->wavelet.s[kk] = w.s[k];
    }
    /* This was the old code fixed Dec 2020 - remove when revision is know to
    work
    for(k=0,kk=this->winlength;k<ns_to_copy;++k,++kk)this->wavelet.s[kk]=w.s[k];
    */
    // this->wavelet.t0 -= operator_dt*static_cast<double>(winlength);
    // this->wavelet.ns=FFTDeconOperator::nfft;
    // double newt0;
    // newt0=this->wavelet.t0() - operator_dt*static_cast<double>(winlength);
    // this->wavelet.set_t0(newt0);
    // debug
    /*cout << "Wavelet t, data"<<endl;
    for(auto kw=0;kw<FFTDeconOperator::nfft;++kw)
      cout << wavelet.time(kw)<<" "<<wavelet.s[kw]<<endl;
*/
    switch (algorithm) {
    /* Note all the algorithms here alter wavelet by applying a taper */
    case CNR3C_algorithms::generalized_water_level:
      compute_gwl_inverse();
      break;
    case CNR3C_algorithms::colored_noise_damping:
    default:
      compute_gdamp_inverse();
    };
    // DEBUG
    // cout << "Exiting loadwavelet"<<endl;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::MTPowerSpectrumEngine::apply(), mspass::seismic::BasicTimeSeries::dead(), mspass::algorithms::deconvolution::FFTDeconOperator::df(), mspass::utility::ProcessingHistory::elog, mspass::utility::ErrorLogger::log_error(), mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::seismic::BasicTimeSeries::npts(), mspass::seismic::CoreTimeSeries::s, mspass::seismic::BasicTimeSeries::sample_number(), mspass::seismic::CoreTimeSeries::set_npts(), mspass::seismic::CoreTimeSeries::set_t0(), mspass::algorithms::deconvolution::MTPowerSpectrumEngine::taper_length(), mspass::seismic::BasicTimeSeries::time(), and mspass::algorithms::deconvolution::MTPowerSpectrumEngine::time_bandwidth_product().
operator=()
CNR3CDecon & mspass::algorithms::deconvolution::CNR3CDecon::operator= (const CNR3CDecon & parent)
Assignment operator.
{
  if (this != (&parent)) {
    algorithm = parent.algorithm;
    processing_window = parent.processing_window;
    noise_window = parent.noise_window;
    signalengine = parent.signalengine;
    waveletengine = parent.waveletengine;
    dnoise_engine = parent.dnoise_engine;
    wnoise_engine = parent.wnoise_engine;
    psnoise = parent.psnoise;
    psnoise_data = parent.psnoise_data;
    pssignal = parent.pssignal;
    pswavelet = parent.pswavelet;
    decondata = parent.decondata;
    wavelet = parent.wavelet;
    shapingwavelet = parent.shapingwavelet;
    ao_fft = parent.ao_fft;
    wavelet_snr = parent.wavelet_snr;
    taper_data = parent.taper_data;
    operator_dt = parent.operator_dt;
    winlength = parent.winlength;
    damp = parent.damp;
    noise_floor = parent.noise_floor;
    snr_regularization_floor = parent.snr_regularization_floor;
    snr_bandwidth = parent.snr_bandwidth;
    band_snr_floor = parent.band_snr_floor;
    regularization_bandwidth_fraction =
        parent.regularization_bandwidth_fraction;
    decon_bandwidth_cutoff = parent.decon_bandwidth_cutoff;
    fhs = parent.fhs;
    wavelet_bwd = parent.wavelet_bwd;
    signal_bwd = parent.signal_bwd;
    for (int k = 0; k < 3; ++k) {
      signal_bandwidth_fraction[k] = parent.signal_bandwidth_fraction[k];
      peak_snr[k] = parent.peak_snr[k];
    }
    wavelet_taper = parent.wavelet_taper;
    data_taper = parent.data_taper;
  }
  return *this;
}
output_shaping_wavelet()
mspass::seismic::TimeSeries mspass::algorithms::deconvolution::CNR3CDecon::output_shaping_wavelet () inline
Return the output shaping wavelet.
This is the target finite-bandwidth wavelet used to represent the deconvolved result. The historical name ideal_output is retained for compatibility, but new code should prefer output_shaping_wavelet.
{
    return this->ideal_output();
  }
References ideal_output().
process()
Seismogram mspass::algorithms::deconvolution::CNR3CDecon::process () virtual
Apply the loaded 3C deconvolution operator.
Implementations process the currently loaded data and return the deconvolved three-component result.
Implements mspass::algorithms::deconvolution::Base3CDecon.
{
  // DEBUG
  // cout << "Entering process method"<<endl;
  const string base_error("CNR3CDecon::process method:  ");
  int j, k;
  try {
    /* Immediately determine the data bandwidth for efficiency.
    If the data have insufficient bandwith return a null Seismogram
    with only Metadata and no data.   Do, however, post a message to
    elog in that situation assuming it will be saved to database an
    can be queried to tell what data were deleted for this reason.
    Some of the tests here are more cautious than needed as load
    functions should catch useless data before getting this far. */
    BandwidthData bo;
    bo = band_overlap(wavelet_bwd, signal_bwd);
    /* Note both of the quantities in this test must be in consistent
    untis of dB */
    if (bo.bandwidth() < (this->decon_bandwidth_cutoff)) {
      /* this is a bit inefficient to create this work space and immediately
      destroy it but will do it this way until this proves to be a performance
      problem. */
      Seismogram no_can_do(decondata);
      no_can_do.u = mspass::utility::dmatrix(1, 1);
      /* Be sure this is marked dead */
      no_can_do.kill();
      stringstream ss;
      ss << "Killed because estimated bandwidth=" << bo.bandwidth()
         << " dB is below threshold of " << this->decon_bandwidth_cutoff
         << endl;
      no_can_do.elog.log_error("CNR3CDecon", ss.str(), ErrorSeverity::Invalid);
      return no_can_do;
    }
    this->update_shaping_wavelet(bo);
    Seismogram rfest(decondata);
    post_bandwidth_data(rfest, bo);
    /* This is used to apply a shift to the fft outputs to put signals
    at relative time 0 */
    int t0_shift;
    t0_shift = round((-rfest.t0()) / rfest.dt());
    // DEBUG
    // cout << "time shift applied to output signal="<<t0_shift<<endl;
    vector<double> wvec;
    wvec.reserve(FFTDeconOperator::nfft);
    /* This is the proper mspass way to preserve history */
    // rfest.append_chain("process_sequence","CNR3CDecon");
    if (rfest.npts() != FFTDeconOperator::nfft)
      rfest.u = dmatrix(3, FFTDeconOperator::nfft);
    int nhighsnr;
    double df;
    df = 1.0 / (operator_dt * static_cast<double>(FFTDeconOperator::nfft));
    for (k = 0; k < 3; ++k) {
      TimeSeries work;
      work = TimeSeries(ExtractComponent(decondata, k), "Invalid");
      /* Debug - temporarily remove taper
      if(taper_data) data_taper->apply(work);
      */
      wvec.clear();
      int ntocopy = FFTDeconOperator::nfft;
      if (ntocopy > work.npts())
        ntocopy = work.npts();
      for (j = 0; j < ntocopy; ++j)
        wvec.push_back(work.s[j]);
      for (j = ntocopy; j < FFTDeconOperator::nfft; ++j)
        wvec.push_back(0.0);
      ComplexArray numerator(FFTDeconOperator::nfft, &(wvec[0]));
      // Debug
      // cout << "numerator data after taper for component="<<k<<endl;
      // for(j=0;j<FFTDeconOperator::nfft;++j)cout<<real(numerator[j])<<endl;
      gsl_fft_complex_forward(numerator.ptr(), 1, FFTDeconOperator::nfft,
                              wavetable, workspace);
      /* This loop computes QCMetrics of bandwidth fraction that
      is above a defined snr floor - not necessarily the same as the
      regularization floor used in computing the inverse */
      double snrmax;
      snrmax = 1.0;
      nhighsnr = 0;
      // debug
      // cout << "Spectrum f, signal, noise, snr"<<endl;
      for (j = 0; j < FFTDeconOperator::nfft / 2; ++j) {
        double f;
        f = df * static_cast<double>(j);
        Complex64 z = numerator[j];
        double sigamp = abs(z);
        double namp = sqrt(psnoise.power(f));
        double snr = sigamp / namp;
        // Debug
        // cout <<f<<" "<< sigamp<<" "<<namp<<" "<<snr<<endl;
        if (snr > snrmax)
          snrmax = snr;
        if (snr > band_snr_floor)
          ++nhighsnr;
      }
      signal_bandwidth_fraction[k] =
          static_cast<double>(nhighsnr) /
          static_cast<double>(FFTDeconOperator::nfft / 2);
      peak_snr[k] = snrmax;
      ComplexArray rftmp = numerator * winv;
      rftmp = (*shapingwavelet.wavelet()) * rftmp;
      gsl_fft_complex_inverse(rftmp.ptr(), 1, FFTDeconOperator::nfft, wavetable,
                              workspace);
      wvec.clear();
      for (j = 0; j < FFTDeconOperator::nfft; ++j)
        wvec.push_back(rftmp[j].real());
      // debug
      // cout << "Raw deconvolved data before time shift (re,im)"<<endl;
      // for(j=0;j<FFTDeconOperator::nfft;++j) cout << wvec[j]<<"
      // "<<rftmp[j].imag()<<endl; cout << "Function output uses time
      // shift="<<t0_shift<<endl;
      /* Note we used a time domain shift instead of using a linear phase
      shift in the frequency domain because time domain operator has a lower
      operation count than the frequency domain algorithm and is thus more
      efficient.*/
      /* Debug - temporarily disable this shift*/
      if (t0_shift != 0)
        wvec = circular_shift(wvec, -t0_shift);
      for (j = 0; j < FFTDeconOperator::nfft; ++j)
        rfest.u(k, j) = wvec[j];
    }
    return rfest;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::amplitudes::BandwidthData::bandwidth(), mspass::algorithms::deconvolution::FFTDeconOperator::df(), mspass::seismic::BasicTimeSeries::dt(), mspass::utility::ProcessingHistory::elog, mspass::seismic::BasicTimeSeries::kill(), mspass::utility::ErrorLogger::log_error(), mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::seismic::BasicTimeSeries::npts(), mspass::seismic::PowerSpectrum::power(), mspass::algorithms::deconvolution::ComplexArray::ptr(), mspass::seismic::CoreTimeSeries::s, mspass::seismic::BasicTimeSeries::t0(), mspass::seismic::CoreSeismogram::u, mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), mspass::algorithms::deconvolution::FFTDeconOperator::wavetable, mspass::algorithms::deconvolution::FFTDeconOperator::winv, and mspass::algorithms::deconvolution::FFTDeconOperator::workspace.
QCMetrics()
Metadata mspass::algorithms::deconvolution::CNR3CDecon::QCMetrics () virtual
Return appropriate quality measures.
The QC values return use two concepts: maximum snr is the largest signal to noise ratio estimated across the band exceeded a specified snr floor for the operator. "bandwidth fraction" is the fraction of the total frequency band (ie. 0 to Nyquist) exceeding the operator snr floor.
This function returns the following key-value pairs: waveletbf - bandwidth fraction for wavelet. maxsnr0,maxsnr1,maxsnr2 - maximum signal to noise ratio on each of the three components of the data being deconvolved. signalbf0,signalbf1,signalbf2 - bandwidth fraction for each of the three components of data deconvolved to produce the latest output.
Implements mspass::algorithms::deconvolution::Base3CDecon.
{
  Metadata result;
  result.put("decon_operator", string("CNR3CDecon"));
  result.put("decon_processed", regularization_bandwidth_fraction > 0.0);
  result.put("decon_operator_nfft", nfft);
  result.put("decon_operator_sample_shift", sample_shift);
  result.put("decon_sample_interval", operator_dt);
  result.put("decon_window_start", processing_window.start);
  result.put("decon_window_end", processing_window.end);
  result.put("noise_window_start", noise_window.start);
  result.put("noise_window_end", noise_window.end);
  result.put("cnr_regularization_bandwidth_fraction",
             regularization_bandwidth_fraction);
  result.put("waveletbf", regularization_bandwidth_fraction);
  result.put("maxsnr0", peak_snr[0]);
  result.put("maxsnr1", peak_snr[1]);
  result.put("maxsnr2", peak_snr[2]);
  result.put("signalbf0", signal_bandwidth_fraction[0]);
  result.put("signalbf1", signal_bandwidth_fraction[1]);
  result.put("signalbf2", signal_bandwidth_fraction[2]);
  return result;
}
References mspass::algorithms::TimeWindow::end, mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::utility::Metadata::put(), mspass::algorithms::deconvolution::FFTDeconOperator::sample_shift, and mspass::algorithms::TimeWindow::start.
resolution_kernel()
mspass::seismic::TimeSeries mspass::algorithms::deconvolution::CNR3CDecon::resolution_kernel () inline
Alias for actual_output using inverse-theory terminology.
{
    return this->actual_output();
  }
References actual_output().
wavelet_noise_spectrum()
mspass::seismic::PowerSpectrum mspass::algorithms::deconvolution::CNR3CDecon::wavelet_noise_spectrum () inline
Return the power spectrum estimate linked to the wavelet signal.
{ return psnoise; };
wavelet_spectrum()
mspass::seismic::PowerSpectrum mspass::algorithms::deconvolution::CNR3CDecon::wavelet_spectrum () inline
Return the power spectrum of the wavelet signal used for deconvolution.
{ return pswavelet; };
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/cxx/include/mspass/algorithms/deconvolution/CNR3CDecon.h
/home/runner/work/mspass/mspass/cxx/src/lib/algorithms/deconvolution/CNR3CDecon.cc