MsPASS C++ API: mspass::algorithms::deconvolution::NoiseStableDecon Class Reference
mspass::algorithms::deconvolution::NoiseStableDecon Class Reference
Noise-aware stable FFT inverse used by NS-GID.
#include <NoiseStableDecon.h>
Public Member Functions
NoiseStableDecon (const mspass::utility::Metadata &md)
NoiseStableDecon (const mspass::utility::Metadata &md, const std::vector< double > &wavelet, const std::vector< double > &data)
void changeparameter (const mspass::utility::Metadata &md)
void process ()
void loadnoise (const std::vector< double > &noise)
void loadnoise (const mspass::seismic::CoreTimeSeries &noise)
void loadnoise (const mspass::seismic::PowerSpectrum &noise_spectrum)
mspass::seismic::CoreTimeSeries actual_output ()
Return the actual output of the deconvolution operator.
mspass::seismic::CoreTimeSeries inverse_wavelet (const double t0parent)
mspass::seismic::CoreTimeSeries inverse_wavelet ()
Return a FIR represention of the inverse filter.
mspass::utility::Metadata QCMetrics ()
Return appropriate quality measures.
double max_gain () const
double gain_cap () const
Public Member Functions inherited from mspass::algorithms::deconvolution::FFTDeconOperator
FFTDeconOperator (const mspass::utility::Metadata &md)
FFTDeconOperator (const FFTDeconOperator &parent)
FFTDeconOperator & operator= (const FFTDeconOperator &parent)
void changeparameter (const mspass::utility::Metadata &md)
void change_size (const int nfft_new)
void change_shift (const int shift)
int get_size ()
int get_shift ()
int operator_size ()
int operator_shift ()
double df (const double dt)
mspass::seismic::CoreTimeSeries FourierInverse (const ComplexArray &winv, const ComplexArray &sw, const double dt, const double t0parent)
Return inverse wavelet for Fourier methods.
Public Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
ScalarDecon (const mspass::utility::Metadata &md)
ScalarDecon (const std::vector< double > &d, const std::vector< double > &w)
ScalarDecon (const ScalarDecon &parent)
int load (const std::vector< double > &wavelet, const std::vector< double > &data)
Load all data required for decon.
int loaddata (const std::vector< double > &data)
int loadwavelet (const std::vector< double > &wavelet)
ScalarDecon & operator= (const ScalarDecon &parent)
std::vector< double > getresult ()
void changeparameter (const mspass::utility::Metadata &md)
void change_shaping_wavelet (const ShapingWavelet &nsw)
ShapingWavelet get_shaping_wavelet () const
virtual mspass::seismic::CoreTimeSeries output_shaping_wavelet ()
Return the output shaping wavelet.
mspass::seismic::CoreTimeSeries ideal_output ()
Legacy alias for output_shaping_wavelet.
mspass::seismic::CoreTimeSeries resolution_kernel ()
Alias for actual_output using inverse-theory terminology.
Additional Inherited Members
Protected Attributes inherited from mspass::algorithms::deconvolution::FFTDeconOperator
int nfft
int sample_shift
gsl_fft_complex_wavetable * wavetable
gsl_fft_complex_workspace * workspace
ComplexArray winv
Protected Attributes inherited from mspass::algorithms::deconvolution::ScalarDecon
std::vector< double > data
std::vector< double > wavelet
std::vector< double > result
ShapingWavelet shapingwavelet
Detailed Description
Noise-aware stable FFT inverse used by NS-GID.
This scalar operator computes
G(f)=B(f) conj(S(f))/(|S(f)|^2 + mu(f))
with frequency-dependent damping from an optional noise spectrum and an explicit gain cap. The minimum damping parameter is scaled by peak wavelet spectral power. It is intended as the inverse operator used to form the GID peak-picking function. As a standalone scalar deconvolution operator it applies one stable inverse filter and returns the finite-bandwidth result; it does not run sparse iteration and does not apply the GID output shaping wavelet.
Constructor & Destructor Documentation
NoiseStableDecon() [1/2]
mspass::algorithms::deconvolution::NoiseStableDecon::NoiseStableDecon ()
    : FFTDeconOperator(), ScalarDecon(), mu_min(3.0e-3), alpha(1.0),
      noise_floor(1.0e-12), gain_max(1.0e3), snr_taper_low(1.0),
      snr_taper_high(3.0), use_reliability_taper(false),
      noise_vector_loaded(false), noise_spectrum_loaded(false),
      processed(false), max_gain_actual(0.0), noise_amplification(0.0),
      effective_bandwidth_fraction(0.0) {}
NoiseStableDecon() [2/2]
mspass::algorithms::deconvolution::NoiseStableDecon::NoiseStableDecon (const mspass::utility::Metadata & md)
    : FFTDeconOperator(md), noise_vector_loaded(false),
      noise_spectrum_loaded(false), processed(false) {
  this->read_metadata(md);
}
Member Function Documentation
actual_output()
CoreTimeSeries mspass::algorithms::deconvolution::NoiseStableDecon::actual_output () virtual
Return the actual output of the deconvolution operator.
The actual output is defined as w^-1*w and is compable to resolution kernels in linear inverse theory. Although not required we would normally expect this function to be peaked at 0. Offsets from 0 would imply a bias.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  if (!processed || winv.size() <= 0)
    throw MsPASSError(
        "NoiseStableDecon::actual_output: process must be called first",
        ErrorSeverity::Invalid);
  vector<double> wavelet_padded(wavelet);
  if (wavelet_padded.size() < nfft)
    wavelet_padded.resize(nfft, 0.0);
  ComplexArray W(nfft, &(wavelet_padded[0]));
  gsl_fft_complex_forward(W.ptr(), 1, nfft, wavetable, workspace);
  ComplexArray ao_fft = winv * W;
  gsl_fft_complex_inverse(ao_fft.ptr(), 1, nfft, wavetable, workspace);
  vector<double> ao;
  ao.reserve(nfft);
  for (int k = 0; k < ao_fft.size(); ++k)
    ao.push_back(ao_fft[k].real());
  int i0 = nfft / 2;
  ao = circular_shift(ao, i0);
  CoreTimeSeries result(nfft);
  double dt = shapingwavelet.sample_interval();
  result.set_t0(-dt * static_cast<double>(i0));
  result.set_dt(dt);
  result.set_live();
  result.set_npts(nfft);
  result.set_tref(TimeReferenceType::Relative);
  for (int k = 0; k < nfft; ++k)
    result.s[k] = ao[k];
  result.s = normalize<double>(result.s);
  return result;
}
References mspass::seismic::CoreTimeSeries::s, mspass::seismic::CoreTimeSeries::set_dt(), mspass::seismic::BasicTimeSeries::set_live(), mspass::seismic::CoreTimeSeries::set_npts(), mspass::seismic::CoreTimeSeries::set_t0(), and mspass::seismic::BasicTimeSeries::set_tref().
changeparameter()
void mspass::algorithms::deconvolution::NoiseStableDecon::changeparameter (const mspass::utility::Metadata & md) virtual
Implements mspass::algorithms::deconvolution::BasicDeconOperator.
{
  this->read_metadata(md);
  result.clear();
  winv = ComplexArray();
  processed = false;
}
gain_cap()
double mspass::algorithms::deconvolution::NoiseStableDecon::gain_cap () const inline
{ return gain_max; }
inverse_wavelet() [1/2]
CoreTimeSeries mspass::algorithms::deconvolution::NoiseStableDecon::inverse_wavelet () virtual
Return a FIR represention of the inverse filter.
After any deconvolution is computed one can sometimes produce a finite impulse response (FIR) respresentation of the inverse filter.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  return this->inverse_wavelet(0.0);
}
inverse_wavelet() [2/2]
CoreTimeSeries mspass::algorithms::deconvolution::NoiseStableDecon::inverse_wavelet (const double t0parent) virtual
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  if (!processed || winv.size() <= 0)
    throw MsPASSError(
        "NoiseStableDecon::inverse_wavelet: process must be called first",
        ErrorSeverity::Invalid);
  double dt = shapingwavelet.sample_interval();
  ComplexArray no_shaping(nfft);
  for (int k = 0; k < nfft; ++k) {
    double *ptr = no_shaping.ptr(k);
    ptr[0] = 1.0;
    ptr[1] = 0.0;
  }
  return this->FourierInverse(winv, no_shaping, dt, t0parent);
}
loadnoise() [1/2]
void mspass::algorithms::deconvolution::NoiseStableDecon::loadnoise (const mspass::seismic::CoreTimeSeries & noise)
{
  this->loadnoise(noise_in.s);
}
loadnoise() [2/2]
void mspass::algorithms::deconvolution::NoiseStableDecon::loadnoise (const mspass::seismic::PowerSpectrum & noise_spectrum)
{
  ValidatePowerSpectrumCoversDC(noise_spectrum_in,
                                "NoiseStableDecon::loadnoise");
  noise_spectrum = noise_spectrum_in;
  noise_spectrum_loaded = true;
  noise_vector_loaded = false;
  result.clear();
  winv = ComplexArray();
  processed = false;
}
max_gain()
double mspass::algorithms::deconvolution::NoiseStableDecon::max_gain () const inline
{ return max_gain_actual; }
process()
void mspass::algorithms::deconvolution::NoiseStableDecon::process () virtual
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  const string base_error("NoiseStableDecon::process: ");
  result.clear();
  winv = ComplexArray();
  processed = false;
  const int output_length = data.size();
  if (output_length <= 0)
    throw MsPASSError(base_error + "no data loaded", ErrorSeverity::Invalid);
  if (wavelet.empty())
    throw MsPASSError(base_error + "no wavelet loaded", ErrorSeverity::Invalid);
  if (output_length > nfft || wavelet.size() > nfft)
    throw MsPASSError(base_error + "loaded vectors exceed padded FFT length",
                      ErrorSeverity::Invalid);
  vector<double> data_padded(data);
  data_padded.resize(nfft, 0.0);
  ComplexArray d_fft(nfft, &(data_padded[0]));
  gsl_fft_complex_forward(d_fft.ptr(), 1, nfft, wavetable, workspace);
  vector<double> wavelet_padded(wavelet);
  wavelet_padded.resize(nfft, 0.0);
  ComplexArray s_fft(nfft, &(wavelet_padded[0]));
  gsl_fft_complex_forward(s_fft.ptr(), 1, nfft, wavetable, workspace);
  if (s_fft.rms() <= 0.0)
    throw MsPASSError(base_error + "wavelet vector is all zeros",
                      ErrorSeverity::Invalid);
  const double dt = shapingwavelet.sample_interval();
  vector<double> pn = this->noise_power_spectrum(dt);
  winv = ComplexArray(nfft);
  max_gain_actual = 0.0;
  noise_amplification = 0.0;
  double spectral_power_peak = 0.0;
  for (int k = 0; k < nfft; ++k)
    spectral_power_peak = max(spectral_power_peak, norm(s_fft[k]));
  const double mu_floor = mu_min * spectral_power_peak;
  int usable_bins = 0;
  for (int k = 0; k < nfft; ++k) {
    Complex64 s = s_fft[k];
    double absS2 = norm(s);
    double absS = sqrt(absS2);
    double snr = absS2 / (pn[k] + noise_floor);
    double mu_noise = alpha * absS2 / (snr + 1.0e-12);
    double mu_gain = max(0.0, absS / gain_max - absS2);
    double mu = max({mu_floor, mu_noise, mu_gain});
    double b = this->reliability_taper(snr);
    Complex64 g(0.0, 0.0);
    if ((absS2 + mu) > 0.0)
      g = b * conj(s) / (absS2 + mu);
    double gain = abs(g);
    if (gain > gain_max) {
      g *= gain_max / gain;
      gain = gain_max;
    }
    double *ptr = winv.ptr(k);
    ptr[0] = g.real();
    ptr[1] = g.imag();
    max_gain_actual = max(max_gain_actual, gain);
    noise_amplification += gain * gain * pn[k];
    if (b > 0.0 && gain > 0.0)
      ++usable_bins;
  }
  noise_amplification = sqrt(noise_amplification / static_cast<double>(nfft));
  effective_bandwidth_fraction =
      static_cast<double>(usable_bins) / static_cast<double>(nfft);
  ComplexArray rf_fft = winv * d_fft;
  gsl_fft_complex_inverse(rf_fft.ptr(), 1, nfft, wavetable, workspace);
  result = ExtractLagWindow(rf_fft, output_length, sample_shift);
  processed = true;
}
QCMetrics()
Metadata mspass::algorithms::deconvolution::NoiseStableDecon::QCMetrics () virtual
Return appropriate quality measures.
Each operator commonly has different was to measure the quality of the result. This method should return these in a generic Metadata object.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  Metadata md;
  md.put("ns_gid_gain_max_requested", gain_max);
  md.put("ns_gid_gain_max_actual", max_gain_actual);
  md.put("ns_gid_mu_min", mu_min);
  md.put("ns_gid_alpha", alpha);
  md.put("ns_gid_noise_amplification", noise_amplification);
  md.put("ns_gid_effective_bandwidth_fraction",
         effective_bandwidth_fraction);
  md.put("ns_gid_operator_nfft", nfft);
  md.put("ns_gid_use_reliability_taper", use_reliability_taper);
  return md;
}
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/cxx/include/mspass/algorithms/deconvolution/NoiseStableDecon.h
/home/runner/work/mspass/mspass/cxx/src/lib/algorithms/deconvolution/NoiseStableDecon.cc