MsPASS C++ API: mspass::algorithms::deconvolution::MultiTaperSpecDivDecon Class Reference
mspass::algorithms::deconvolution::MultiTaperSpecDivDecon Class Reference
Multitaper power-stabilized spectral-division deconvolution.
#include <MultiTaperSpecDivDecon.h>
Public Member Functions
MultiTaperSpecDivDecon ()
MultiTaperSpecDivDecon (const mspass::utility::Metadata &md, const std::vector< double > &noise, const std::vector< double > &wavelet, const std::vector< double > &data)
Construct and load all multitaper inputs.
MultiTaperSpecDivDecon (const mspass::utility::Metadata &md)
Construct from metadata and reserve internal buffers.
MultiTaperSpecDivDecon (const MultiTaperSpecDivDecon &parent)
Copy constructor.
void changeparameter (const mspass::utility::Metadata &md)
Update operator parameters from a Metadata container.
int loadnoise (const std::vector< double > &noise)
Load a section of pre-event noise.
int load (const std::vector< double > &w, const std::vector< double > &d, const std::vector< double > &n)
Load wavelet, data, and noise vectors.
void process ()
Compute the combined multitaper spectral-division result.
mspass::seismic::CoreTimeSeries actual_output ()
Return the actual output of the deconvolution operator.
mspass::seismic::CoreTimeSeries inverse_wavelet (const double t0parent=0.0)
Return a FIR representation of the inverse filter.
mspass::seismic::CoreTimeSeries inverse_wavelet ()
Return default FIR representation of the inverse filter.
std::vector< mspass::seismic::CoreTimeSeries > all_inverse_wavelets (const double t0parent=0.0)
std::vector< mspass::seismic::CoreTimeSeries > all_rfestimates (const double t0parent=0.0)
std::vector< mspass::seismic::CoreTimeSeries > all_actual_outputs (const double t0parent=0.0)
mspass::utility::Metadata QCMetrics ()
Return appropriate quality measures.
int get_taperlen ()
int get_number_tapers ()
int get_number_outputs ()
double get_time_bandwidth_product ()
Public Member Functions inherited from mspass::algorithms::deconvolution::FFTDeconOperator
FFTDeconOperator ()
Construct an empty FFT operator shell.
FFTDeconOperator (const mspass::utility::Metadata &md)
Construct from deconvolution Metadata.
FFTDeconOperator (const FFTDeconOperator &parent)
Copy constructor.
~FFTDeconOperator ()
Release allocated GSL FFT work objects.
FFTDeconOperator & operator= (const FFTDeconOperator &parent)
Assign FFT size and lag shift from another operator.
void changeparameter (const mspass::utility::Metadata &md)
Reconfigure the FFT operator from Metadata.
void change_size (const int nfft_new)
Change the FFT work-buffer length.
void change_shift (const int shift)
Set the sample offset used to unwrap deconvolution lag windows.
int get_size ()
Return the current FFT work-buffer length.
int get_shift ()
Return the current deconvolution lag-window sample shift.
int operator_size ()
Return the current FFT work-buffer length.
int operator_shift ()
Return the current deconvolution lag-window sample shift.
double df (const double dt)
Return frequency spacing for the current FFT length.
mspass::seismic::CoreTimeSeries FourierInverse (const ComplexArray &winv, const ComplexArray &sw, const double dt, const double t0parent)
Return inverse wavelet for Fourier methods.
Public Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
ScalarDecon ()
Construct an empty scalar deconvolution operator.
ScalarDecon (const mspass::utility::Metadata &md)
Construct from Metadata.
ScalarDecon (const std::vector< double > &d, const std::vector< double > &w)
Construct with loaded data and source-wavelet vectors.
ScalarDecon (const ScalarDecon &parent)
Copy constructor preserving loaded vectors and shaping wavelet.
int load (const std::vector< double > &wavelet, const std::vector< double > &data)
Load all data required for decon.
int loaddata (const std::vector< double > &data)
int loadwavelet (const std::vector< double > &wavelet)
ScalarDecon & operator= (const ScalarDecon &parent)
Assign loaded wavelet, data, and result vectors from parent.
std::vector< double > getresult ()
Return the current deconvolution result vector.
void changeparameter (const mspass::utility::Metadata &md)
void change_shaping_wavelet (const ShapingWavelet &nsw)
ShapingWavelet get_shaping_wavelet () const
virtual mspass::seismic::CoreTimeSeries output_shaping_wavelet ()
Return the output shaping wavelet.
mspass::seismic::CoreTimeSeries ideal_output ()
Legacy alias for output_shaping_wavelet.
mspass::seismic::CoreTimeSeries resolution_kernel ()
Alias for actual_output using inverse-theory terminology.
Public Member Functions inherited from mspass::algorithms::deconvolution::BasicDeconOperator
virtual ~BasicDeconOperator ()
Additional Inherited Members
Protected Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
mspass::utility::Metadata BasicQCMetrics (const std::string &operator_name, const bool processed)
Build QC Metadata fields common to scalar deconvolution operators.
Protected Attributes inherited from mspass::algorithms::deconvolution::FFTDeconOperator
int nfft
Current FFT work-buffer length in samples.
int sample_shift
Sample offset used to place zero lag in deconvolution outputs.
gsl_fft_complex_wavetable * wavetable
GSL factorization table allocated for nfft.
gsl_fft_complex_workspace * workspace
GSL scratch workspace allocated for nfft.
ComplexArray winv
Frequency-domain inverse wavelet coefficients for derived operators.
Protected Attributes inherited from mspass::algorithms::deconvolution::ScalarDecon
std::vector< double > data
Data vector to be deconvolved by concrete scalar methods.
std::vector< double > wavelet
Source-wavelet estimate used by concrete scalar methods.
std::vector< double > result
Deconvolved output vector produced by process.
ShapingWavelet shapingwavelet
Output shaping wavelet applied by scalar deconvolution methods.
Detailed Description
Multitaper power-stabilized spectral-division deconvolution.
This legacy class name is retained for source and ABI compatibility. The current implementation is not a paper-faithful Park-Levin spectral-division estimator: it uses untapered source/data phase for the final inverse and uses multitaper source/noise spectra only to stabilize the power denominator.
Constructor & Destructor Documentation
MultiTaperSpecDivDecon() [1/4]
mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::MultiTaperSpecDivDecon () inline
Default constructor. Do not use - only for declarations
: FFTDeconOperator(), ScalarDecon() {};
MultiTaperSpecDivDecon() [2/4]
mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::MultiTaperSpecDivDecon (const mspass::utility::Metadata & md, const std::vector< double > & noise, const std::vector< double > & wavelet, const std::vector< double > & data)
Construct and load all multitaper inputs.
Parameters
md metadata defining FFT, shaping-wavelet, and DPSS taper parameters.
noise pre-event noise samples used for denominator stabilization.
wavelet source wavelet samples.
data data samples to deconvolve with the source wavelet.
{
  try {
    this->read_metadata(md, false);
  } catch (...) {
    throw;
  }
  this->load(wavelet, data, noise);
}
References mspass::algorithms::deconvolution::ScalarDecon::data, and load().
MultiTaperSpecDivDecon() [3/4]
mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::MultiTaperSpecDivDecon (const mspass::utility::Metadata & md)
Construct from metadata and reserve internal buffers.
Parameters
md metadata defining FFT, shaping-wavelet, and DPSS taper parameters.
    : FFTDeconOperator(md), ScalarDecon(md) {
  try {
    this->read_metadata(md, false);
  } catch (...) {
    throw;
  };
  /* assume tapers matrix is created in read_metadata.   We call reserve
  on the three stl vector containers for efficiency. */
  ScalarDecon::data.reserve(nfft);
  ScalarDecon::wavelet.reserve(nfft);
  noise.reserve(nfft);
}
References mspass::algorithms::deconvolution::ScalarDecon::data, mspass::algorithms::deconvolution::FFTDeconOperator::nfft, and mspass::algorithms::deconvolution::ScalarDecon::wavelet.
MultiTaperSpecDivDecon() [4/4]
mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::MultiTaperSpecDivDecon (const MultiTaperSpecDivDecon & parent)
Copy constructor.
Copies the configured taper set, loaded noise, and cached processed products.
    : FFTDeconOperator(parent), ScalarDecon(parent), noise(parent.noise),
      tapers(parent.tapers), winv_taper(parent.winv_taper),
      ao_fft(parent.ao_fft), rfestimates(parent.rfestimates) {
  nw = parent.nw;
  nseq = parent.nseq;
  damp = parent.damp;
  taperlen = parent.taperlen;
}
~MultiTaperSpecDivDecon()
mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::~MultiTaperSpecDivDecon () inline
{};
Member Function Documentation
actual_output()
CoreTimeSeries mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::actual_output () virtual
Return the actual output of the deconvolution operator.
The actual output/resolution kernel is defined as G(f)W0(f), where G is the combined multitaper-power-stabilized inverse and W0 is the untapered wavelet spectrum.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  try {
    if (ao_fft.empty())
      throw MsPASSError("MultiTaperSpecDivDecon::actual_output: process must "
                        "be called before actual_output",
                        ErrorSeverity::Invalid);
    int i, k;
    vector<double> ao;
    ao.reserve(nfft);
    for (k = 0; k < nfft; ++k)
      ao.push_back(0.0);
    for (i = 0; i < static_cast<int>(ao_fft.size()); ++i) {
      ComplexArray work(ao_fft[i]);
      work = (*shapingwavelet.wavelet()) * work;
      gsl_fft_complex_inverse(work.ptr(), 1, nfft, wavetable, workspace);
      for (k = 0; k < nfft; ++k)
        ao[k] += work[k].real();
    }
    double nrmscl = 1.0 / static_cast<double>(ao_fft.size());
    for (k = 0; k < nfft; ++k)
      ao[k] *= nrmscl;
    /* We always shift this wavelet to the center of the data vector.
    We handle the time through the CoreTimeSeries object. */
    int i0 = nfft / 2;
    ao = circular_shift(ao, i0);
    ao = normalize<double>(ao);
    CoreTimeSeries result(nfft);
    /* Getting dt from here is unquestionably a flaw in the api, but will
    retain for now.   Perhaps should a copy of dt in the ScalarDecon object. */
    double dt = this->shapingwavelet.sample_interval();
    /* t0 is time of sample zero - hence normally negative*/
    /* Old API
    result.t0=dt*(-(double)i0);
    result.dt=dt;
    result.live=true;
    result.tref=TimeReferenceType::Relative;
    result.s=ao;
    result.ns=nfft;
    */
    result.set_t0(dt * (-(double)i0));
    result.set_dt(dt);
    result.set_live();
    result.set_npts(nfft);
    result.set_tref(TimeReferenceType::Relative);
    for (k = 0; k < nfft; ++k)
      result.s[k] = ao[k];
    return result;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::algorithms::deconvolution::ComplexArray::ptr(), mspass::algorithms::deconvolution::ScalarDecon::result, mspass::algorithms::deconvolution::ShapingWavelet::sample_interval(), mspass::seismic::CoreTimeSeries::set_t0(), mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), mspass::algorithms::deconvolution::FFTDeconOperator::wavetable, and mspass::algorithms::deconvolution::FFTDeconOperator::workspace.
all_actual_outputs()
std::vector< CoreTimeSeries > mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::all_actual_outputs (const double t0parent = 0.0)
Return actual outputs retained for API compatibility.
The current implementation normally returns one combined actual output.
{
  try {
    if (ao_fft.empty())
      throw MsPASSError("MultiTaperSpecDivDecon::all_actual_outputs: process "
                        "must be called before all_actual_outputs",
                        ErrorSeverity::Invalid);
    std::vector<CoreTimeSeries> all;
    all.reserve(ao_fft.size());
    double dt = this->shapingwavelet.sample_interval();
    for (int i = 0; i < static_cast<int>(ao_fft.size()); ++i) {
      /* Although this method of FFTDeconOperator was originally
       * written to return inverse wavelet, it can work in this
       * context too */
      CoreTimeSeries work(this->FFTDeconOperator::FourierInverse(
          this->ao_fft[i], *shapingwavelet.wavelet(), dt, t0parent));
      all.push_back(work);
    }
    return all;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::FourierInverse(), mspass::algorithms::deconvolution::ShapingWavelet::sample_interval(), mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, and mspass::algorithms::deconvolution::ShapingWavelet::wavelet().
all_inverse_wavelets()
std::vector< CoreTimeSeries > mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::all_inverse_wavelets (const double t0parent = 0.0)
Return inverse wavelets retained for API compatibility.
The current implementation normally returns one combined multitaper inverse, not independent per-taper inverse wavelets.
{
  try {
    if (winv_taper.empty())
      throw MsPASSError("MultiTaperSpecDivDecon::all_inverse_wavelets: "
                        "process must be called before all_inverse_wavelets",
                        ErrorSeverity::Invalid);
    std::vector<CoreTimeSeries> all;
    all.reserve(winv_taper.size());
    double dt = this->shapingwavelet.sample_interval();
    for (int i = 0; i < static_cast<int>(winv_taper.size()); ++i) {
      CoreTimeSeries work(this->FFTDeconOperator::FourierInverse(
          this->winv_taper[i], *shapingwavelet.wavelet(), dt, t0parent));
      all.push_back(work);
    }
    return all;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::FourierInverse(), mspass::algorithms::deconvolution::ShapingWavelet::sample_interval(), mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, and mspass::algorithms::deconvolution::ShapingWavelet::wavelet().
all_rfestimates()
std::vector< CoreTimeSeries > mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::all_rfestimates (const double t0parent = 0.0)
Return RF estimates retained for API compatibility.
The current implementation normally returns one combined RF estimate.
{
  try {
    if (rfestimates.empty())
      throw MsPASSError("MultiTaperSpecDivDecon::all_rfestimates: process "
                        "must be called before all_rfestimates",
                        ErrorSeverity::Invalid);
    std::vector<CoreTimeSeries> all;
    all.reserve(rfestimates.size());
    double dt = this->shapingwavelet.sample_interval();
    for (int i = 0; i < static_cast<int>(rfestimates.size()); ++i) {
      /* Although this method of FFTDeconOperator was originally
       * written to return inverse wavelet, it can work in this
       * context too */
      CoreTimeSeries work(this->FFTDeconOperator::FourierInverse(
          this->rfestimates[i], *shapingwavelet.wavelet(), dt, t0parent));
      all.push_back(work);
    }
    return all;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::FourierInverse(), mspass::algorithms::deconvolution::ShapingWavelet::sample_interval(), mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, and mspass::algorithms::deconvolution::ShapingWavelet::wavelet().
changeparameter()
void mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::changeparameter (const mspass::utility::Metadata & md) inline virtual
Update operator parameters from a Metadata container.
Implements mspass::algorithms::deconvolution::BasicDeconOperator.
{
    this->read_metadata(md, true);
    this->result.clear();
    this->winv = ComplexArray();
    this->winv_taper.clear();
    this->ao_fft.clear();
    this->rfestimates.clear();
  };
References mspass::algorithms::deconvolution::ScalarDecon::result, and mspass::algorithms::deconvolution::FFTDeconOperator::winv.
get_number_outputs()
int mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::get_number_outputs () inline
Return the number of combined inverse/RF/AO products stored after process.
The value is normally 1 after a successful process call and 0 before process.
{ return winv_taper.size(); };
get_number_tapers()
int mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::get_number_tapers () inline
Return the number of DPSS tapers used to build the combined denominator.
This is intentionally different from get_number_outputs(). The current implementation combines the multitaper powers before forming one inverse operator, so processed products normally contain one combined output.
{ return nseq; };
get_taperlen()
int mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::get_taperlen () inline
Return the configured DPSS taper length in samples.
{ return taperlen; };
get_time_bandwidth_product()
double mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::get_time_bandwidth_product () inline
Return the DPSS time-bandwidth product used to generate tapers.
{ return nw; };
inverse_wavelet() [1/2]
CoreTimeSeries mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::inverse_wavelet () virtual
Return default FIR representation of the inverse filter.
This is an overloaded version of the parameterized method. It is equivalent to this->inverse_wavelet(0.0);
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  try {
    return this->inverse_wavelet(0.0);
  } catch (...) {
    throw;
  };
}
References inverse_wavelet().
inverse_wavelet() [2/2]
CoreTimeSeries mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::inverse_wavelet (const double t0parent = 0.0) virtual
Return a FIR representation of the inverse filter.
An inverse filter has an impulse response. For some wavelets this can be represented by a FIR filter with finite numbers of coefficients. Since this is a Fourier method this method returns the inverse FFT of the regularized operator. The output usually needs to be phase shifted to be most useful. For typical seismic source wavelets that are approximately minimum phase the shift can be small, but for zero phase input it should be approximately half the window size. This method also has an optional argument for t0parent. Because this processor was written to be agnostic about a time standard it implicitly assumes time 0 is sample 0 of the input waveforms. If the original data have a nonzero start time this should be passed as t0parent or the output will contain a time shift of t0parent. Note that tshift and t0parent do very different things. tshift is used to apply circular phase shift to the output (e.g. a shift of 10 samples causes the last 10 samples in the wavelet to be wrapped to the first 10 samples). t0parent only changes the time standard so the output has t0 -= parent.t0.
Output wavelet is always circular shifted with 0 lag at center.
Parameters
t0parent - time zero of parent seismograms (see above).
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  try {
    /* Getting dt from here is unquestionably a flaw in the api, but will
     *         retain for now.   Perhaps should a copy of dt in the ScalarDecon
     * object. */
    double dt = this->shapingwavelet.sample_interval();
    /* algorithm assumes this data vector in result is initialized to nfft zeros
     */
    CoreTimeSeries result(this->nfft);
    if (winv_taper.empty())
      throw MsPASSError("MultiTaperSpecDivDecon::inverse_wavelet: process must "
                        "be called before inverse_wavelet",
                        ErrorSeverity::Invalid);
    for (int i = 0; i < static_cast<int>(winv_taper.size()); ++i) {
      CoreTimeSeries work(this->FFTDeconOperator::FourierInverse(
          this->winv_taper[i], *shapingwavelet.wavelet(), dt, t0parent));
      if (i == 0)
        result = work;
      else
        result += work;
    }
    double nrmscal = 1.0 / static_cast<double>(winv_taper.size());
    for (int k = 0; k < result.s.size(); ++k)
      result.s[k] *= nrmscal;
    return result;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::FourierInverse(), mspass::algorithms::deconvolution::ScalarDecon::result, mspass::seismic::CoreTimeSeries::s, mspass::algorithms::deconvolution::ShapingWavelet::sample_interval(), mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, and mspass::algorithms::deconvolution::ShapingWavelet::wavelet().
load()
int mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::load (const std::vector< double > & w, const std::vector< double > & d, const std::vector< double > & n)
Load wavelet, data, and noise vectors.
Parameters
w wavelet/source data
d data to be deconvolved with w
n noise vector used for regularization
{
  try {
    const string base_error("MultiTaperSpecDivDecon::load: ");
    if (w.size() > taperlen || d.size() > taperlen)
      throw MsPASSError(
          base_error +
              "wavelet/data vectors are longer than taperlen; multitaper "
              "inputs must not exceed the configured taper length",
          ErrorSeverity::Invalid);
    int lnr = this->loadnoise(n);
    int ldr;
    ldr = this->ScalarDecon::load(w, d);
    return (lnr + ldr);
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::ScalarDecon::load(), and loadnoise().
loadnoise()
int mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::loadnoise (const std::vector< double > & noise)
Load a section of pre-event noise.
The multitaper algorithm uses pre-event noise to compute frequency-dependent power-domain regularization. This method loads the noise data but does not initiate computation.
{
  const string base_error("MultiTaperSpecDivDecon::loadnoise: ");
  if (n.empty())
    throw MsPASSError(base_error + "noise vector cannot be empty",
                      ErrorSeverity::Invalid);
  if (n.size() > taperlen)
    throw MsPASSError(base_error +
                          "noise vector is longer than taperlen; multitaper "
                          "inputs must not exceed the configured taper length",
                      ErrorSeverity::Invalid);
  /* For this implementation we insist n be the same length
   * as d (assumed taperlen) to avoid constant recomputing slepians. */
  if (n.size() == taperlen)
    noise = n;
  else {
    int nn = n.size();
    int k;
    noise.clear();
    for (k = 0; k < static_cast<int>(taperlen); ++k)
      noise.push_back(0.0);
    /* This zero pads noise on the right when input series length is short. */
    for (k = 0; k < nn; ++k)
      noise[k] = n[k];
  }
  return 0;
}
process()
void mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::process () virtual
Compute the combined multitaper spectral-division result.
The method uses multitaper wavelet and noise power to stabilize the denominator, then applies the inverse to the untapered data spectrum.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  const string base_error("MultiTaperSpecDivDecon::process():  ");
  result.clear();
  winv = ComplexArray();
  rfestimates.clear();
  winv_taper.clear();
  ao_fft.clear();
  try {
    const int output_length = data.size();
    if (output_length > nfft)
      throw MsPASSError(base_error + "data vector exceeds padded fft length",
                        ErrorSeverity::Invalid);
    /* WARNING about this algorithm. At present there is nothing to stop
    a coding error of calling the algorithm with inconsistent signal and
    noise data vectors. */
    if (noise.size() <= 0) {
      throw MsPASSError(base_error + "noise data is empty.",
                        ErrorSeverity::Invalid);
    }
    if (wavelet.size() > taperlen || data.size() > taperlen ||
        noise.size() > taperlen)
      throw MsPASSError(base_error +
                            "wavelet, data, and noise vectors must not exceed "
                            "the configured taper length",
                        ErrorSeverity::Invalid);
    /* Tapered wavelet/noise spectra are used only to estimate a stable
    source-power denominator.  The final inverse uses the untapered source
    phase and is applied to the untapered, zero-padded data window. */
    int i, j;
    vector<ComplexArray> wdata;
    wdata = taper_data(wavelet);
    for (i = 0; i < nseq; ++i) {
      gsl_fft_complex_forward(wdata[i].ptr(), 1, nfft, wavetable, workspace);
    }
    vector<ComplexArray> ndata;
    ndata = taper_data(noise);
    for (i = 0; i < nseq; ++i) {
      gsl_fft_complex_forward(ndata[i].ptr(), 1, nfft, wavetable, workspace);
    }
    double max_source_power(0.0);
    for (i = 0; i < nseq; ++i) {
      for (j = 0; j < nfft; ++j) {
        double *zw = wdata[i].ptr(j);
        double swp = (*zw) * (*zw) + (*(zw + 1)) * (*(zw + 1));
        if (swp > max_source_power)
          max_source_power = swp;
      }
    }
    const double relative_floor = max(DBL_EPSILON, 1.0e-12 * max_source_power);
    vector<double> source_power_denominator(nfft, 0.0);
    for (i = 0; i < nseq; ++i) {
      for (j = 0; j < nfft; ++j) {
        double *zw = wdata[i].ptr(j);
        const double source_power =
            (*zw) * (*zw) + (*(zw + 1)) * (*(zw + 1));
        double *zn = ndata[i].ptr(j);
        const double noise_power =
            (*zn) * (*zn) + (*(zn + 1)) * (*(zn + 1));
        double regularized_power = max(source_power, damp * noise_power);
        regularized_power = max(regularized_power, relative_floor);
        source_power_denominator[j] +=
            regularized_power / static_cast<double>(nseq);
      }
    }
    vector<double> padded_data(nfft, 0.0);
    vector<double> padded_wavelet(nfft, 0.0);
    int ndcopy = std::min(static_cast<int>(data.size()), nfft);
    int nwcopy = std::min(static_cast<int>(wavelet.size()), nfft);
    for (i = 0; i < ndcopy; ++i)
      padded_data[i] = data[i];
    for (i = 0; i < nwcopy; ++i)
      padded_wavelet[i] = wavelet[i];
    ComplexArray untapered_data(nfft, padded_data);
    ComplexArray untapered_wavelet(nfft, padded_wavelet);
    gsl_fft_complex_forward(untapered_data.ptr(), 1, nfft, wavetable,
                            workspace);
    gsl_fft_complex_forward(untapered_wavelet.ptr(), 1, nfft, wavetable,
                            workspace);
    ComplexArray inv(untapered_wavelet);
    inv.conj();
    for (j = 0; j < nfft; ++j) {
      double *zinv = inv.ptr(j);
      (*zinv) /= source_power_denominator[j];
      (*(zinv + 1)) /= source_power_denominator[j];
    }
    vector<ComplexArray> winv_taper_work;
    vector<ComplexArray> rfestimates_work;
    vector<ComplexArray> ao_fft_work;
    winv_taper_work.push_back(inv);
    ComplexArray rfwork(inv);
    rfwork = rfwork * untapered_data;
    rfestimates_work.push_back(rfwork);
    ComplexArray aowork(inv);
    aowork = aowork * untapered_wavelet;
    ao_fft_work.push_back(aowork);
    vector<double> ao_scale(nfft, 0.0);
    for (i = 0; i < static_cast<int>(ao_fft_work.size()); ++i) {
      ComplexArray work(ao_fft_work[i]);
      work = (*shapingwavelet.wavelet()) * work;
      gsl_fft_complex_inverse(work.ptr(), 1, nfft, wavetable, workspace);
      for (j = 0; j < nfft; ++j)
        ao_scale[j] += work[j].real();
    }
    double ao_nrmscl = 1.0 / static_cast<double>(ao_fft_work.size());
    for (j = 0; j < nfft; ++j)
      ao_scale[j] *= ao_nrmscl;
    ComplexArray ao_work(nfft, ao_scale);
    vector<double> ao_lag = ExtractLagWindow(ao_work, output_length, sample_shift);
    if (sample_shift < 0 || sample_shift >= static_cast<int>(ao_lag.size()))
      throw MsPASSError(base_error +
                            "zero-lag sample is outside extracted lag window",
                        ErrorSeverity::Invalid);
    double ao_peak = ao_lag[sample_shift];
    if (fabs(ao_peak) <= 0.0)
      throw MsPASSError(base_error + "actual output has zero peak",
                        ErrorSeverity::Invalid);
    for (i = 0; i < static_cast<int>(rfestimates_work.size()); ++i) {
      for (j = 0; j < nfft; ++j) {
        double *zrf = rfestimates_work[i].ptr(j);
        (*zrf) /= ao_peak;
        (*(zrf + 1)) /= ao_peak;
        double *zw = winv_taper_work[i].ptr(j);
        (*zw) /= ao_peak;
        (*(zw + 1)) /= ao_peak;
        double *zao = ao_fft_work[i].ptr(j);
        (*zao) /= ao_peak;
        (*(zao + 1)) /= ao_peak;
      }
    }
    /* To mesh with the API of other methods we now compute the average
    rf estimate.  We compute this as a simple average in the padded work
    buffer, then extract the requested lag window. */
    vector<double> padded_result(nfft, 0.0);
    vector<double> wtmp;
    for (i = 0; i < static_cast<int>(rfestimates_work.size()); ++i) {
      ComplexArray work(rfestimates_work[i]);
      /* We always apply the shaping wavelet to the rf estimate.  We do it
      here before averaging. */
      work = (*shapingwavelet.wavelet()) * work;
      gsl_fft_complex_inverse(work.ptr(), 1, nfft, wavetable, workspace);
      for (j = 0; j < nfft; ++j) {
        padded_result[j] += work[j].real();
      }
    }
    double nrmscl = 1.0 / static_cast<double>(rfestimates_work.size());
    for (j = 0; j < nfft; ++j)
      padded_result[j] *= nrmscl;
    ComplexArray rf_work(nfft, padded_result);
    result = ExtractLagWindow(rf_work, output_length, sample_shift);
    winv = winv_taper_work[0];
    winv_taper = winv_taper_work;
    rfestimates = rfestimates_work;
    ao_fft = ao_fft_work;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::ComplexArray::conj(), mspass::algorithms::deconvolution::ScalarDecon::data, mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::algorithms::deconvolution::ComplexArray::ptr(), mspass::algorithms::deconvolution::ScalarDecon::result, mspass::algorithms::deconvolution::FFTDeconOperator::sample_shift, mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, mspass::algorithms::deconvolution::ScalarDecon::wavelet, mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), mspass::algorithms::deconvolution::FFTDeconOperator::wavetable, mspass::algorithms::deconvolution::FFTDeconOperator::winv, and mspass::algorithms::deconvolution::FFTDeconOperator::workspace.
QCMetrics()
Metadata mspass::algorithms::deconvolution::MultiTaperSpecDivDecon::QCMetrics () virtual
Return appropriate quality measures.
Each operator commonly has different ways to measure the quality of the result. This method should return these in a generic Metadata object.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  const bool did_process(!winv_taper.empty());
  Metadata md(this->BasicQCMetrics("MultiTaperSpecDivDecon", did_process));
  md.put("multitaper_operator_type", string("specdiv_power_stabilized"));
  md.put("multitaper_operator_nfft", nfft);
  md.put("decon_operator_nfft", nfft);
  md.put("decon_operator_sample_shift", sample_shift);
  md.put("multitaper_taper_length", static_cast<int>(taperlen));
  md.put("multitaper_number_tapers", nseq);
  md.put("multitaper_time_bandwidth_product", nw);
  md.put("multitaper_damping_factor", damp);
  md.put("multitaper_processed", did_process);
  md.put("multitaper_number_outputs", static_cast<int>(winv_taper.size()));
  return md;
}
References mspass::algorithms::deconvolution::ScalarDecon::BasicQCMetrics(), mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::utility::Metadata::put(), and mspass::algorithms::deconvolution::FFTDeconOperator::sample_shift.
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/cxx/include/mspass/algorithms/deconvolution/MultiTaperSpecDivDecon.h
/home/runner/work/mspass/mspass/cxx/src/lib/algorithms/deconvolution/MultiTaperSpecDivDecon.cc