MsPASS C++ API: mspass::algorithms::deconvolution::MultiTaperXcorDecon Class Reference
mspass::algorithms::deconvolution::MultiTaperXcorDecon Class Reference
Multitaper source-power-stabilized deconvolution.
#include <MultiTaperXcorDecon.h>
Public Member Functions
MultiTaperXcorDecon ()
MultiTaperXcorDecon (const mspass::utility::Metadata &md, const std::vector< double > &noise, const std::vector< double > &wavelet, const std::vector< double > &data)
Construct and load all multitaper inputs.
MultiTaperXcorDecon (const mspass::utility::Metadata &md)
Construct from metadata and reserve internal buffers.
MultiTaperXcorDecon (const MultiTaperXcorDecon &parent)
Copy constructor.
void changeparameter (const mspass::utility::Metadata &md)
Update operator parameters from a Metadata container.
int loadnoise (const std::vector< double > &noise)
Load a section of pre-event noise.
int load (const std::vector< double > &w, const std::vector< double > &d, const std::vector< double > &n)
Load wavelet, data, and noise vectors.
void process ()
Compute the multitaper cross-correlation deconvolution result.
mspass::seismic::CoreTimeSeries actual_output ()
Return the actual output of the deconvolution operator.
mspass::seismic::CoreTimeSeries inverse_wavelet (const double t0parent=0.0)
Return a FIR representation of the inverse filter.
mspass::seismic::CoreTimeSeries inverse_wavelet ()
Return default FIR representation of the inverse filter.
mspass::utility::Metadata QCMetrics ()
Return appropriate quality measures.
int get_taperlen ()
int get_number_tapers ()
double get_time_bandwidth_product ()
Public Member Functions inherited from mspass::algorithms::deconvolution::FFTDeconOperator
FFTDeconOperator ()
Construct an empty FFT operator shell.
FFTDeconOperator (const mspass::utility::Metadata &md)
Construct from deconvolution Metadata.
FFTDeconOperator (const FFTDeconOperator &parent)
Copy constructor.
~FFTDeconOperator ()
Release allocated GSL FFT work objects.
FFTDeconOperator & operator= (const FFTDeconOperator &parent)
Assign FFT size and lag shift from another operator.
void changeparameter (const mspass::utility::Metadata &md)
Reconfigure the FFT operator from Metadata.
void change_size (const int nfft_new)
Change the FFT work-buffer length.
void change_shift (const int shift)
Set the sample offset used to unwrap deconvolution lag windows.
int get_size ()
Return the current FFT work-buffer length.
int get_shift ()
Return the current deconvolution lag-window sample shift.
int operator_size ()
Return the current FFT work-buffer length.
int operator_shift ()
Return the current deconvolution lag-window sample shift.
double df (const double dt)
Return frequency spacing for the current FFT length.
mspass::seismic::CoreTimeSeries FourierInverse (const ComplexArray &winv, const ComplexArray &sw, const double dt, const double t0parent)
Return inverse wavelet for Fourier methods.
Public Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
ScalarDecon ()
Construct an empty scalar deconvolution operator.
ScalarDecon (const mspass::utility::Metadata &md)
Construct from Metadata.
ScalarDecon (const std::vector< double > &d, const std::vector< double > &w)
Construct with loaded data and source-wavelet vectors.
ScalarDecon (const ScalarDecon &parent)
Copy constructor preserving loaded vectors and shaping wavelet.
int load (const std::vector< double > &wavelet, const std::vector< double > &data)
Load all data required for decon.
int loaddata (const std::vector< double > &data)
int loadwavelet (const std::vector< double > &wavelet)
ScalarDecon & operator= (const ScalarDecon &parent)
Assign loaded wavelet, data, and result vectors from parent.
std::vector< double > getresult ()
Return the current deconvolution result vector.
void changeparameter (const mspass::utility::Metadata &md)
void change_shaping_wavelet (const ShapingWavelet &nsw)
ShapingWavelet get_shaping_wavelet () const
virtual mspass::seismic::CoreTimeSeries output_shaping_wavelet ()
Return the output shaping wavelet.
mspass::seismic::CoreTimeSeries ideal_output ()
Legacy alias for output_shaping_wavelet.
mspass::seismic::CoreTimeSeries resolution_kernel ()
Alias for actual_output using inverse-theory terminology.
Public Member Functions inherited from mspass::algorithms::deconvolution::BasicDeconOperator
virtual ~BasicDeconOperator ()
Additional Inherited Members
Protected Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
mspass::utility::Metadata BasicQCMetrics (const std::string &operator_name, const bool processed)
Build QC Metadata fields common to scalar deconvolution operators.
Protected Attributes inherited from mspass::algorithms::deconvolution::FFTDeconOperator
int nfft
Current FFT work-buffer length in samples.
int sample_shift
Sample offset used to place zero lag in deconvolution outputs.
gsl_fft_complex_wavetable * wavetable
GSL factorization table allocated for nfft.
gsl_fft_complex_workspace * workspace
GSL scratch workspace allocated for nfft.
ComplexArray winv
Frequency-domain inverse wavelet coefficients for derived operators.
Protected Attributes inherited from mspass::algorithms::deconvolution::ScalarDecon
std::vector< double > data
Data vector to be deconvolved by concrete scalar methods.
std::vector< double > wavelet
Source-wavelet estimate used by concrete scalar methods.
std::vector< double > result
Deconvolved output vector produced by process.
ShapingWavelet shapingwavelet
Output shaping wavelet applied by scalar deconvolution methods.
Detailed Description
Multitaper source-power-stabilized deconvolution.
This legacy class name is retained for source and ABI compatibility. The current implementation is not a paper-faithful Park-Levin MTC estimator: it uses untapered source/data phase for the final inverse and uses multitaper source/noise spectra only to stabilize the power denominator.
Constructor & Destructor Documentation
MultiTaperXcorDecon() [1/4]
mspass::algorithms::deconvolution::MultiTaperXcorDecon::MultiTaperXcorDecon () inline
Default constructor. Do not use except for declarations.
: FFTDeconOperator(), ScalarDecon() {};
MultiTaperXcorDecon() [2/4]
mspass::algorithms::deconvolution::MultiTaperXcorDecon::MultiTaperXcorDecon (const mspass::utility::Metadata & md, const std::vector< double > & noise, const std::vector< double > & wavelet, const std::vector< double > & data)
Construct and load all multitaper inputs.
Parameters
md metadata defining FFT, shaping-wavelet, and DPSS taper parameters.
noise pre-event noise samples used for denominator stabilization.
wavelet source wavelet samples.
data data samples to deconvolve with the source wavelet.
{
  try {
    this->read_metadata(md, false);
  } catch (...) {
    throw;
  }
  this->load(wavelet, data, noise);
}
References mspass::algorithms::deconvolution::ScalarDecon::data, and load().
MultiTaperXcorDecon() [3/4]
mspass::algorithms::deconvolution::MultiTaperXcorDecon::MultiTaperXcorDecon (const mspass::utility::Metadata & md)
Construct from metadata and reserve internal buffers.
Parameters
md metadata defining FFT, shaping-wavelet, and DPSS taper parameters.
    : FFTDeconOperator(md) {
  try {
    this->read_metadata(md, false);
  } catch (...) {
    throw;
  };
  /* assume tapers matrix is created in read_metadata.   We call reserve
  on the three stl vector containers for efficiency. */
  data.reserve(nfft);
  wavelet.reserve(nfft);
  noise.reserve(nfft);
}
References mspass::algorithms::deconvolution::ScalarDecon::data, mspass::algorithms::deconvolution::FFTDeconOperator::nfft, and mspass::algorithms::deconvolution::ScalarDecon::wavelet.
MultiTaperXcorDecon() [4/4]
mspass::algorithms::deconvolution::MultiTaperXcorDecon::MultiTaperXcorDecon (const MultiTaperXcorDecon & parent)
Copy constructor.
Copies the configured taper set, loaded noise, and cached actual-output spectrum.
    : FFTDeconOperator(parent), ScalarDecon(parent), noise(parent.noise),
      tapers(parent.tapers), ao_fft(parent.ao_fft) {
  /* multitaper parameters to copy */
  nw = parent.nw;
  nseq = parent.nseq;
  taperlen = parent.taperlen;
  damp = parent.damp;
}
~MultiTaperXcorDecon()
mspass::algorithms::deconvolution::MultiTaperXcorDecon::~MultiTaperXcorDecon () inline
{};
Member Function Documentation
actual_output()
CoreTimeSeries mspass::algorithms::deconvolution::MultiTaperXcorDecon::actual_output () virtual
Return the actual output of the deconvolution operator.
The actual output/resolution kernel is defined as G(f)W0(f), where G is the untapered-phase inverse and W0 is the untapered wavelet spectrum. The denominator of G is stabilized by multitaper source power and damped multitaper noise power.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  try {
    if (ao_fft.size() <= 0)
      throw MsPASSError("MultiTaperXcorDecon::actual_output: process must "
                        "be called before actual_output",
                        ErrorSeverity::Invalid);
    /* The ao_fft array contains the fft of the actual output/resolution kernel.
     * We do need to appy the shaping wavelet for consistency before
     * converting it to the time domain.*/
    ComplexArray work(ao_fft);
    work = (*shapingwavelet.wavelet()) * work;
    gsl_fft_complex_inverse(work.ptr(), 1, nfft, wavetable, workspace);
    vector<double> ao;
    ao.reserve(nfft);
    for (int k = 0; k < work.size(); ++k)
      ao.push_back(work[k].real());
    /* We always shift this wavelet to the center of the data vector.
    We handle the time through the CoreTimeSeries object. */
    int i0 = nfft / 2;
    ao = circular_shift(ao, i0);
    ao = normalize<double>(ao);
    CoreTimeSeries result(nfft);
    /* Getting dt from here is unquestionably a flaw in the api, but will
    retain for now.   Perhaps should a copy of dt in the ScalarDecon object. */
    double dt = this->shapingwavelet.sample_interval();
    result.set_t0(dt * (-(double)i0));
    result.set_dt(dt);
    result.set_live();
    result.set_tref(TimeReferenceType::Relative);
    result.set_npts(nfft);
    for (int k = 0; k < nfft; ++k)
      result.s[k] = ao[k];
    return result;
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::algorithms::deconvolution::ComplexArray::ptr(), mspass::algorithms::deconvolution::ScalarDecon::result, mspass::algorithms::deconvolution::ShapingWavelet::sample_interval(), mspass::seismic::CoreTimeSeries::set_t0(), mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, mspass::algorithms::deconvolution::ComplexArray::size(), mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), mspass::algorithms::deconvolution::FFTDeconOperator::wavetable, and mspass::algorithms::deconvolution::FFTDeconOperator::workspace.
changeparameter()
void mspass::algorithms::deconvolution::MultiTaperXcorDecon::changeparameter (const mspass::utility::Metadata & md) inline virtual
Update operator parameters from a Metadata container.
Implements mspass::algorithms::deconvolution::BasicDeconOperator.
{
    this->read_metadata(md, true);
    this->result.clear();
    this->winv = ComplexArray();
    this->ao_fft = ComplexArray();
  };
References mspass::algorithms::deconvolution::ScalarDecon::result, and mspass::algorithms::deconvolution::FFTDeconOperator::winv.
get_number_tapers()
int mspass::algorithms::deconvolution::MultiTaperXcorDecon::get_number_tapers () inline
Return the number of DPSS tapers used by the operator.
{ return nseq; };
get_taperlen()
int mspass::algorithms::deconvolution::MultiTaperXcorDecon::get_taperlen () inline
Return the configured DPSS taper length in samples.
{ return taperlen; };
get_time_bandwidth_product()
double mspass::algorithms::deconvolution::MultiTaperXcorDecon::get_time_bandwidth_product () inline
Return the DPSS time-bandwidth product used to generate tapers.
{ return nw; };
inverse_wavelet() [1/2]
CoreTimeSeries mspass::algorithms::deconvolution::MultiTaperXcorDecon::inverse_wavelet () virtual
Return default FIR representation of the inverse filter.
This is an overloaded version of the parameterized method. It is equivalent to this->inverse_wavelet(0.0);
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  try {
    return this->inverse_wavelet(0.0);
  } catch (...) {
    throw;
  };
}
References inverse_wavelet().
inverse_wavelet() [2/2]
CoreTimeSeries mspass::algorithms::deconvolution::MultiTaperXcorDecon::inverse_wavelet (const double t0parent = 0.0) virtual
Return a FIR representation of the inverse filter.
An inverse filter has an impulse response. For some wavelets this can be represented by a FIR filter with finite numbers of coefficients. Since this is a Fourier method this method returns the inverse FFT of the regularized operator. The output usually needs to be phase shifted to be most useful. For typical seismic source wavelets that are approximately minimum phase the shift can be small, but for zero phase input it should be approximately half the window size. This method also has an optional argument for t0parent. Because this processor was written to be agnostic about a time standard it implicitly assumes time 0 is sample 0 of the input waveforms. If the original data have a nonzero start time this should be passed as t0parent or the output will contain a time shift of t0parent. Note that tshift and t0parent do very different things. tshift is used to apply circular phase shift to the output (e.g. a shift of 10 samples causes the last 10 samples in the wavelet to be wrapped to the first 10 samples). t0parent only changes the time standard so the output has t0 -= parent.t0.
Output wavelet is always circular shifted with 0 lag at center.
Parameters
t0parent - time zero of parent seismograms (see above).
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  try {
    if (winv.size() <= 0)
      throw MsPASSError("MultiTaperXcorDecon::inverse_wavelet: process must "
                        "be called before inverse_wavelet",
                        ErrorSeverity::Invalid);
    /* Getting dt from here is unquestionably a flaw in the api, but will
     *         retain for now.   Perhaps should a copy of dt in the ScalarDecon
     * object. */
    double dt = this->shapingwavelet.sample_interval();
    return (this->FFTDeconOperator::FourierInverse(
        this->winv, *shapingwavelet.wavelet(), dt, t0parent));
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::FFTDeconOperator::FourierInverse(), mspass::algorithms::deconvolution::ShapingWavelet::sample_interval(), mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, mspass::algorithms::deconvolution::ComplexArray::size(), mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), and mspass::algorithms::deconvolution::FFTDeconOperator::winv.
load()
int mspass::algorithms::deconvolution::MultiTaperXcorDecon::load (const std::vector< double > & w, const std::vector< double > & d, const std::vector< double > & n)
Load wavelet, data, and noise vectors.
Parameters
w wavelet/source data
d data to be deconvolved with w
n noise vector used for regularization
{
  try {
    const string base_error("MultiTaperXcorDecon::load: ");
    if (w.size() > taperlen || d.size() > taperlen)
      throw MsPASSError(
          base_error +
              "wavelet/data vectors are longer than taperlen; multitaper "
              "inputs must not exceed the configured taper length",
          ErrorSeverity::Invalid);
    int lnr = this->loadnoise(n);
    int ldr;
    ldr = this->ScalarDecon::load(w, d);
    return (lnr + ldr);
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::ScalarDecon::load(), and loadnoise().
loadnoise()
int mspass::algorithms::deconvolution::MultiTaperXcorDecon::loadnoise (const std::vector< double > & noise)
Load a section of pre-event noise.
The multitaper algorithm uses pre-event noise to compute frequency-dependent power-domain regularization. This method loads the noise data but does not initiate computation.
{
  const string base_error("MultiTaperXcorDecon::loadnoise: ");
  if (n.empty())
    throw MsPASSError(base_error + "noise vector cannot be empty",
                      ErrorSeverity::Invalid);
  if (n.size() > taperlen)
    throw MsPASSError(base_error +
                          "noise vector is longer than taperlen; multitaper "
                          "inputs must not exceed the configured taper length",
                      ErrorSeverity::Invalid);
  /* For this implementation we insist n be the same length
   * as d (assumed taperlen) to avoid constant recomputing slepians. */
  if (n.size() == taperlen)
    noise = n;
  else {
    int nn = n.size();
    int k;
    noise.clear();
    for (k = 0; k < static_cast<int>(taperlen); ++k)
      noise.push_back(0.0);
    /* This zero pads noise on the right when input series length is short. */
    for (k = 0; k < nn; ++k)
      noise[k] = n[k];
  }
  return 0;
}
process()
void mspass::algorithms::deconvolution::MultiTaperXcorDecon::process () virtual
Compute the multitaper cross-correlation deconvolution result.
The method uses DPSS-stabilized source and noise powers for the denominator and the untapered wavelet/data phase for the final inverse.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  const string base_error("MultiTaperXcorDecon::process():  ");
  result.clear();
  winv = ComplexArray();
  ao_fft = ComplexArray();
  const int output_length = data.size();
  if (output_length > nfft)
    throw MsPASSError(base_error + "data vector exceeds padded fft length",
                      ErrorSeverity::Invalid);
  /* WARNING about this algorithm. At present there is nothing to stop
  a coding error of calling the algorithm with inconsistent signal and
  noise data vectors. */
  if (noise.size() <= 0) {
    throw MsPASSError(base_error + "noise data is empty.",
                      ErrorSeverity::Invalid);
  }
  if (wavelet.size() > taperlen || data.size() > taperlen ||
      noise.size() > taperlen)
    throw MsPASSError(base_error +
                          "wavelet, data, and noise vectors must not exceed "
                          "the configured taper length",
                      ErrorSeverity::Invalid);
  int i, j;
  /* The final inverse is applied to the untapered wavelet/data spectra.  DPSS
  tapers are used only to estimate stable source and noise power terms. */
  vector<ComplexArray> wdata;
  wdata = taper_data(wavelet);
  for (i = 0; i < nseq; ++i) {
    gsl_fft_complex_forward(wdata[i].ptr(), 1, nfft, wavetable, workspace);
  }
  vector<ComplexArray> ndata;
  ndata = taper_data(noise);
  for (i = 0; i < nseq; ++i) {
    gsl_fft_complex_forward(ndata[i].ptr(), 1, nfft, wavetable, workspace);
  }
  vector<double> source_power_denominator(nfft, 0.0);
  for (i = 0; i < nseq; ++i) {
    for (j = 0; j < nfft; ++j) {
      double *zw = wdata[i].ptr(j);
      source_power_denominator[j] +=
          ((*zw) * (*zw) + (*(zw + 1)) * (*(zw + 1))) /
          static_cast<double>(nseq);
    }
  }
  vector<double> noise_power_spectrum(ndata[0].abs());
  for (j = 0; j < static_cast<int>(noise_power_spectrum.size()); ++j)
    noise_power_spectrum[j] *= noise_power_spectrum[j];
  for (i = 1; i < nseq; ++i) {
    vector<double> nwork(ndata[i].abs());
    for (j = 0; j < static_cast<int>(noise_power_spectrum.size()); ++j) {
      noise_power_spectrum[j] += nwork[j] * nwork[j];
    }
  }
  for (j = 0; j < static_cast<int>(noise_power_spectrum.size()); ++j)
    noise_power_spectrum[j] =
        damp * noise_power_spectrum[j] / static_cast<double>(nseq);
  vector<double> padded_wavelet(nfft, 0.0);
  vector<double> padded_data(nfft, 0.0);
  const int nwcopy = std::min(static_cast<int>(wavelet.size()), nfft);
  const int ndcopy = std::min(static_cast<int>(data.size()), nfft);
  for (i = 0; i < nwcopy; ++i)
    padded_wavelet[i] = wavelet[i];
  for (i = 0; i < ndcopy; ++i)
    padded_data[i] = data[i];
  ComplexArray wuntapered(nfft, padded_wavelet);
  ComplexArray duntapered(nfft, padded_data);
  gsl_fft_complex_forward(wuntapered.ptr(), 1, nfft, wavetable, workspace);
  gsl_fft_complex_forward(duntapered.ptr(), 1, nfft, wavetable, workspace);
  double max_source_power =
      *max_element(source_power_denominator.begin(), source_power_denominator.end());
  const double relative_floor = max(DBL_EPSILON, 1.0e-12 * max_source_power);
  ComplexArray winv_work(wuntapered);
  winv_work.conj();
  for (j = 0; j < nfft; ++j) {
    const double den =
        source_power_denominator[j] + noise_power_spectrum[j] + relative_floor;
    double *zw = winv_work.ptr(j);
    (*zw) /= den;
    (*(zw + 1)) /= den;
  }
  ComplexArray rf_fft = winv_work * duntapered;
  ComplexArray ao_fft_work = winv_work * wuntapered;
  ComplexArray ao_scale_test(ao_fft_work);
  ao_scale_test = (*shapingwavelet.wavelet()) * ao_scale_test;
  gsl_fft_complex_inverse(ao_scale_test.ptr(), 1, nfft, wavetable, workspace);
  vector<double> ao_lag =
      ExtractLagWindow(ao_scale_test, output_length, sample_shift);
  if (sample_shift < 0 || sample_shift >= static_cast<int>(ao_lag.size()))
    throw MsPASSError(base_error +
                          "zero-lag sample is outside extracted lag window",
                      ErrorSeverity::Invalid);
  double ao_peak = ao_lag[sample_shift];
  if (fabs(ao_peak) <= 0.0)
    throw MsPASSError(base_error + "actual output has zero peak",
                      ErrorSeverity::Invalid);
  for (j = 0; j < nfft; ++j) {
    double *zrf = rf_fft.ptr(j);
    (*zrf) /= ao_peak;
    (*(zrf + 1)) /= ao_peak;
    double *zw = winv_work.ptr(j);
    (*zw) /= ao_peak;
    (*(zw + 1)) /= ao_peak;
    double *zao = ao_fft_work.ptr(j);
    (*zao) /= ao_peak;
    (*(zao + 1)) /= ao_peak;
  }
  winv = winv_work;
  ao_fft = ao_fft_work;
  /* this applies the shaping wavelet.  NOTE we intentionally do NOT
   * apply this to winv and ao_fft as a bow to some efficiency */
  rf_fft = (*shapingwavelet.wavelet()) * rf_fft;
  /* Next compute inverse fft, save real part, and apply the time shift.
  The time shift formula assumes wrapping in the form used by the gsl
  algorithm. */
  gsl_fft_complex_inverse(rf_fft.ptr(), 1, nfft, wavetable, workspace);
  result = ExtractLagWindow(rf_fft, output_length, sample_shift);
}
References mspass::algorithms::deconvolution::ComplexArray::conj(), mspass::algorithms::deconvolution::ScalarDecon::data, mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::algorithms::deconvolution::ComplexArray::ptr(), mspass::algorithms::deconvolution::ScalarDecon::result, mspass::algorithms::deconvolution::FFTDeconOperator::sample_shift, mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, mspass::algorithms::deconvolution::ScalarDecon::wavelet, mspass::algorithms::deconvolution::ShapingWavelet::wavelet(), mspass::algorithms::deconvolution::FFTDeconOperator::wavetable, mspass::algorithms::deconvolution::FFTDeconOperator::winv, and mspass::algorithms::deconvolution::FFTDeconOperator::workspace.
QCMetrics()
Metadata mspass::algorithms::deconvolution::MultiTaperXcorDecon::QCMetrics () virtual
Return appropriate quality measures.
Each operator commonly has different ways to measure the quality of the result. This method should return these in a generic Metadata object.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  const bool did_process(ao_fft.size() > 0);
  Metadata md(this->BasicQCMetrics("MultiTaperXcorDecon", did_process));
  md.put("multitaper_operator_type", string("xcor_power_stabilized"));
  md.put("multitaper_operator_nfft", nfft);
  md.put("decon_operator_nfft", nfft);
  md.put("decon_operator_sample_shift", sample_shift);
  md.put("multitaper_taper_length", static_cast<int>(taperlen));
  md.put("multitaper_number_tapers", nseq);
  md.put("multitaper_time_bandwidth_product", nw);
  md.put("multitaper_damping_factor", damp);
  md.put("multitaper_processed", did_process);
  md.put("multitaper_number_outputs", did_process ? 1 : 0);
  return md;
}
References mspass::algorithms::deconvolution::ScalarDecon::BasicQCMetrics(), mspass::algorithms::deconvolution::FFTDeconOperator::nfft, mspass::utility::Metadata::put(), mspass::algorithms::deconvolution::FFTDeconOperator::sample_shift, and mspass::algorithms::deconvolution::ComplexArray::size().
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/cxx/include/mspass/algorithms/deconvolution/MultiTaperXcorDecon.h
/home/runner/work/mspass/mspass/cxx/src/lib/algorithms/deconvolution/MultiTaperXcorDecon.cc