FROM --platform=linux/arm64 continuumio/anaconda3:2023.09-0
COPY . /mspass
WORKDIR /mspass
RUN ls
RUN pwd
ENV PYTHON_VERSION=3.11
RUN apt-get update && apt-get install -y wget 
RUN wget http://ftp.de.debian.org/debian/pool/main/c/cmake/cmake_3.13.4-1_arm64.deb
RUN dpkg -i cmake_3.13.4-1_arm64.deb
RUN sed -i '38d' meta.yaml \
    && conda install conda-build anaconda-client \
    && conda config --set anaconda_upload yes \
    && conda config --add channels conda-forge \
    && export ANACONDA_API_TOKEN=cx-8248b24a-767b-41de-ab7d-446cdc390b23 \
    && conda build . --python 3.11
