{% set version = load_file_regex(load_file='pyproject.toml', regex_pattern='^version = "(.*)"$') %}

package:
  name: mspasspy
  version: {{ version }}

source:
  path: .

build:
  script: scripts/build.sh

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - gsl


  host:
    - python {{ PYTHON_VERSION }}
    - pip
    - gsl
    - ipympl
    - boost
    - boost-cpp
    - lapack
    - libblas
    - yaml-cpp

  run:
    - python {{ PYTHON_VERSION }}
    - boost
    - libboost-devel
    - libzlib
    - gsl
    - pyyaml
    - yaml-cpp
    - libblas
    - pymongo
    - numpy
    - obspy
    - dill
    - click
    - cartopy
    - dask
    - distributed
    - cloudpickle
    - schema
    - decorator
    - boto3
    - botocore
    - moto
    - requests 
    - setuptools
    - xarray
    - zarr
    - pandas==1.5.3
    - numba
    - multitaper
    - ipympl


about:
  home: https://github.com/mspass-team/mspass
  license: MIT
  summary: "The Massive Parallel Analysis System for Seismologists is an open source framework for seismic data processing and management. It has three core components: A scalable parallel processing framework based on a dataflow computation model. A NoSQL database system centered on document store. A container-based virtualization environment."
