# Strip the 'v' from the version tag
{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG[1:] %}
{% else %}
{%   set version = "0.0.0" %}
{% endif %}

package:
  name: mspasspy
  version: {{ version }}

source:
  path: .

build:
  script: scripts/conda_build.sh
  include_recipe: False
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ CONDA_PY }}_{{ GIT_DESCRIBE_NUMBER|int }}_g{{ GIT_FULL_HASH[:8] }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - gsl


  host:
    - python {{ PYTHON_VERSION }}
    - pip
    - setuptools>=64
    - setuptools_scm>=8.0
    - wheel
    - gsl
    - boost-cpp=1.85.0
    - liblapack
    - yaml-cpp

  run:
    - python {{ PYTHON_VERSION }}
    - libzlib
    - pyyaml
    - pymongo<4.9.0
    - numpy<2.0.0
    - obspy
    - dill
    - click
    - cartopy
    - dask
    - distributed
    - cloudpickle
    - schema
    - decorator
    - boto3
    - botocore
    - moto
    - requests 
    - setuptools
    - xarray<=2024.3.0
    - zarr
    - pandas==1.5.3
    - numba
    - multitaper
    - ipympl
    - gsl
    - libboost=1.85.0
    - liblapack
    - yaml-cpp


about:
  home: https://github.com/mspass-team/mspass
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  license_url: https://github.com/mspass-team/mspass/blob/master/LICENSE
  summary: Massive Parallel Analysis System for Seismologists
  description: |
    The Massive Parallel Analysis System for Seismologists is an open source framework 
    for seismic data processing and management. It has three core components. 
    A scalable parallel processing framework based on a dataflow computation model. 
    A NoSQL database system centered on document store. 
    A container-based virtualization environment.
  dev_url: https://github.com/mspass-team/mspass
  doc_url: https://www.mspass.org
  doc_source_url: https://github.com/mspass-team/mspass/blob/master/docs/source/index.rst
