[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools-extensions]
cmake-extension = "setup:CMakeExtension"
cmake-build = "setup:CMakeBuild"

[tool.poetry]
name = "mspasspy"
version = "1.0.0"
description = "Massive Parallel Analysis System for Seismologists"
authors = ["Ian Wang <yinzhi.wang.cug@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "*"
pymongo = "*"
numpy = "*"
obspy = "*"
dill = "*"
click = "*"
dask = { extras = ["complete"], version = "*" }
schema = "*"
decorator = "*"
boto3 = "*"
botocore = "*"
moto = "*"
requests = "*"
setuptools = "*"
xarray = "*"
zarr = "*"
pandas = "*"

[tool.poetry.extras]
complete = ["numpy", "pandas", "scipy", "matplotlib"]

[tool.poetry.scripts]
mspass-dbclean = "mspasspy.db.script.dbclean:main"
mspass-dbverify = "mspasspy.db.script.dbverify:main"
mspass-normalize_mseed.py = "mspasspy.db.script.normalize_mseed:main"

