[build-system]
requires = ["setuptools", "wheel", "cmake"]
build-backend = "setuptools.build_meta"

[tool.setuptools-extensions]
cmake-extension = "setup:CMakeExtension"
cmake-build = "setup:CMakeBuild"

[tool.poetry]
name = "mspasspy"
version = "0.0.1"
description = "Massive Parallel Analysis System for Seismologists"
authors = ["Ian Wang <yinzhi.wang.cug@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "*"
pymongo = "<=3.12.1"
numpy = "<=1.22"
obspy = "*"
dill = "*"
click = "==7.1.2"
dask = { extras = ["complete"], version = "*" }
schema = "*"
decorator = "<=4.4.2"
boto3 = "*"
botocore = "*"
moto = "*"
requests = "==2.27.1"
setuptools = "<=65.5.1"
xarray = "*"
zarr = "*"
pandas = "==1.5.3"

[tool.poetry.extras]
complete = ["numpy", "pandas", "scipy", "matplotlib"]

[tool.poetry.scripts]
mspass-dbclean = "mspasspy.db.script.dbclean:main"
mspass-dbverify = "mspasspy.db.script.dbverify:main"
mspass-normalize_mseed.py = "mspasspy.db.script.normalize_mseed:main"

