MsPASS C++ API: mspass::utility::BasicProcessingHistory Class Reference
mspass::utility::BasicProcessingHistory Class Reference
#include <ProcessingHistory.h>
Public Member Functions
BasicProcessingHistory (const std::string jobname, const std::string jobid)
BasicProcessingHistory (const BasicProcessingHistory &parent)
virtual size_t number_of_stages ()
std::string jobid () const
void set_jobid (const std::string &newjid)
std::string jobname () const
void set_jobname (const std::string jobname)
BasicProcessingHistory & operator= (const BasicProcessingHistory &parent)
Protected Attributes
std::string jid
std::string jnm
Detailed Description
Base class defining core concepts.
Constructor & Destructor Documentation
BasicProcessingHistory() [1/3]
mspass::utility::BasicProcessingHistory::BasicProcessingHistory () inline
{
    jid = std::string();
    jnm = std::string();
  };
~BasicProcessingHistory()
virtual mspass::utility::BasicProcessingHistory::~BasicProcessingHistory () inline virtual
{};
BasicProcessingHistory() [2/3]
mspass::utility::BasicProcessingHistory::BasicProcessingHistory (const std::string jobname, const std::string jobid) inline
Construct with explicit job name and job identifier.
Parameters
jobname descriptive name of the processing job.
jobid identifier for the processing job or run.
{
    jid = jobid;
    jnm = jobname;
  };
References jid, jnm, jobid(), and jobname().
BasicProcessingHistory() [3/3]
mspass::utility::BasicProcessingHistory::BasicProcessingHistory (const BasicProcessingHistory & parent) inline
Copy the job-identification fields from another history object.
{
    jid = parent.jid;
    jnm = parent.jnm;
  };
References jid, and jnm.
Member Function Documentation
jobid()
std::string mspass::utility::BasicProcessingHistory::jobid () const inline
Return the job identifier stored with this history object.
{ return jid; };
References jid.
jobname()
std::string mspass::utility::BasicProcessingHistory::jobname () const inline
Return the descriptive job name stored with this history object.
{ return jnm; };
References jnm.
number_of_stages()
virtual size_t mspass::utility::BasicProcessingHistory::number_of_stages () inline virtual
Return number or processing algorithms applied to produce these data.
Implementations of this method need to return a count of the number of processing steps that have been applied to put the data in the current state. This method could be made pure, but for convenience the base class always returns 0 since it does not implement the actual history mechanism.
Reimplemented in mspass::utility::ProcessingHistory.
{ return 0; };
operator=()
BasicProcessingHistory & mspass::utility::BasicProcessingHistory::operator= (const BasicProcessingHistory & parent) inline
Assign the job-identification fields from another history object.
{
    if (this != (&parent)) {
      jnm = parent.jnm;
      jid = parent.jid;
    }
    return *this;
  }
References jid, and jnm.
set_jobid()
void mspass::utility::BasicProcessingHistory::set_jobid (const std::string & newjid) inline
Replace the job identifier stored with this history object.
{ jid = newjid; };
References jid.
set_jobname()
void mspass::utility::BasicProcessingHistory::set_jobname (const std::string jobname) inline
Replace the descriptive job name stored with this history object.
{ jnm = jobname; };
References jnm, and jobname().
Member Data Documentation
jid
std::string mspass::utility::BasicProcessingHistory::jid protected
Identifier for the processing job or run that owns this history.
jnm
std::string mspass::utility::BasicProcessingHistory::jnm protected
Descriptive name of the processing job that owns this history.
The documentation for this class was generated from the following file:
/home/runner/work/mspass/mspass/cxx/include/mspass/utility/ProcessingHistory.h