MsPASS C++ API: mspass::algorithms::deconvolution::FrequencyDomainGIDDecon Class Reference
mspass::algorithms::deconvolution::FrequencyDomainGIDDecon Class Reference
Frequency-domain generalized iterative deconvolution.
#include <FrequencyDomainGIDDecon.h>
Public Member Functions
FrequencyDomainGIDDecon (const mspass::utility::AntelopePf &md)
Construct from the top-level deconvolution parameter file.
FrequencyDomainGIDDecon (const FrequencyDomainGIDDecon &parent)=delete
FrequencyDomainGIDDecon & operator= (const FrequencyDomainGIDDecon &parent)=delete
void changeparameter (const mspass::utility::Metadata &md)
Update operator parameters from a Metadata container.
int load (const mspass::seismic::CoreSeismogram &d, mspass::algorithms::TimeWindow dwin)
Load the three-component signal data used for deconvolution.
int loadnoise (const mspass::seismic::CoreSeismogram &d, mspass::algorithms::TimeWindow nwin)
Load the residual-domain noise window from a seismogram.
int loadwavelet (const mspass::seismic::TimeSeries &wavelet)
Load an externally supplied source wavelet.
int loadwavelet (const mspass::seismic::CoreTimeSeries &wavelet)
Load an externally supplied core source wavelet.
int loadnoise (const mspass::seismic::TimeSeries &noise)
Load an externally supplied scalar noise estimate.
int loadnoise (const mspass::seismic::CoreTimeSeries &noise)
Load an externally supplied core scalar noise estimate.
int loadnoise (const mspass::seismic::PowerSpectrum &noise_spectrum)
Load an externally supplied noise power spectrum.
void clear_external_wavelet ()
void clear_external_noise ()
double deconvolution_window_start () const
double deconvolution_window_end () const
double noise_window_start () const
double noise_window_end () const
std::string configuration_pf_text () const
bool leaf_parameters_have_changed () const
mspass::utility::Metadata changed_leaf_parameters () const
bool external_wavelet_is_loaded () const
bool external_noise_is_loaded () const
bool external_noise_spectrum_is_loaded () const
mspass::seismic::TimeSeries loaded_external_wavelet () const
mspass::seismic::TimeSeries loaded_external_noise () const
mspass::seismic::PowerSpectrum loaded_external_noise_spectrum () const
int load (const mspass::seismic::CoreSeismogram &d, mspass::algorithms::TimeWindow dwin, mspass::algorithms::TimeWindow nwin)
Load signal and residual-noise windows from one seismogram.
void process ()
Run the configured sparse GID iteration.
mspass::seismic::CoreSeismogram getresult ()
Return the shaped deconvolution result.
mspass::seismic::CoreSeismogram sparse_output ()
Return the unshaped sparse spike train.
std::vector< double > lag_weight_vector () const
mspass::seismic::CoreTimeSeries ideal_output ()
mspass::seismic::CoreTimeSeries actual_output ()
mspass::seismic::CoreTimeSeries inverse_wavelet ()
mspass::seismic::CoreTimeSeries inverse_wavelet (double t0parent)
Return the inverse wavelet with the parent time correction.
mspass::utility::Metadata QCMetrics ()
Return appropriate quality measures.
Public Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
ScalarDecon ()
Construct an empty scalar deconvolution operator.
ScalarDecon (const mspass::utility::Metadata &md)
Construct from Metadata.
ScalarDecon (const std::vector< double > &d, const std::vector< double > &w)
Construct with loaded data and source-wavelet vectors.
ScalarDecon (const ScalarDecon &parent)
Copy constructor preserving loaded vectors and shaping wavelet.
int load (const std::vector< double > &wavelet, const std::vector< double > &data)
Load all data required for decon.
int loaddata (const std::vector< double > &data)
int loadwavelet (const std::vector< double > &wavelet)
ScalarDecon & operator= (const ScalarDecon &parent)
Assign loaded wavelet, data, and result vectors from parent.
std::vector< double > getresult ()
Return the current deconvolution result vector.
void changeparameter (const mspass::utility::Metadata &md)
void change_shaping_wavelet (const ShapingWavelet &nsw)
ShapingWavelet get_shaping_wavelet () const
virtual mspass::seismic::CoreTimeSeries output_shaping_wavelet ()
Return the output shaping wavelet.
mspass::seismic::CoreTimeSeries ideal_output ()
Legacy alias for output_shaping_wavelet.
mspass::seismic::CoreTimeSeries resolution_kernel ()
Alias for actual_output using inverse-theory terminology.
Public Member Functions inherited from mspass::algorithms::deconvolution::BasicDeconOperator
virtual ~BasicDeconOperator ()
Additional Inherited Members
Protected Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
mspass::utility::Metadata BasicQCMetrics (const std::string &operator_name, const bool processed)
Build QC Metadata fields common to scalar deconvolution operators.
Protected Attributes inherited from mspass::algorithms::deconvolution::ScalarDecon
std::vector< double > data
Data vector to be deconvolved by concrete scalar methods.
std::vector< double > wavelet
Source-wavelet estimate used by concrete scalar methods.
std::vector< double > result
Deconvolved output vector produced by process.
ShapingWavelet shapingwavelet
Output shaping wavelet applied by scalar deconvolution methods.
Detailed Description
Frequency-domain generalized iterative deconvolution.
This engine shares the sparse GID iteration semantics of TimeDomainGIDDecon but applies the candidate inverse operator in the frequency domain. Processing requires both a loaded signal window and residual-domain noise window. External PowerSpectrum noise is accepted by ns_gid and group_sparse because both use NS-GID inverse-operator regularization; it does not replace load(d, dwin, nwin) or loadnoise(d, nwin).
Constructor & Destructor Documentation
FrequencyDomainGIDDecon()
mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::FrequencyDomainGIDDecon (const mspass::utility::AntelopePf & md)
Construct from the top-level deconvolution parameter file.
The constructor reads the frequency_domain_gid_deconvolution branch, builds the configured leaf inverse operator, and initializes the signal, noise, and FFT processing windows.
Parameters
md top-level Antelope parameter file for the deconvolution operator.
    : ScalarDecon(), preprocessor(nullptr), cnrprocessor(nullptr) {
  const string base_error("FrequencyDomainGIDDecon constructor: ");
  try {
    config_pf_text = AntelopePfToText(mdtoplevel);
    AntelopePf md = mdtoplevel.get_branch("deconvolution_operator_type");
    AntelopePf mdgid = md.get_branch("frequency_domain_gid_deconvolution");
    decon_type = ParseGIDDeconType(mdgid, "FrequencyDomainGIDDecon");
    dwin = TimeWindow(GetDoubleRequired(mdgid, "full_data_window_start"),
                      GetDoubleRequired(mdgid, "full_data_window_end"));
    fftwin =
        TimeWindow(GetDoubleRequired(mdgid, "deconvolution_data_window_start"),
                   GetDoubleRequired(mdgid, "deconvolution_data_window_end"));
    nwin = TimeWindow(GetDoubleRequired(mdgid, "noise_window_start"),
                      GetDoubleRequired(mdgid, "noise_window_end"));
    ValidateWindowDuration(dwin, "full_data_window", base_error);
    ValidateWindowDuration(fftwin, "deconvolution_data_window", base_error);
    ValidateWindowDuration(nwin, "noise_window", base_error);
    if (fftwin.start < dwin.start || fftwin.end > dwin.end)
      throw MsPASSError(base_error +
                            "deconvolution window must be inside full window",
                        ErrorSeverity::Invalid);
    noise_component = GetIntRequired(mdgid, "noise_component");
    ValidateThreeComponentIndex(noise_component, "noise_component", base_error);
    target_dt = GetDoubleRequired(mdgid, "target_sample_interval");
    ValidatePositive(target_dt, "target_sample_interval", base_error);
    int maxns = static_cast<int>((fftwin.end - fftwin.start) / target_dt) + 1;
    int nfft = nextPowerOf2(maxns);
    mdgid.put("operator_nfft", nfft);
    this->ScalarDecon::changeparameter(mdgid);
    this->shapingwavelet = ShapingWavelet(mdgid, nfft);
    iter_max = GetIntRequired(mdgid, "maximum_iterations");
    ValidatePositiveInteger(iter_max, "maximum_iterations", base_error);
    residual_ratio_floor = GetDoubleRequired(mdgid, "residual_ratio_floor");
    ValidateNonnegative(residual_ratio_floor, "residual_ratio_floor",
                        base_error);
    residual_improvement_floor =
        GetDoubleRequired(mdgid, "residual_fractional_improvement_floor");
    ValidateNonnegative(residual_improvement_floor,
                        "residual_fractional_improvement_floor", base_error);
    lag_weight_penalty_function =
        mdgid.is_defined("lag_weight_penalty_function")
            ? mdgid.get_string("lag_weight_penalty_function")
            : "none";
    lag_weight_penalty_scale_factor =
        mdgid.is_defined("lag_weight_penalty_scale_factor")
            ? GetDoubleRequired(mdgid, "lag_weight_penalty_scale_factor")
            : 1.0;
    if (!isfinite(lag_weight_penalty_scale_factor) ||
        lag_weight_penalty_scale_factor <= 0.0 ||
        lag_weight_penalty_scale_factor > 1.0)
      throw MsPASSError(base_error +
                            "lag_weight_penalty_scale_factor must be in (0, 1]",
                        ErrorSeverity::Fatal);
    lag_weight_function_width =
        mdgid.is_defined("lag_weight_function_width")
            ? GetIntRequired(mdgid, "lag_weight_function_width")
            : 0;
    if (mdgid.is_defined("lag_weight_function_width"))
      ValidatePositiveInteger(lag_weight_function_width,
                              "lag_weight_function_width", base_error);
    if (lag_weight_penalty_function == "none") {
      lag_weight_penalty = vector<double>{1.0};
    } else if (lag_weight_penalty_function == "shaping_wavelet") {
      CoreTimeSeries shaping(this->output_shaping_wavelet());
      lag_weight_penalty = BuildGIDLagWeightPenaltyFunctionFromKernel(
          lag_weight_penalty_function, lag_weight_penalty_scale_factor,
          shaping.s, shaping.sample_number(0.0), "FrequencyDomainGIDDecon");
    } else if (lag_weight_penalty_function == "resolution_kernel" ||
               GIDLagWeightPenaltyUsesAdaptiveMemory(
                   lag_weight_penalty_function)) {
      lag_weight_penalty = vector<double>{1.0};
    } else {
      lag_weight_penalty =
          BuildGIDLagWeightPenaltyFunction(mdgid, "FrequencyDomainGIDDecon");
    }
    AntelopePf mdleaf;
    switch (decon_type) {
    case WATER_LEVEL:
      mdleaf = md.get_branch("water_level");
      ValidateGIDLeafWindow(mdleaf, fftwin, "water level", base_error);
      preprocessor = std::make_unique<WaterLevelDecon>(mdleaf);
      break;
    case LEAST_SQ:
      mdleaf = md.get_branch("least_square");
      ValidateGIDLeafWindow(mdleaf, fftwin, "least square", base_error);
      preprocessor = std::make_unique<LeastSquareDecon>(mdleaf);
      break;
    case MULTI_TAPER:
      mdleaf = md.get_branch("multi_taper");
      ValidateGIDLeafWindow(mdleaf, fftwin, "multi taper", base_error);
      preprocessor = std::make_unique<MultiTaperXcorDecon>(mdleaf);
      break;
    case CNR:
      mdleaf = md.get_branch("cnr");
      ValidateGIDLeafWindow(mdleaf, fftwin, "CNR", base_error);
      cnrprocessor = std::make_unique<CNRDeconEngine>(mdleaf);
      break;
    case GROUP_SPARSE:
      mdleaf = md.get_branch("ns_gid");
      ValidateGIDLeafWindow(mdleaf, fftwin, "group sparse NS-GID inverse",
                            base_error);
      preprocessor = std::make_unique<NoiseStableDecon>(mdleaf);
      break;
    case NS_GID:
    default:
      mdleaf = md.get_branch("ns_gid");
      ValidateGIDLeafWindow(mdleaf, fftwin, "NS-GID", base_error);
      preprocessor = std::make_unique<NoiseStableDecon>(mdleaf);
      break;
    };
    changed_leaf_metadata = Metadata(mdleaf);
    external_wavelet_loaded = false;
    external_noise_loaded = false;
    external_noise_spectrum_loaded = false;
    residual_noise_from_external = false;
    leaf_parameters_changed = false;
    external_wavelet_allowed = GetBoolDefault(
        mdgid, "ns_gid_external_wavelet_allowed", true);
    ns_peak_sigma_threshold =
        GetDoubleDefault(mdgid, "ns_gid_peak_sigma_threshold", 4.0);
    ValidatePositive(ns_peak_sigma_threshold, "ns_gid_peak_sigma_threshold",
                     base_error);
    ns_peak_probability_threshold = GetDoubleDefault(
        mdgid, "ns_gid_peak_probability_threshold", 0.995);
    ValidateProbability(ns_peak_probability_threshold,
                        "ns_gid_peak_probability_threshold", base_error);
    ns_use_empirical_noise_threshold = GetBoolDefault(
        mdgid, "ns_gid_use_empirical_noise_threshold", true);
    ns_residual_noise_ratio_floor = GetDoubleDefault(
        mdgid, "ns_gid_residual_noise_ratio_floor", 1.0);
    ValidateNonnegative(ns_residual_noise_ratio_floor,
                        "ns_gid_residual_noise_ratio_floor", base_error);
    ns_max_spikes = GetIntDefault(mdgid, "ns_gid_max_spikes", 0);
    if (ns_max_spikes < 0)
      throw MsPASSError(base_error + "ns_gid_max_spikes must be nonnegative",
                        ErrorSeverity::Fatal);
    ns_refit_interval = GetIntDefault(mdgid, "ns_gid_refit_interval", 5);
    if (ns_refit_interval < 1)
      throw MsPASSError(base_error + "ns_gid_refit_interval must be positive",
                        ErrorSeverity::Fatal);
    ns_ridge_beta =
        GetDoubleDefault(mdgid, "ns_gid_ridge_beta", 1.0e-10);
    ValidateNonnegative(ns_ridge_beta, "ns_gid_ridge_beta", base_error);
    group_sparse_lambda = GetDoubleDefault(mdgid, "group_sparse_lambda", 0.0);
    ValidateNonnegative(group_sparse_lambda, "group_sparse_lambda",
                        base_error);
    group_sparse_lambda_scale =
        GetDoubleDefault(mdgid, "group_sparse_lambda_scale", 1.0);
    ValidateNonnegative(group_sparse_lambda_scale,
                        "group_sparse_lambda_scale", base_error);
    group_sparse_tolerance =
        GetDoubleDefault(mdgid, "group_sparse_tolerance", 1.0e-4);
    ValidatePositive(group_sparse_tolerance, "group_sparse_tolerance",
                     base_error);
    group_sparse_max_iterations =
        GetIntDefault(mdgid, "group_sparse_max_iterations", iter_max);
    ValidatePositiveInteger(group_sparse_max_iterations,
                            "group_sparse_max_iterations", base_error);
    group_sparse_active_threshold =
        GetDoubleDefault(mdgid, "group_sparse_active_threshold", 2.0e-2);
    ValidateNonnegative(group_sparse_active_threshold,
                        "group_sparse_active_threshold", base_error);
    group_sparse_active_threshold_scale =
        GetDoubleDefault(mdgid, "group_sparse_active_threshold_scale", 1.0);
    ValidateNonnegative(group_sparse_active_threshold_scale,
                        "group_sparse_active_threshold_scale", base_error);
    group_sparse_active_threshold_quantile =
        GetDoubleDefault(mdgid, "group_sparse_active_threshold_quantile", 0.90);
    ValidateProbability(group_sparse_active_threshold_quantile,
                        "group_sparse_active_threshold_quantile", base_error);
    this->invalidate_processing_state();
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::ScalarDecon::changeparameter(), mspass::algorithms::TimeWindow::end, mspass::utility::AntelopePf::get_branch(), mspass::utility::Metadata::get_string(), mspass::utility::Metadata::is_defined(), mspass::algorithms::deconvolution::ScalarDecon::output_shaping_wavelet(), mspass::utility::Metadata::put(), mspass::seismic::CoreTimeSeries::s, mspass::seismic::BasicTimeSeries::sample_number(), mspass::algorithms::deconvolution::ScalarDecon::shapingwavelet, and mspass::algorithms::TimeWindow::start.
~FrequencyDomainGIDDecon()
mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::~FrequencyDomainGIDDecon ()
{}
Member Function Documentation
actual_output()
CoreTimeSeries mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::actual_output () virtual
Return the resolution kernel of the active leaf inverse operator.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  if (!processed)
    throw MsPASSError(
        "FrequencyDomainGIDDecon::actual_output: process must be called first",
        ErrorSeverity::Invalid);
  if (decon_type == CNR)
    return cnrprocessor->actual_output(current_wavelet);
  return preprocessor->actual_output();
}
changed_leaf_parameters()
mspass::utility::Metadata mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::changed_leaf_parameters () const inline
Return the metadata most recently passed to changeparameter.
{
    return this->changed_leaf_metadata;
  };
changeparameter()
void mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::changeparameter (const mspass::utility::Metadata & md) virtual
Update operator parameters from a Metadata container.
Implements mspass::algorithms::deconvolution::BasicDeconOperator.
{
  const bool cnr_mode(decon_type == CNR);
  ValidateGIDLeafOperatorMetadata(
      md, fftwin, target_dt, "FrequencyDomainGIDDecon::changeparameter",
      cnr_mode);
  this->invalidate_processing_state();
  if (cnr_mode)
    cnrprocessor->changeparameter(md);
  else
    preprocessor->changeparameter(md);
  changed_leaf_metadata = Metadata(md);
  leaf_parameters_changed = true;
}
clear_external_noise()
void mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::clear_external_noise ()
Clear externally loaded noise or noise spectrum and invalidate state.
{
  external_noise_loaded = false;
  external_noise_spectrum_loaded = false;
  external_noise = TimeSeries();
  external_noise_spectrum = PowerSpectrum();
  if (residual_noise_from_external) {
    n.kill();
    nnwin = 0;
    residual_noise_from_external = false;
  }
  this->invalidate_processing_state();
}
References mspass::seismic::BasicTimeSeries::kill().
clear_external_wavelet()
void mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::clear_external_wavelet ()
Clear any externally loaded wavelet and invalidate processed state.
{
  external_wavelet_loaded = false;
  external_wavelet = TimeSeries();
  this->invalidate_processing_state();
}
configuration_pf_text()
std::string mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::configuration_pf_text () const inline
Return the serialized configuration parameter-file text.
{ return this->config_pf_text; };
deconvolution_window_end()
double mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::deconvolution_window_end () const inline
Return the configured deconvolution-window end time.
{ return this->fftwin.end; };
References mspass::algorithms::TimeWindow::end.
deconvolution_window_start()
double mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::deconvolution_window_start () const inline
Return the configured deconvolution-window start time.
{ return this->fftwin.start; };
References mspass::algorithms::TimeWindow::start.
external_noise_is_loaded()
bool mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::external_noise_is_loaded () const inline
Return true if an external scalar noise waveform is currently loaded.
{ return this->external_noise_loaded; };
external_noise_spectrum_is_loaded()
bool mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::external_noise_spectrum_is_loaded () const inline
Return true if an external noise power spectrum is currently loaded.
{
    return this->external_noise_spectrum_loaded;
  };
external_wavelet_is_loaded()
bool mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::external_wavelet_is_loaded () const inline
Return true if an external wavelet is currently loaded.
{
    return this->external_wavelet_loaded;
  };
getresult()
CoreSeismogram mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::getresult ()
Return the shaped deconvolution result.
The sparse output is convolved with the configured shaping wavelet and returned in the loaded data window.
{
  if (!processed)
    throw MsPASSError(
        "FrequencyDomainGIDDecon::getresult: process must be called first",
        ErrorSeverity::Invalid);
  CoreSeismogram sparse(this->sparse_output());
  CoreTimeSeries shaping(this->output_shaping_wavelet());
  CoreSeismogram shaped(sparse_convolve(shaping, sparse));
  return WindowData(shaped, dwin);
}
References mspass::algorithms::deconvolution::ScalarDecon::output_shaping_wavelet(), and sparse_output().
ideal_output()
CoreTimeSeries mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::ideal_output ()
Legacy alias for output_shaping_wavelet inherited from ScalarDecon.
{
  return this->ScalarDecon::output_shaping_wavelet();
}
References mspass::algorithms::deconvolution::ScalarDecon::output_shaping_wavelet().
inverse_wavelet() [1/2]
CoreTimeSeries mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::inverse_wavelet () virtual
Return the inverse wavelet using a zero parent start time.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  return this->inverse_wavelet(0.0);
}
References inverse_wavelet().
inverse_wavelet() [2/2]
CoreTimeSeries mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::inverse_wavelet (double t0parent) virtual
Return the inverse wavelet with the parent time correction.
Parameters
t0parent start time of the parent waveform used to set output time.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  if (!processed)
    throw MsPASSError(
        "FrequencyDomainGIDDecon::inverse_wavelet: process must be called first",
        ErrorSeverity::Invalid);
  if (decon_type == CNR)
    return cnrprocessor->inverse_wavelet(current_wavelet, t0parent);
  return preprocessor->inverse_wavelet(t0parent);
}
lag_weight_vector()
vector< double > mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::lag_weight_vector () const
Return the final lag weights used by the sparse picker.
{
  if (!processed)
    throw MsPASSError("FrequencyDomainGIDDecon::lag_weight_vector: process "
                      "must be called first",
                      ErrorSeverity::Invalid);
  return lag_weights;
}
leaf_parameters_have_changed()
bool mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::leaf_parameters_have_changed () const inline
Return true if changeparameter has updated the leaf inverse operator.
{
    return this->leaf_parameters_changed;
  };
load() [1/2]
int mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::load (const mspass::seismic::CoreSeismogram & d, mspass::algorithms::TimeWindow dwin)
Load the three-component signal data used for deconvolution.
The input seismogram is windowed to dwin. The supplied window must contain the configured deconvolution FFT window.
Parameters
d input three-component seismogram.
dwin full data window to retain around the deconvolution interval.
Returns
0 on success and 1 if the requested data window is unusable.
{
  this->invalidate_processing_state();
  d_all.kill();
  ndwin = 0;
  ValidateWindowDuration(dwin_in, "signal_window",
                         "FrequencyDomainGIDDecon::load");
  if ((dwin_in.start > fftwin.start) || (dwin_in.end < fftwin.end))
    return 1;
  dwin = dwin_in;
  d_all = WindowData(draw, dwin);
  if (d_all.dead() || d_all.npts() <= 0)
    return 1;
  ndwin = d_all.npts();
  return 0;
}
References mspass::seismic::BasicTimeSeries::dead(), mspass::algorithms::TimeWindow::end, mspass::seismic::BasicTimeSeries::kill(), mspass::seismic::BasicTimeSeries::npts(), and mspass::algorithms::TimeWindow::start.
load() [2/2]
int mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::load (const mspass::seismic::CoreSeismogram & d, mspass::algorithms::TimeWindow dwin, mspass::algorithms::TimeWindow nwin)
Load signal and residual-noise windows from one seismogram.
This convenience overload calls loadnoise(d, nwin) and load(d, dwin).
Parameters
d input three-component seismogram.
dwin full data window to retain around the deconvolution interval.
nwin time window used to estimate residual noise.
Returns
sum of the signal and noise load return codes.
{
  this->invalidate_processing_state();
  d_all.kill();
  n.kill();
  ndwin = 0;
  nnwin = 0;
  ValidateWindowDuration(dwin, "signal_window",
                         "FrequencyDomainGIDDecon::load");
  ValidateWindowDuration(nwin, "noise_window",
                         "FrequencyDomainGIDDecon::load");
  if ((dwin.start > fftwin.start) || (dwin.end < fftwin.end))
    return 1;
  int iretn = this->loadnoise(draw, nwin);
  int iretd = this->load(draw, dwin);
  return iretn + iretd;
}
References mspass::algorithms::TimeWindow::end, mspass::seismic::BasicTimeSeries::kill(), load(), loadnoise(), and mspass::algorithms::TimeWindow::start.
loaded_external_noise()
mspass::seismic::TimeSeries mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::loaded_external_noise () const inline
Return the loaded external noise, or an empty TimeSeries if absent.
{
    if (!this->external_noise_loaded)
      return mspass::seismic::TimeSeries();
    return this->external_noise;
  };
loaded_external_noise_spectrum()
mspass::seismic::PowerSpectrum mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::loaded_external_noise_spectrum () const inline
Return the loaded external noise spectrum, or an empty spectrum.
{
    if (!this->external_noise_spectrum_loaded)
      return mspass::seismic::PowerSpectrum();
    return this->external_noise_spectrum;
  };
loaded_external_wavelet()
mspass::seismic::TimeSeries mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::loaded_external_wavelet () const inline
Return the loaded external wavelet, or an empty TimeSeries if absent.
{
    if (!this->external_wavelet_loaded)
      return mspass::seismic::TimeSeries();
    return this->external_wavelet;
  };
loadnoise() [1/4]
int mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::loadnoise (const mspass::seismic::CoreSeismogram & d, mspass::algorithms::TimeWindow nwin)
Load the residual-domain noise window from a seismogram.
Parameters
d input three-component seismogram containing the noise window.
nwin time window used to estimate residual noise.
Returns
0 on success and 1 if the requested noise window is unusable.
{
  this->invalidate_processing_state();
  n.kill();
  nnwin = 0;
  residual_noise_from_external = false;
  ValidateWindowDuration(nwin_in, "noise_window",
                         "FrequencyDomainGIDDecon::loadnoise");
  nwin = nwin_in;
  n = WindowData(draw, nwin);
  if (n.dead() || n.npts() <= 0)
    return 1;
  nnwin = n.npts();
  return 0;
}
References mspass::seismic::BasicTimeSeries::dead(), mspass::seismic::BasicTimeSeries::kill(), and mspass::seismic::BasicTimeSeries::npts().
loadnoise() [2/4]
int mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::loadnoise (const mspass::seismic::CoreTimeSeries & noise)
Load an externally supplied core scalar noise estimate.
Parameters
noise core time series converted to a TimeSeries noise waveform.
Returns
0 on success.
{
  TimeSeries ts(noise_in, "FrequencyDomainGIDDecon");
  return this->loadnoise(ts);
}
References loadnoise().
loadnoise() [3/4]
int mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::loadnoise (const mspass::seismic::PowerSpectrum & noise_spectrum)
Load an externally supplied noise power spectrum.
This overload is supported for ns_gid and group_sparse modes where the leaf inverse operator uses the spectrum for noise-stable regularization.
Parameters
noise_spectrum spectrum that covers DC and describes noise power.
Returns
0 on success.
{
  if (decon_type != NS_GID && decon_type != GROUP_SPARSE)
    throw MsPASSError("FrequencyDomainGIDDecon::loadnoise: external "
                      "PowerSpectrum noise is only supported for ns_gid and "
                      "group_sparse; pass a TimeSeries noise estimate for "
                      "multi_taper or use the configured noise window for "
                      "other GID modes",
                      ErrorSeverity::Invalid);
  ValidatePowerSpectrumCoversDC(noise_spectrum_in,
                                "FrequencyDomainGIDDecon::loadnoise");
  this->invalidate_processing_state();
  external_noise_loaded = false;
  external_noise_spectrum_loaded = false;
  external_noise = TimeSeries();
  external_noise_spectrum = noise_spectrum_in;
  external_noise_spectrum_loaded = true;
  external_noise_loaded = false;
  if (residual_noise_from_external) {
    n.kill();
    nnwin = 0;
    residual_noise_from_external = false;
  }
  return 0;
}
References mspass::seismic::BasicTimeSeries::kill().
loadnoise() [4/4]
int mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::loadnoise (const mspass::seismic::TimeSeries & noise)
Load an externally supplied scalar noise estimate.
The sample interval must match the configured target sample interval. If no residual-domain noise seismogram is already loaded, this vector is also used to synthesize the residual noise estimate required by the sparse iteration.
Parameters
noise scalar noise waveform.
Returns
0 on success.
{
  if (noise_in.dead())
    throw MsPASSError("FrequencyDomainGIDDecon::loadnoise: external noise is "
                      "marked dead",
                      ErrorSeverity::Invalid);
  if (noise_in.npts() <= 0)
    throw MsPASSError("FrequencyDomainGIDDecon::loadnoise: external noise is "
                      "empty",
                      ErrorSeverity::Invalid);
  ValidateExternalTimeSeriesSampleInterval(
      noise_in, target_dt, "FrequencyDomainGIDDecon::loadnoise");
  const bool keep_residual_noise =
      n.live() && n.npts() > 0 && !residual_noise_from_external;
  this->invalidate_processing_state();
  external_noise_loaded = false;
  external_noise_spectrum_loaded = false;
  external_noise_spectrum = PowerSpectrum();
  external_noise = noise_in;
  external_noise_loaded = true;
  external_noise_spectrum_loaded = false;
  if (!keep_residual_noise) {
    n = CoreSeismogram(noise_in.npts());
    n.set_t0(noise_in.t0());
    n.set_dt(noise_in.dt());
    n.set_live();
    n.set_tref(noise_in.timetype());
    for (int k = 0; k < 3; ++k)
      cblas_dcopy(noise_in.npts(), &(noise_in.s[0]), 1, n.u.get_address(k, 0),
                  3);
    nnwin = n.npts();
    residual_noise_from_external = true;
  }
  return 0;
}
References mspass::seismic::BasicTimeSeries::dead(), mspass::seismic::BasicTimeSeries::dt(), mspass::utility::dmatrix::get_address(), mspass::seismic::BasicTimeSeries::live(), mspass::seismic::BasicTimeSeries::npts(), mspass::seismic::CoreTimeSeries::s, mspass::seismic::CoreSeismogram::set_dt(), mspass::seismic::BasicTimeSeries::set_live(), mspass::seismic::CoreSeismogram::set_t0(), mspass::seismic::BasicTimeSeries::set_tref(), mspass::seismic::BasicTimeSeries::t0(), mspass::seismic::BasicTimeSeries::timetype(), and mspass::seismic::CoreSeismogram::u.
loadwavelet() [1/2]
int mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::loadwavelet (const mspass::seismic::CoreTimeSeries & wavelet)
Load an externally supplied core source wavelet.
Parameters
wavelet core time series converted to a TimeSeries wavelet.
Returns
0 on success.
{
  TimeSeries ts(wavelet, "FrequencyDomainGIDDecon");
  return this->loadwavelet(ts);
}
References loadwavelet(), and mspass::algorithms::deconvolution::ScalarDecon::wavelet.
loadwavelet() [2/2]
int mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::loadwavelet (const mspass::seismic::TimeSeries & wavelet)
Load an externally supplied source wavelet.
External wavelets are accepted only when enabled by the configuration and must match the configured target sample interval.
Parameters
wavelet source wavelet to use instead of the internally estimated one.
Returns
0 on success.
{
  if (!external_wavelet_allowed)
    throw MsPASSError("FrequencyDomainGIDDecon::loadwavelet: external "
                      "wavelets are disabled by "
                      "ns_gid_external_wavelet_allowed",
                      ErrorSeverity::Invalid);
  if (wavelet.dead())
    throw MsPASSError("FrequencyDomainGIDDecon::loadwavelet: external wavelet "
                      "is marked dead",
                      ErrorSeverity::Invalid);
  if (wavelet.npts() <= 0)
    throw MsPASSError("FrequencyDomainGIDDecon::loadwavelet: external wavelet "
                      "is empty",
                      ErrorSeverity::Invalid);
  ValidateExternalTimeSeriesSampleInterval(
      wavelet, target_dt, "FrequencyDomainGIDDecon::loadwavelet");
  this->invalidate_processing_state();
  external_wavelet_loaded = false;
  external_wavelet = wavelet;
  external_wavelet_loaded = true;
  return 0;
}
References mspass::algorithms::deconvolution::ScalarDecon::wavelet.
noise_window_end()
double mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::noise_window_end () const inline
Return the current residual-noise window end time.
{ return this->nwin.end; };
References mspass::algorithms::TimeWindow::end.
noise_window_start()
double mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::noise_window_start () const inline
Return the current residual-noise window start time.
{ return this->nwin.start; };
References mspass::algorithms::TimeWindow::start.
process()
void mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::process () virtual
Run the configured sparse GID iteration.
Processing requires both a loaded data window and a loaded residual-noise estimate. The method resets prior processed products before computing a new inverse operator, sparse spike train, and QC state.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  const string base_error("FrequencyDomainGIDDecon::process: ");
  string process_stage("initialize inverse operator");
  this->invalidate_processing_state();
  ns_stop_reason = (decon_type == NS_GID) ? "running" : "not_enabled";
  gid_stop_reason = "running";
  gid_converged = false;
  try {
    if (d_all.dead() || d_all.npts() <= 0)
      throw MsPASSError(base_error + "valid data window has not been loaded",
                        ErrorSeverity::Invalid);
    if (n.dead() || n.npts() <= 0)
      throw MsPASSError(base_error + "valid noise window has not been loaded",
                        ErrorSeverity::Invalid);
    this->initialize_inverse_operator();
    if (decon_type == NS_GID || decon_type == GROUP_SPARSE) {
      process_stage = "compute NS-GID peak threshold";
      ns_peak_threshold = this->compute_ns_peak_threshold();
      adaptive_penalty_noise_amplitude =
          (ns_noise_amplitude_rms > 0.0) ? ns_noise_amplitude_rms
                                         : ns_peak_threshold;
    } else if (decon_type == CNR) {
      TimeSeries nwavelet =
          external_noise_loaded
              ? TimeSeries(external_noise)
              : TimeSeries(ExtractComponent(n, noise_component),
                           "FrequencyDomainGIDDecon");
      adaptive_penalty_noise_amplitude =
          cnr_processed_noise_rms(*cnrprocessor, nwavelet, n,
                                  static_cast<int>(actual_o_fir.size()));
    } else {
      process_stage = "estimate inverse-wavelet noise amplitude";
      CoreTimeSeries winv(preprocessor->inverse_wavelet(d_decon.t0()));
      adaptive_penalty_noise_amplitude =
          inverse_wavelet_noise_rms(winv, n);
    }
    process_stage = "initialize residual";
    r = d_decon;
    spikes.clear();
    iter_count = 0;
    lag_weights.clear();
    lag_weights.reserve(r.npts());
    for (int i = 0; i < r.npts(); ++i)
      lag_weights.push_back(1.0);
    for (int i = 0; i < r.npts(); ++i) {
      int col0 = i - actual_o_0;
      if ((col0 < 0) || ((col0 + actual_o_fir.size()) > r.npts()))
        lag_weights[i] = 0.0;
    }
    adaptive_penalty_memory.assign(lag_weights.size(), 0.0);
    adaptive_penalty_retention.assign(lag_weights.size(), 0.0);
    ns_converged = false;
    ns_stop_reason = (decon_type == NS_GID) ? "running" : "not_enabled";
    gid_stop_reason = "running";
    gid_converged = false;
    ns_last_peak_significance = 0.0;
    resid_l2_initial = matrix_l2(r.u);
    resid_linf_initial = matrix_linf(r.u);
    resid_l2_prev = resid_l2_initial;
    if (resid_l2_initial <= 0.0)
      throw MsPASSError(base_error + "input data residual is zero",
                        ErrorSeverity::Invalid);
    if (decon_type == GROUP_SPARSE) {
      process_stage = "group-sparse regularized solve";
      if (ns_peak_threshold <= 0.0)
        ns_peak_threshold = this->compute_ns_peak_threshold();
      group_sparse_lambda_used = group_sparse_lambda;
      if (group_sparse_lambda_used <= 0.0) {
        const double lambda_base =
            (ns_peak_threshold > 0.0) ? ns_peak_threshold
                                      : 0.02 * resid_linf_initial;
        group_sparse_lambda_used = group_sparse_lambda_scale * lambda_base;
      }
      GroupSparseDeconResult gs = SolveGroupSparseDecon(
          d_decon, actual_o_fir, actual_o_0, group_sparse_lambda_used,
          group_sparse_max_iterations, group_sparse_tolerance,
          group_sparse_active_threshold, group_sparse_active_threshold_scale,
          group_sparse_active_threshold_quantile, "FrequencyDomainGIDDecon");
      spikes = gs.spikes;
      iter_count = gs.iterations;
      group_sparse_iterations = gs.iterations;
      group_sparse_active_groups = static_cast<int>(spikes.size());
      group_sparse_converged = gs.converged;
      group_sparse_objective_initial = gs.objective_initial;
      group_sparse_objective_final = gs.objective_final;
      group_sparse_fractional_improvement_final =
          gs.fractional_improvement_final;
      group_sparse_active_threshold_quantile_value =
          gs.active_threshold_quantile_value;
      group_sparse_active_threshold_used = gs.active_threshold_used;
      process_stage = "refit group-sparse amplitudes";
      RefitSpikeAmplitudes(spikes, d_decon, actual_o_fir, actual_o_0,
                           ns_ridge_beta);
      spikes.remove_if([this](const ThreeCSpike &spk) {
        return spk.amp <= group_sparse_active_threshold_used;
      });
      group_sparse_active_groups = static_cast<int>(spikes.size());
      process_stage = "recompute group-sparse final residual";
      r = d_decon;
      for (auto sptr = spikes.begin(); sptr != spikes.end(); ++sptr)
        this->update_residual_matrix(*sptr);
      resid_l2_final = matrix_l2(r.u);
      resid_linf_final = matrix_linf(r.u);
      group_sparse_debiased_objective_final =
          GroupSparseObjective(r, spikes, group_sparse_lambda_used);
      group_sparse_debiased_fractional_improvement_final =
          (group_sparse_objective_initial -
           group_sparse_debiased_objective_final) /
          max(1.0, group_sparse_objective_initial);
      if (!lag_weights.empty()) {
        auto lwmax = max_element(lag_weights.begin(), lag_weights.end());
        lag_weight_linf_final = (lwmax != lag_weights.end()) ? *lwmax : 0.0;
        lag_weight_l2_final =
            cblas_dnrm2(lag_weights.size(), &(lag_weights[0]), 1);
      }
      gid_stop_reason = group_sparse_converged
                            ? "group_sparse_converged"
                            : "group_sparse_max_iterations";
      gid_converged = group_sparse_converged;
      ns_stop_reason = "not_enabled";
      ns_converged = false;
      processed = true;
      return;
    }
    vector<double> amps;
    amps.reserve(r.npts());
    process_stage = "sparse iteration";
    for (int iiter = 0; iiter < iter_max; ++iiter) {
      amps.clear();
      for (int i = 0; i < r.npts(); ++i) {
        int col0 = i - actual_o_0;
        if ((col0 < 0) || ((col0 + actual_o_fir.size()) > r.npts())) {
          amps.push_back(0.0);
        } else {
          double amp2(0.0);
          for (int k = 0; k < 3; ++k)
            amp2 += r.u(k, i) * r.u(k, i);
          amps.push_back(amp2 * lag_weights[i] * lag_weights[i]);
        }
      }
      auto amax = max_element(amps.begin(), amps.end());
      if ((amax == amps.end()) || (*amax <= 0.0)) {
        gid_stop_reason = "no_valid_candidate";
        gid_converged = true;
        break;
      }
      if (decon_type == NS_GID) {
        int imax = distance(amps.begin(), amax);
        double candidate_amp2(0.0);
        for (int k = 0; k < 3; ++k)
          candidate_amp2 += r.u(k, imax) * r.u(k, imax);
        double candidate_amp = sqrt(max(0.0, candidate_amp2));
        ns_last_peak_significance =
            (ns_peak_threshold > 0.0) ? candidate_amp / ns_peak_threshold
                                      : 0.0;
        if (ns_peak_threshold > 0.0 && candidate_amp < ns_peak_threshold) {
          ns_stop_reason = "candidate_not_significant";
          ns_converged = true;
          gid_stop_reason = ns_stop_reason;
          gid_converged = ns_converged;
          break;
        }
        if ((ns_max_spikes > 0) &&
            (static_cast<int>(spikes.size()) >= ns_max_spikes)) {
          ns_stop_reason = "max_spikes";
          ns_converged = true;
          gid_stop_reason = ns_stop_reason;
          gid_converged = ns_converged;
          break;
        }
      }
      int imax = distance(amps.begin(), amax);
      bool accepted(false);
      while (!accepted && (*amax > 0.0)) {
        imax = distance(amps.begin(), amax);
        double candidate_amp2(0.0);
        for (int k = 0; k < 3; ++k)
          candidate_amp2 += r.u(k, imax) * r.u(k, imax);
        const double candidate_amp = sqrt(max(0.0, candidate_amp2));
        ThreeCSpike spk(r.u, imax);
        this->rescale_spike(spk);
        CoreSeismogram saved_r(r);
        this->update_residual_matrix(spk);
        double trial_l2 = matrix_l2(r.u);
        if (trial_l2 < resid_l2_prev) {
          spikes.push_back(spk);
          this->update_lag_weights(imax, candidate_amp);
          iter_count = iiter + 1;
          accepted = true;
          if (decon_type == NS_GID && ns_refit_interval > 0 &&
              (static_cast<int>(spikes.size()) % ns_refit_interval) == 0) {
            RefitSpikeAmplitudes(spikes, d_decon, actual_o_fir, actual_o_0,
                                 ns_ridge_beta);
            r = d_decon;
            for (auto sptr = spikes.begin(); sptr != spikes.end(); ++sptr)
              this->update_residual_matrix(*sptr);
          }
        } else {
          r = saved_r;
          amps[imax] = 0.0;
          amax = max_element(amps.begin(), amps.end());
        }
      }
      if (!accepted) {
        gid_stop_reason = "no_acceptable_candidate";
        gid_converged = true;
        break;
      }
      resid_l2_final = matrix_l2(r.u);
      resid_linf_final = matrix_linf(r.u);
      double ratio = resid_l2_final / resid_l2_initial;
      double improvement = (resid_l2_prev - resid_l2_final) / resid_l2_initial;
      ns_fractional_improvement_final = improvement;
      resid_l2_prev = resid_l2_final;
      if (decon_type == NS_GID && ns_noise_l2 > 0.0 &&
          (resid_l2_final / ns_noise_l2) <= ns_residual_noise_ratio_floor) {
        ns_stop_reason = "residual_reached_noise_floor";
        ns_converged = true;
        gid_stop_reason = ns_stop_reason;
        gid_converged = ns_converged;
        break;
      }
      if (ratio <= residual_ratio_floor) {
        gid_stop_reason = "residual_ratio_floor";
        gid_converged = true;
        if (decon_type == NS_GID) {
          ns_stop_reason = "residual_ratio_floor";
          ns_converged = true;
        }
        break;
      }
      if (improvement <= residual_improvement_floor) {
        gid_stop_reason = "fractional_improvement_floor";
        gid_converged = true;
        if (decon_type == NS_GID) {
          ns_stop_reason = "fractional_improvement_floor";
          ns_converged = true;
        }
        break;
      }
    }
    if (decon_type == NS_GID && ns_stop_reason == "running") {
      if (iter_count >= iter_max)
        ns_stop_reason = "max_iterations";
      else {
        ns_stop_reason = "converged";
        ns_converged = true;
      }
      gid_stop_reason = ns_stop_reason;
      gid_converged = ns_converged;
    }
    if (decon_type != NS_GID && gid_stop_reason == "running") {
      gid_stop_reason = (iter_count >= iter_max) ? "max_iterations"
                                                 : "converged";
      gid_converged = (gid_stop_reason != "max_iterations");
    }
    process_stage = "refit sparse amplitudes";
    double ridge_beta = (decon_type == NS_GID) ? ns_ridge_beta : 1.0e-10;
    RefitSpikeAmplitudes(spikes, d_decon, actual_o_fir, actual_o_0,
                         ridge_beta);
    process_stage = "recompute final residual";
    r = d_decon;
    for (auto sptr = spikes.begin(); sptr != spikes.end(); ++sptr)
      this->update_residual_matrix(*sptr);
    resid_l2_final = matrix_l2(r.u);
    resid_linf_final = matrix_linf(r.u);
    if (!lag_weights.empty()) {
      auto lwmax = max_element(lag_weights.begin(), lag_weights.end());
      lag_weight_linf_final = (lwmax != lag_weights.end()) ? *lwmax : 0.0;
      lag_weight_l2_final =
          cblas_dnrm2(lag_weights.size(), &(lag_weights[0]), 1);
    }
    processed = true;
  } catch (const MsPASSError &err) {
    throw MsPASSError(base_error + "failed during " + process_stage + "\n" +
                          string(err.what()),
                      err.severity());
  } catch (...) {
    throw;
  };
}
References mspass::algorithms::deconvolution::GroupSparseDeconResult::active_threshold_quantile_value, mspass::algorithms::deconvolution::GroupSparseDeconResult::active_threshold_used, mspass::algorithms::deconvolution::ThreeCSpike::amp, mspass::algorithms::deconvolution::GroupSparseDeconResult::converged, mspass::seismic::BasicTimeSeries::dead(), mspass::algorithms::deconvolution::GroupSparseDeconResult::fractional_improvement_final, mspass::algorithms::deconvolution::GroupSparseDeconResult::iterations, mspass::seismic::BasicTimeSeries::npts(), mspass::algorithms::deconvolution::GroupSparseDeconResult::objective_final, mspass::algorithms::deconvolution::GroupSparseDeconResult::objective_initial, mspass::utility::MsPASSError::severity(), mspass::algorithms::deconvolution::GroupSparseDeconResult::spikes, mspass::seismic::BasicTimeSeries::t0(), mspass::seismic::CoreSeismogram::u, and mspass::utility::MsPASSError::what().
QCMetrics()
Metadata mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::QCMetrics () virtual
Return appropriate quality measures.
Each operator commonly has different was to measure the quality of the result. This method should return these in a generic Metadata object.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  Metadata md;
  PutPrefixedMetadata(md, changed_leaf_metadata, "gid_leaf_");
  md.put("decon_operator", string("FrequencyDomainGIDDecon"));
  md.put("deconvolution_type", GIDDeconTypeName(decon_type));
  md.put("decon_processed", processed);
  md.put("decon_sample_interval", target_dt);
  md.put("decon_window_start", dwin.start);
  md.put("decon_window_end", dwin.end);
  md.put("deconvolution_window_start", fftwin.start);
  md.put("deconvolution_window_end", fftwin.end);
  md.put("noise_window_start", nwin.start);
  md.put("noise_window_end", nwin.end);
  md.put("gid_leaf_parameters_changed", leaf_parameters_changed);
  md.put("gid_processed", processed);
  md.put("gid_converged", gid_converged);
  md.put("gid_stop_reason", gid_stop_reason);
  md.put("gid_iterations", iter_count);
  md.put("gid_number_spikes", static_cast<int>(spikes.size()));
  md.put("gid_maximum_iterations",
         (decon_type == GROUP_SPARSE) ? group_sparse_max_iterations : iter_max);
  if (decon_type != GROUP_SPARSE) {
    md.put("gid_penalty_function", lag_weight_penalty_function);
    md.put("gid_penalty_scale_factor", lag_weight_penalty_scale_factor);
    md.put("gid_penalty_width", lag_weight_function_width);
    md.put("gid_penalty_effective_width",
           static_cast<int>(lag_weight_penalty.size()));
    md.put("gid_adaptive_penalty_enabled",
           GIDLagWeightPenaltyUsesAdaptiveMemory(lag_weight_penalty_function));
    md.put("gid_penalty_noise_amplitude", adaptive_penalty_noise_amplitude);
    md.put("gid_penalty_last_confidence", adaptive_penalty_last_confidence);
    md.put("gid_penalty_last_immediate_strength",
           adaptive_penalty_last_immediate_strength);
    md.put("gid_penalty_last_specificity", adaptive_penalty_last_specificity);
    md.put("gid_penalty_last_decay_factor",
           adaptive_penalty_last_decay_factor);
    md.put("gid_penalty_memory_Linf_final", adaptive_penalty_memory_linf);
    md.put("gid_penalty_memory_L2_final", adaptive_penalty_memory_l2);
    int gid_penalty_valid_lags(0);
    for (auto w : lag_weights) {
      if (w > 0.0)
        ++gid_penalty_valid_lags;
    }
    md.put("gid_penalty_valid_lags", gid_penalty_valid_lags);
  }
  md.put("gid_external_wavelet_used", external_wavelet_loaded);
  md.put("gid_external_noise_used", external_noise_loaded);
  md.put("gid_external_noise_spectrum_used",
         external_noise_spectrum_loaded);
  md.put("iteration_count", iter_count);
  md.put("residual_Linf_initial", resid_linf_initial);
  md.put("residual_Linf_final", resid_linf_final);
  md.put("residual_L2_initial", resid_l2_initial);
  md.put("residual_L2_final", resid_l2_final);
  md.put("lag_weight_Linf_final", lag_weight_linf_final);
  md.put("lag_weight_L2_final", lag_weight_l2_final);
  md.put("gid_actual_o_fir_npts", static_cast<int>(actual_o_fir.size()));
  md.put("gid_actual_o_fir_zero_lag_index", actual_o_0);
  md.put("gid_actual_o_fir_peak_normalized",
         processed && !actual_o_fir.empty());
  if (decon_type == GROUP_SPARSE) {
    md.put("group_sparse_enabled", true);
    md.put("group_sparse_inverse_operator", string("ns_gid"));
    md.put("group_sparse_lambda_requested", group_sparse_lambda);
    md.put("group_sparse_lambda_scale", group_sparse_lambda_scale);
    md.put("group_sparse_lambda_used", group_sparse_lambda_used);
    md.put("group_sparse_tolerance", group_sparse_tolerance);
    md.put("group_sparse_max_iterations", group_sparse_max_iterations);
    md.put("group_sparse_iterations", group_sparse_iterations);
    md.put("group_sparse_converged", group_sparse_converged);
    md.put("group_sparse_active_threshold", group_sparse_active_threshold);
    md.put("group_sparse_active_threshold_scale",
           group_sparse_active_threshold_scale);
    md.put("group_sparse_active_threshold_quantile",
           group_sparse_active_threshold_quantile);
    md.put("group_sparse_active_threshold_quantile_value",
           group_sparse_active_threshold_quantile_value);
    md.put("group_sparse_active_threshold_used",
           group_sparse_active_threshold_used);
    md.put("group_sparse_active_groups", group_sparse_active_groups);
    md.put("group_sparse_objective_initial", group_sparse_objective_initial);
    md.put("group_sparse_objective_final", group_sparse_objective_final);
    md.put("group_sparse_fractional_improvement_final",
           group_sparse_fractional_improvement_final);
    md.put("group_sparse_debiased_objective_final",
           group_sparse_debiased_objective_final);
    md.put("group_sparse_debiased_fractional_improvement_final",
           group_sparse_debiased_fractional_improvement_final);
    md.put("group_sparse_noise_threshold", ns_peak_threshold);
    NoiseStableDecon *nsop =
        dynamic_cast<NoiseStableDecon *>(preprocessor.get());
    if (nsop != nullptr) {
      Metadata nsmd(nsop->QCMetrics());
      md.put("group_sparse_inverse_gain_max_requested",
             nsmd.get_double("ns_gid_gain_max_requested"));
      md.put("group_sparse_inverse_gain_max_actual",
             nsmd.get_double("ns_gid_gain_max_actual"));
      md.put("group_sparse_inverse_mu_min", nsmd.get_double("ns_gid_mu_min"));
      md.put("group_sparse_inverse_alpha", nsmd.get_double("ns_gid_alpha"));
      md.put("group_sparse_inverse_noise_amplification",
             nsmd.get_double("ns_gid_noise_amplification"));
      md.put("group_sparse_inverse_effective_bandwidth_fraction",
             nsmd.get_double("ns_gid_effective_bandwidth_fraction"));
      md.put("group_sparse_inverse_operator_nfft",
             nsmd.get_int("ns_gid_operator_nfft"));
      md.put("group_sparse_inverse_use_reliability_taper",
             nsmd.get_bool("ns_gid_use_reliability_taper"));
      md.put("group_sparse_inverse_external_wavelet_used",
             external_wavelet_loaded);
      md.put("group_sparse_inverse_external_noise_used",
             external_noise_loaded);
      md.put("group_sparse_inverse_external_noise_spectrum_used",
             external_noise_spectrum_loaded);
    }
  }
  if (decon_type == NS_GID) {
    md.put("ns_gid_enabled", true);
    md.put("ns_gid_stop_reason", ns_stop_reason);
    md.put("ns_gid_converged", ns_converged);
    md.put("ns_gid_iterations", iter_count);
    md.put("ns_gid_number_spikes", static_cast<int>(spikes.size()));
    md.put("ns_gid_peak_threshold", ns_peak_threshold);
    md.put("ns_gid_noise_amplitude_rms", ns_noise_amplitude_rms);
    md.put("ns_gid_last_peak_significance", ns_last_peak_significance);
    md.put("ns_gid_external_wavelet_used", external_wavelet_loaded);
    md.put("ns_gid_external_noise_used", external_noise_loaded);
    md.put("ns_gid_external_noise_spectrum_used",
           external_noise_spectrum_loaded);
    md.put("ns_gid_residual_l2_initial", resid_l2_initial);
    md.put("ns_gid_residual_l2_final", resid_l2_final);
    md.put("ns_gid_residual_noise_ratio",
           (ns_noise_l2 > 0.0) ? resid_l2_final / ns_noise_l2 : 0.0);
    md.put("ns_gid_fractional_improvement_final",
           ns_fractional_improvement_final);
    NoiseStableDecon *nsop = dynamic_cast<NoiseStableDecon *>(preprocessor.get());
    if (nsop != nullptr) {
      Metadata nsmd(nsop->QCMetrics());
      md.put("ns_gid_gain_max_requested",
             nsmd.get_double("ns_gid_gain_max_requested"));
      md.put("ns_gid_gain_max_actual",
             nsmd.get_double("ns_gid_gain_max_actual"));
      md.put("ns_gid_mu_min", nsmd.get_double("ns_gid_mu_min"));
      md.put("ns_gid_alpha", nsmd.get_double("ns_gid_alpha"));
      md.put("ns_gid_noise_amplification",
             nsmd.get_double("ns_gid_noise_amplification"));
      md.put("ns_gid_effective_bandwidth_fraction",
             nsmd.get_double("ns_gid_effective_bandwidth_fraction"));
      md.put("ns_gid_operator_nfft", nsmd.get_int("ns_gid_operator_nfft"));
    }
  }
  return md;
}
References mspass::algorithms::TimeWindow::end, mspass::utility::Metadata::get_bool(), mspass::utility::Metadata::get_double(), mspass::utility::Metadata::get_int(), mspass::utility::Metadata::put(), mspass::algorithms::deconvolution::NoiseStableDecon::QCMetrics(), and mspass::algorithms::TimeWindow::start.
sparse_output()
CoreSeismogram mspass::algorithms::deconvolution::FrequencyDomainGIDDecon::sparse_output ()
Return the unshaped sparse spike train.
Values are inserted at the selected sparse lags in a seismogram aligned with the loaded data window.
{
  if (!processed)
    throw MsPASSError(
        "FrequencyDomainGIDDecon::sparse_output: process must be called first",
        ErrorSeverity::Invalid);
  CoreSeismogram result(d_all);
  result = WindowData(result, dwin);
  result.u.zero();
  double dt0 = result.t0() - r.t0();
  int delta_col = round(dt0 / r.dt());
  for (auto sptr = spikes.begin(); sptr != spikes.end(); ++sptr) {
    int resultcol = (sptr->col) - delta_col;
    if ((resultcol < 0) || (resultcol >= result.npts()))
      continue;
    for (int k = 0; k < 3; ++k)
      result.u(k, resultcol) = sptr->u[k];
  }
  return result;
}
References mspass::seismic::BasicTimeSeries::dt(), mspass::algorithms::deconvolution::ScalarDecon::result, and mspass::seismic::BasicTimeSeries::t0().
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/cxx/include/mspass/algorithms/deconvolution/FrequencyDomainGIDDecon.h
/home/runner/work/mspass/mspass/cxx/src/lib/algorithms/deconvolution/FrequencyDomainGIDDecon.cc