MsPASS C++ API: mspass::algorithms::deconvolution::FFTDeconOperator Class Reference
mspass::algorithms::deconvolution::FFTDeconOperator Class Reference
Object to hold components needed in all fft based decon algorithms.
#include <FFTDeconOperator.h>
Public Member Functions
FFTDeconOperator ()
Construct an empty FFT operator shell.
FFTDeconOperator (const mspass::utility::Metadata &md)
Construct from deconvolution Metadata.
FFTDeconOperator (const FFTDeconOperator &parent)
Copy constructor.
~FFTDeconOperator ()
Release allocated GSL FFT work objects.
FFTDeconOperator & operator= (const FFTDeconOperator &parent)
Assign FFT size and lag shift from another operator.
void changeparameter (const mspass::utility::Metadata &md)
Reconfigure the FFT operator from Metadata.
void change_size (const int nfft_new)
Change the FFT work-buffer length.
void change_shift (const int shift)
Set the sample offset used to unwrap deconvolution lag windows.
int get_size ()
Return the current FFT work-buffer length.
int get_shift ()
Return the current deconvolution lag-window sample shift.
int operator_size ()
Return the current FFT work-buffer length.
int operator_shift ()
Return the current deconvolution lag-window sample shift.
double df (const double dt)
Return frequency spacing for the current FFT length.
mspass::seismic::CoreTimeSeries FourierInverse (const ComplexArray &winv, const ComplexArray &sw, const double dt, const double t0parent)
Return inverse wavelet for Fourier methods.
Protected Attributes
int nfft
Current FFT work-buffer length in samples.
int sample_shift
Sample offset used to place zero lag in deconvolution outputs.
gsl_fft_complex_wavetable * wavetable
GSL factorization table allocated for nfft.
gsl_fft_complex_workspace * workspace
GSL scratch workspace allocated for nfft.
ComplexArray winv
Frequency-domain inverse wavelet coefficients for derived operators.
Detailed Description
Object to hold components needed in all fft based decon algorithms.
The fft based algorithms implemented here us the GNU Scientific Library prime factorization fft algorithm. Those methods require initialization given length of the fft to load and store the factorization data. This object holds these for all such methods and recomputes them only when needed for efficiency.
Constructor & Destructor Documentation
FFTDeconOperator() [1/3]
mspass::algorithms::deconvolution::FFTDeconOperator::FFTDeconOperator ()
Construct an empty FFT operator shell.
The FFT length is initialized to zero and GSL work objects are left unallocated until change_size or changeparameter supplies an operator size.
{
  nfft = 0;
  sample_shift = 0;
  wavetable = NULL;
  workspace = NULL;
}
References nfft, sample_shift, wavetable, and workspace.
FFTDeconOperator() [2/3]
mspass::algorithms::deconvolution::FFTDeconOperator::FFTDeconOperator (const mspass::utility::Metadata & md)
Construct from deconvolution Metadata.
Uses operator_nfft, target_sample_interval, and the deconvolution data window entries in md to choose a power-of-two FFT length, compute the standard lag-window sample shift, and allocate the GSL FFT work objects.
{
  try {
    const string base_error("FFTDeconOperator Metadata constructor:  ");
    const double ts =
        GetDoubleRequired(md, "deconvolution_data_window_start");
    const double te = GetDoubleRequired(md, "deconvolution_data_window_end");
    const double dt = GetDoubleRequired(md, "target_sample_interval");
    ValidateWindowDuration(TimeWindow(ts, te), "deconvolution_data_window",
                           base_error);
    if (!std::isfinite(dt) || dt <= 0.0)
      throw MsPASSError(base_error +
                            "target_sample_interval must be positive",
                        ErrorSeverity::Fatal);
    int nfftpf = GetIntRequired(md, "operator_nfft");
    /* We force a power of 2 algorithm for efficiency and always round up*/
    this->nfft = nextPowerOf2(nfftpf);
    /* We compute the sample shift from the window start time and dt.  This
     * assures the output will be phase shifted so zero lag is at the zero
     * position of the array.   Necessary because operators using this object
     * internally only return a raw vector of samples not a child of
     * BasicTimeSeries. */
    this->sample_shift = ComputeDeconSampleShift(md);
    if (this->sample_shift < 0)
      throw MsPASSError(base_error +
                            "illegal sample_shift parameter - must be ge 0",
                        ErrorSeverity::Fatal);
    if ((this->sample_shift) > nfft)
      throw MsPASSError(
          base_error + "Computed shift parameter exceeds length of fft\n" +
              "Deconvolution data window parameters are probably nonsense",
          ErrorSeverity::Fatal);
    wavetable = gsl_fft_complex_wavetable_alloc(nfft);
    workspace = gsl_fft_complex_workspace_alloc(nfft);
  } catch (...) {
    throw;
  };
}
References nfft, sample_shift, wavetable, and workspace.
FFTDeconOperator() [3/3]
mspass::algorithms::deconvolution::FFTDeconOperator::FFTDeconOperator (const FFTDeconOperator & parent)
Copy constructor.
Copies the FFT length and sample shift while allocating independent GSL work objects for the new operator.
{
  nfft = parent.nfft;
  sample_shift = parent.sample_shift;
  /* copies need their own work space */
  wavetable = gsl_fft_complex_wavetable_alloc(nfft);
  workspace = gsl_fft_complex_workspace_alloc(nfft);
}
References nfft, sample_shift, wavetable, and workspace.
~FFTDeconOperator()
mspass::algorithms::deconvolution::FFTDeconOperator::~FFTDeconOperator ()
Release allocated GSL FFT work objects.
{
  if (wavetable != NULL)
    gsl_fft_complex_wavetable_free(wavetable);
  if (workspace != NULL)
    gsl_fft_complex_workspace_free(workspace);
}
References wavetable, and workspace.
Member Function Documentation
change_shift()
void mspass::algorithms::deconvolution::FFTDeconOperator::change_shift (const int shift) inline
Set the sample offset used to unwrap deconvolution lag windows.
{ sample_shift = shift; };
References sample_shift.
change_size()
void mspass::algorithms::deconvolution::FFTDeconOperator::change_size (const int nfft_new)
Change the FFT work-buffer length.
Frees any existing GSL FFT work objects, stores nfft_new as the operator length, and allocates new work objects for that size.
{
  try {
    if (nfft != 0) {
      if (wavetable != NULL)
        gsl_fft_complex_wavetable_free(wavetable);
      if (workspace != NULL)
        gsl_fft_complex_workspace_free(workspace);
    }
    nfft = n;
    wavetable = gsl_fft_complex_wavetable_alloc(nfft);
    workspace = gsl_fft_complex_workspace_alloc(nfft);
  } catch (...) {
    throw;
  };
}
References nfft, wavetable, and workspace.
changeparameter()
void mspass::algorithms::deconvolution::FFTDeconOperator::changeparameter (const mspass::utility::Metadata & md)
Reconfigure the FFT operator from Metadata.
Recomputes the power-of-two FFT length and deconvolution sample shift from md. Existing GSL work objects are replaced only when the FFT length changes.
{
  try {
    const string base_error("FFTDeconOperator::changeparameter:  ");
    const double ts =
        GetDoubleRequired(md, "deconvolution_data_window_start");
    const double te = GetDoubleRequired(md, "deconvolution_data_window_end");
    const double dt = GetDoubleRequired(md, "target_sample_interval");
    ValidateWindowDuration(TimeWindow(ts, te), "deconvolution_data_window",
                           base_error);
    if (!std::isfinite(dt) || dt <= 0.0)
      throw MsPASSError(base_error +
                            "target_sample_interval must be positive",
                        ErrorSeverity::Fatal);
    const int nfft_test = nextPowerOf2(GetIntRequired(md, "operator_nfft"));
    const int sample_shift_test = ComputeDeconSampleShift(md);
    if (sample_shift_test < 0)
      throw MsPASSError(base_error +
                            "illegal sample_shift parameter - must be ge 0",
                        ErrorSeverity::Fatal);
    if (sample_shift_test > nfft_test)
      throw MsPASSError(
          base_error + "computed sample_shift exceeds length of fft",
          ErrorSeverity::Fatal);
    if (nfft_test != nfft) {
      gsl_fft_complex_wavetable *new_wavetable =
          gsl_fft_complex_wavetable_alloc(nfft_test);
      gsl_fft_complex_workspace *new_workspace =
          gsl_fft_complex_workspace_alloc(nfft_test);
      if (wavetable != NULL)
        gsl_fft_complex_wavetable_free(wavetable);
      if (workspace != NULL)
        gsl_fft_complex_workspace_free(workspace);
      wavetable = new_wavetable;
      workspace = new_workspace;
      nfft = nfft_test;
    }
    sample_shift = sample_shift_test;
  } catch (...) {
    throw;
  };
}
References nfft, sample_shift, wavetable, and workspace.
df()
double mspass::algorithms::deconvolution::FFTDeconOperator::df (const double dt) inline
Return frequency spacing for the current FFT length.
Parameters
dt sample interval of the time-domain signal.
Returns
1 / (nfft * dt), the frequency-bin spacing for this operator.
{
    double period;
    period = static_cast<double>(nfft) * dt;
    return 1.0 / period;
  };
References nfft.
FourierInverse()
CoreTimeSeries mspass::algorithms::deconvolution::FFTDeconOperator::FourierInverse (const ComplexArray & winv, const ComplexArray & sw, const double dt, const double t0parent)
Return inverse wavelet for Fourier methods.
This is a helper to be used by the inverse_wavelet method for all Fourier based deconvolution methods. It avoids repetitious code that would be required otherwise. inverse_wavelet methods are only wrappers for this generic method. See documentation for inverse_wavelet for description of tshift and t0parent.
{
  try {
    const string base_error("FFTDeconOperator::FourierInverse:  ");
    /* Compute wrap point for circular shift operator - note negative
    because a positive t0 is requires wrapping at a point i0 to the left
    of the original zero point*/
    /* Testing with matlab prototypes showed Fourier inverse filters
     * showed they created valid results only if the filter used a
     * circular shift of nfft/2.   This sets that as a requirement here. */
    int ntest;
    ntest = winv.size();
    if (ntest != nfft)
      throw MsPASSError(
          base_error +
              "wavelet inverse fourier array size mismatch with operator",
          ErrorSeverity::Invalid);
    if (sw.size() != nfft)
      throw MsPASSError(
          base_error +
              "shaping wavelet fourier array size mismatch with operator",
          ErrorSeverity::Invalid);
    ComplexArray winv_work(winv);
    /* This applies the shaping wavelet*/
    winv_work *= sw;
    gsl_fft_complex_inverse(winv_work.ptr(), 1, nfft, wavetable, workspace);
    CoreTimeSeries result;
    result.set_t0(t0parent);
    result.set_dt(dt);
    result.set_live();
    /* Note this new api method initializes s all zeros so we need only set
    the values not use push back below */
    result.set_npts(nfft);
    result.set_tref(TimeReferenceType::Relative);
    for (int k = 0; k < winv_work.size(); ++k)
      result.s[k] = winv_work[k].real();
    return result;
  } catch (...) {
    throw;
  };
}
References nfft, mspass::algorithms::deconvolution::ComplexArray::ptr(), mspass::seismic::CoreTimeSeries::s, mspass::seismic::CoreTimeSeries::set_dt(), mspass::seismic::BasicTimeSeries::set_live(), mspass::seismic::CoreTimeSeries::set_npts(), mspass::seismic::CoreTimeSeries::set_t0(), mspass::seismic::BasicTimeSeries::set_tref(), mspass::algorithms::deconvolution::ComplexArray::size(), wavetable, winv, and workspace.
get_shift()
int mspass::algorithms::deconvolution::FFTDeconOperator::get_shift () inline
Return the current deconvolution lag-window sample shift.
{ return sample_shift; };
References sample_shift.
get_size()
int mspass::algorithms::deconvolution::FFTDeconOperator::get_size () inline
Return the current FFT work-buffer length.
{ return nfft; };
References nfft.
operator=()
FFTDeconOperator & mspass::algorithms::deconvolution::FFTDeconOperator::operator= (const FFTDeconOperator & parent)
Assign FFT size and lag shift from another operator.
The assigned operator receives its own GSL wavetable and workspace.
{
  if (this != &parent) {
    nfft = parent.nfft;
    sample_shift = parent.sample_shift;
    /* copies need their own work space */
    wavetable = gsl_fft_complex_wavetable_alloc(nfft);
    workspace = gsl_fft_complex_workspace_alloc(nfft);
  }
  return *this;
}
References nfft, sample_shift, wavetable, and workspace.
operator_shift()
int mspass::algorithms::deconvolution::FFTDeconOperator::operator_shift () inline
Return the current deconvolution lag-window sample shift.
{ return sample_shift; };
References sample_shift.
operator_size()
int mspass::algorithms::deconvolution::FFTDeconOperator::operator_size () inline
Return the current FFT work-buffer length.
{ return static_cast<int>(nfft); };
References nfft.
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/cxx/include/mspass/algorithms/deconvolution/FFTDeconOperator.h
/home/runner/work/mspass/mspass/cxx/src/lib/algorithms/deconvolution/FFTDeconOperator.cc