MsPASS C++ API: mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon Class Reference
mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon Class Reference
Time-domain damped least-squares deconvolution.
#include <TimeDomainLeastSquareDecon.h>
Public Member Functions
TimeDomainLeastSquareDecon ()
TimeDomainLeastSquareDecon (const TimeDomainLeastSquareDecon &parent)
TimeDomainLeastSquareDecon (const mspass::utility::Metadata &md)
TimeDomainLeastSquareDecon (const mspass::utility::Metadata &md, const std::vector< double > &wavelet, const std::vector< double > &data)
void changeparameter (const mspass::utility::Metadata &md)
void process ()
mspass::seismic::CoreTimeSeries output_shaping_wavelet ()
mspass::seismic::CoreTimeSeries actual_output ()
mspass::seismic::CoreTimeSeries inverse_wavelet (const double t0parent)
mspass::seismic::CoreTimeSeries inverse_wavelet ()
mspass::utility::Metadata QCMetrics ()
Public Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
ScalarDecon ()
Construct an empty scalar deconvolution operator.
ScalarDecon (const mspass::utility::Metadata &md)
Construct from Metadata.
ScalarDecon (const std::vector< double > &d, const std::vector< double > &w)
Construct with loaded data and source-wavelet vectors.
ScalarDecon (const ScalarDecon &parent)
Copy constructor preserving loaded vectors and shaping wavelet.
int load (const std::vector< double > &wavelet, const std::vector< double > &data)
Load all data required for decon.
int loaddata (const std::vector< double > &data)
int loadwavelet (const std::vector< double > &wavelet)
ScalarDecon & operator= (const ScalarDecon &parent)
Assign loaded wavelet, data, and result vectors from parent.
std::vector< double > getresult ()
Return the current deconvolution result vector.
void change_shaping_wavelet (const ShapingWavelet &nsw)
ShapingWavelet get_shaping_wavelet () const
mspass::seismic::CoreTimeSeries ideal_output ()
Legacy alias for output_shaping_wavelet.
mspass::seismic::CoreTimeSeries resolution_kernel ()
Alias for actual_output using inverse-theory terminology.
Public Member Functions inherited from mspass::algorithms::deconvolution::BasicDeconOperator
virtual ~BasicDeconOperator ()
Additional Inherited Members
Protected Member Functions inherited from mspass::algorithms::deconvolution::ScalarDecon
mspass::utility::Metadata BasicQCMetrics (const std::string &operator_name, const bool processed)
Build QC Metadata fields common to scalar deconvolution operators.
Protected Attributes inherited from mspass::algorithms::deconvolution::ScalarDecon
std::vector< double > data
Data vector to be deconvolved by concrete scalar methods.
std::vector< double > wavelet
Source-wavelet estimate used by concrete scalar methods.
std::vector< double > result
Deconvolved output vector produced by process.
ShapingWavelet shapingwavelet
Output shaping wavelet applied by scalar deconvolution methods.
Detailed Description
Time-domain damped least-squares deconvolution.
This class solves the linear convolution problem
d_i = sum_j s_{i-j} m_j + n_i
directly in the time domain. The convolution matrix is the cropped linear Toeplitz operator implied by the loaded wavelet and data vectors. The default model length is the loaded data length, so output samples have the same zero-lag convention as the input window, but the computation is not circular: samples outside the wavelet support are treated as zero.
The normal equations are regularized as
(S^T S + lambda I) m = S^T d
where lambda is damping_factor * max(diag(S^T S)). damping_factor must be positive; smaller values give higher resolution but amplify noise and conditioning errors, while larger values suppress noise at the cost of resolution. The solve uses LAPACK Cholesky with LU fallback; it does not explicitly invert the normal-equation matrix.
Constructor & Destructor Documentation
TimeDomainLeastSquareDecon() [1/4]
mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::TimeDomainLeastSquareDecon ()
Construct with default damped least-squares parameters.
    : ScalarDecon(), output_length(0), sample_shift(0), damp(1.0e-6), dt(1.0),
      residual_norm(0.0), data_norm(0.0), regularization_parameter(0.0) {}
TimeDomainLeastSquareDecon() [2/4]
mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::TimeDomainLeastSquareDecon (const TimeDomainLeastSquareDecon & parent)
Copy constructor.
    : ScalarDecon(parent), output_length(parent.output_length),
      sample_shift(parent.sample_shift), damp(parent.damp), dt(parent.dt),
      residual_norm(parent.residual_norm), data_norm(parent.data_norm),
      regularization_parameter(parent.regularization_parameter) {}
TimeDomainLeastSquareDecon() [3/4]
mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::TimeDomainLeastSquareDecon (const mspass::utility::Metadata & md)
Construct from Metadata parameters.
    : ScalarDecon(), output_length(0), sample_shift(0), damp(1.0e-6), dt(1.0),
      residual_norm(0.0), data_norm(0.0), regularization_parameter(0.0) {
  this->read_metadata(md);
}
TimeDomainLeastSquareDecon() [4/4]
mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::TimeDomainLeastSquareDecon (const mspass::utility::Metadata & md, const std::vector< double > & wavelet, const std::vector< double > & data)
Construct from Metadata plus wavelet and data vectors.
    : TimeDomainLeastSquareDecon(md) {
  wavelet = w;
  data = d;
}
References mspass::algorithms::deconvolution::ScalarDecon::data, and mspass::algorithms::deconvolution::ScalarDecon::wavelet.
Member Function Documentation
actual_output()
CoreTimeSeries mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::actual_output () virtual
Return the actual output generated by the wavelet/operator pair.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  if (wavelet.empty())
    throw MsPASSError("TimeDomainLeastSquareDecon::actual_output: wavelet has "
                      "not been loaded",
                      ErrorSeverity::Invalid);
  const string base_error("TimeDomainLeastSquareDecon::actual_output: ");
  const int nlag(this->diagnostic_length());
  if (sample_shift < 0 || sample_shift >= nlag)
    throw MsPASSError(base_error +
                          "zero-lag sample is outside extracted lag window",
                      ErrorSeverity::Invalid);
  vector<double> delta(nlag, 0.0);
  delta[sample_shift] = 1.0;
  vector<double> inv(this->solve_for(delta));
  vector<double> ao(nlag, 0.0);
  for (int i = 0; i < static_cast<int>(ao.size()); ++i) {
    for (int j = 0; j < static_cast<int>(inv.size()); ++j) {
      const int iw = i - j + sample_shift;
      if (iw >= 0 && iw < static_cast<int>(wavelet.size()))
        ao[i] += wavelet[iw] * inv[j];
    }
  }
  ao = this->apply_shaping_wavelet(ao);
  if (l2_norm(ao) > 0.0)
    ao = normalize<double>(ao);
  CoreTimeSeries result(ao.size());
  result.set_dt(dt);
  result.set_t0(-dt * static_cast<double>(sample_shift));
  result.set_tref(TimeReferenceType::Relative);
  result.set_live();
  result.s = ao;
  return result;
}
References mspass::algorithms::deconvolution::ScalarDecon::result, and mspass::algorithms::deconvolution::ScalarDecon::wavelet.
changeparameter()
void mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::changeparameter (const mspass::utility::Metadata & md) virtual
Update operator parameters from Metadata.
Reimplemented from mspass::algorithms::deconvolution::ScalarDecon.
{
  this->read_metadata(md);
}
inverse_wavelet() [1/2]
CoreTimeSeries mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::inverse_wavelet () virtual
Return the inverse wavelet using the default parent time origin.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  return this->inverse_wavelet(0.0);
}
References inverse_wavelet().
inverse_wavelet() [2/2]
CoreTimeSeries mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::inverse_wavelet (const double t0parent) virtual
Return the inverse wavelet with the supplied parent time origin.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  if (wavelet.empty())
    throw MsPASSError("TimeDomainLeastSquareDecon::inverse_wavelet: wavelet "
                      "has not been loaded",
                      ErrorSeverity::Invalid);
  const string base_error("TimeDomainLeastSquareDecon::inverse_wavelet: ");
  const int nlag(this->diagnostic_length());
  if (sample_shift < 0 || sample_shift >= nlag)
    throw MsPASSError(base_error +
                          "zero-lag sample is outside extracted lag window",
                      ErrorSeverity::Invalid);
  vector<double> delta(nlag, 0.0);
  delta[sample_shift] = 1.0;
  vector<double> inv(this->solve_for(delta));
  CoreTimeSeries result(inv.size());
  result.set_dt(dt);
  result.set_t0(-dt * static_cast<double>(sample_shift) - t0parent);
  result.set_tref(TimeReferenceType::Relative);
  result.set_live();
  result.s = inv;
  return result;
}
References mspass::algorithms::deconvolution::ScalarDecon::result, and mspass::algorithms::deconvolution::ScalarDecon::wavelet.
output_shaping_wavelet()
CoreTimeSeries mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::output_shaping_wavelet () virtual
Return the configured output shaping wavelet.
Reimplemented from mspass::algorithms::deconvolution::ScalarDecon.
{
  const string base_error(
      "TimeDomainLeastSquareDecon::output_shaping_wavelet: ");
  const int nlag(this->diagnostic_length());
  if (nlag <= 0)
    return this->ScalarDecon::output_shaping_wavelet();
  if (sample_shift < 0 || sample_shift >= nlag)
    throw MsPASSError(base_error +
                          "zero-lag sample is outside extracted lag window",
                      ErrorSeverity::Invalid);
  vector<double> delta(nlag, 0.0);
  delta[sample_shift] = 1.0;
  vector<double> ws(this->apply_shaping_wavelet(delta));
  if (l2_norm(ws) > 0.0)
    ws = normalize<double>(ws);
  CoreTimeSeries result(ws.size());
  result.set_dt(dt);
  result.set_t0(-dt * static_cast<double>(sample_shift));
  result.set_tref(TimeReferenceType::Relative);
  result.set_live();
  result.s = ws;
  return result;
}
References mspass::algorithms::deconvolution::ScalarDecon::output_shaping_wavelet(), and mspass::algorithms::deconvolution::ScalarDecon::result.
process()
void mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::process () virtual
Solve the damped least-squares deconvolution problem.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  const string base_error("TimeDomainLeastSquareDecon::process:  ");
  result.clear();
  vector<double> model(this->solve_for(data));
  vector<double> predicted(this->apply_wavelet(model));
  data_norm = l2_norm(data);
  double r2(0.0);
  for (int i = 0; i < static_cast<int>(data.size()); ++i) {
    const double r = data[i] - predicted[i];
    r2 += r * r;
  }
  residual_norm = sqrt(r2);
  result = this->apply_shaping_wavelet(model);
  if (result.empty())
    throw MsPASSError(base_error + "computed an empty result",
                      ErrorSeverity::Fatal);
}
References mspass::algorithms::deconvolution::ScalarDecon::data, and mspass::algorithms::deconvolution::ScalarDecon::result.
QCMetrics()
Metadata mspass::algorithms::deconvolution::TimeDomainLeastSquareDecon::QCMetrics () virtual
Return quality-control metrics from the most recent solve.
Implements mspass::algorithms::deconvolution::ScalarDecon.
{
  Metadata md(this->BasicQCMetrics("TimeDomainLeastSquareDecon",
                                   !result.empty()));
  md.put("damping_factor", damp);
  md.put("sample_shift", sample_shift);
  md.put("decon_operator_sample_shift", sample_shift);
  md.put("time_domain_least_square_output_length", output_length);
  md.put("regularization_parameter", regularization_parameter);
  md.put("residual_norm", residual_norm);
  md.put("data_norm", data_norm);
  if (data_norm > 0.0)
    md.put("relative_residual_norm", residual_norm / data_norm);
  return md;
}
References mspass::algorithms::deconvolution::ScalarDecon::BasicQCMetrics(), mspass::utility::Metadata::put(), and mspass::algorithms::deconvolution::ScalarDecon::result.
The documentation for this class was generated from the following files:
/home/runner/work/mspass/mspass/source/cxx/include/mspass/algorithms/deconvolution/TimeDomainLeastSquareDecon.h
/home/runner/work/mspass/mspass/source/cxx/src/lib/algorithms/deconvolution/TimeDomainLeastSquareDecon.cc