FROM continuumio/miniconda3:latest@sha256:1808b31ef43e9c521cde5884ba4df9ec26d8d503a314cea787590f8550358a63

ARG MSPASS_VERSION
ARG MSPASS_VCS_REF

RUN conda install -n base -y conda-build anaconda-client && \
    conda config --add channels conda-forge && \
    conda config --set anaconda_upload no && \
    conda clean -afy

ADD . /mspass
RUN test -n "${MSPASS_VERSION}" \
    && test -n "${MSPASS_VCS_REF}" \
    && mv /mspass /mspasspy_build

ARG PYTHON_VERSION
ARG TARGETARCH
ARG ANACONDA_API_TOKEN

ENV PATH /opt/conda/bin:$PATH
ENV MSPASS_BOOST_ROOT=/tmp/mspass-boost-1.86.0

RUN apt-get update --fix-missing && \
    apt-get install -y cmake wget bzip2 ca-certificates curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN cd /mspasspy_build \
    && export CONDA_BUILD_DEBUG=1 \
    && export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_MSPASSPY="${MSPASS_VERSION}" \
    && PACKAGE_PATH=$(conda build . --python ${PYTHON_VERSION} --output) \
    && conda build . --python ${PYTHON_VERSION} --debug \
    && if [ "$PYTHON_VERSION" = "3.13" ]; then \
       anaconda -t $ANACONDA_API_TOKEN upload $PACKAGE_PATH --label main --label py${PYTHON_VERSION} --force ; \
       else anaconda -t $ANACONDA_API_TOKEN upload $PACKAGE_PATH --label py${PYTHON_VERSION} --force ; fi
