FROM continuumio/miniconda3:latest AS build

RUN conda install -n base -y conda-build && \
    conda config --add channels conda-forge && \
    conda config --set anaconda_upload no && \
    conda clean -afy

ADD . /mspass
ADD .git /mspass/.git
RUN mv /mspass /mspasspy_build && cd /mspasspy_build && git status

ARG PYTHON_VERSION
ARG TARGETARCH

ENV PATH /opt/conda/bin:$PATH
ENV MSPASS_BOOST_ROOT=/tmp/mspass-boost-1.86.0

RUN apt-get update --fix-missing && \
    apt-get install -y cmake wget bzip2 ca-certificates curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN cd /mspasspy_build \
    && export CONDA_BUILD_DEBUG=1 \
    && PACKAGE_PATH=$(conda build . --python ${PYTHON_VERSION} --output) \
    && conda build . --python ${PYTHON_VERSION} --debug \
    && mkdir -p /conda-package \
    && cp "$PACKAGE_PATH" /conda-package/

FROM scratch AS package
COPY --from=build /conda-package/ /
