name: publish_conda

on: [push, pull_request]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python
      - run: pwd
      - run: ls
      - run: conda install conda-build pip
      - run: pip install multitaper
      - run: conda build .