name: build_publish_anaconda

on:
  push:
    branches:
      - 'build-to-wheel-for-conda'
  pull_request:
    branches:
      - '**'    
  workflow_dispatch: # allows you to trigger manually
    
jobs:
  build-and-publish:
    name: ${{ matrix.os }}, Python 3.${{ matrix.python-minor-version }} for conda deployment
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        os: [ ubuntu-latest ] # macos-latest , windows-latest
        python-minor-version: [8] # , 9, 10, 11, 12

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and Publish
      uses: openalea/action-build-publish-anaconda@v0.1.4
      with:
        conda: .
        mamba: true
        python: ${{ matrix.python-minor-version }}
        token: 'cx-8248b24a-767b-41de-ab7d-446cdc390b23'
        publish: 'true'
        label: main