name: publish_conda

on:
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  conda-build-arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          with:
            fetch-depth: 0

      # Setup for Multi-platform image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Build and push Docker image arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: scripts/Dockerfile_conda_build
          platforms: linux/arm64
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            ANACONDA_API_TOKEN=${{ secrets.CONDA_TOKEN }}

  conda-build-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          with:
            fetch-depth: 0

      # Setup for Multi-platform image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Build and push Docker image arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: scripts/Dockerfile_conda_build
          platforms: linux/amd64
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            ANACONDA_API_TOKEN=${{ secrets.CONDA_TOKEN }}

